//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCCCOC13GraphQLModels39ExclusiveTweetUnfollowOperationResponse22ExclusiveTweetUnfollow35ExclusiveTweetUnfollowInvalidResult22ParameterErrorResponse15ParameterErrors : _TtCs12_SwiftObject
{
    MISSING_TYPE *errorMessage;
}

@end

