//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC13GraphQLModels15JobCoreFragment : _TtCs12_SwiftObject
{
    MISSING_TYPE *employmentType;
    MISSING_TYPE *formattedSalary;
    MISSING_TYPE *jobDescription;
    MISSING_TYPE *jobFunction;
    MISSING_TYPE *location;
    MISSING_TYPE *redirectUrl;
    MISSING_TYPE *salaryCurrencyCode;
    MISSING_TYPE *salaryInterval;
    MISSING_TYPE *salaryMax;
    MISSING_TYPE *salaryMin;
    MISSING_TYPE *seniorityLevel;
    MISSING_TYPE *shortDescription;
    MISSING_TYPE *team;
    MISSING_TYPE *title;
}

@end

