//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC9LottieSPM14TextOutputNode : _TtCs12_SwiftObject
{
    MISSING_TYPE *parentTextNode;
    MISSING_TYPE *isEnabled;
    MISSING_TYPE *_xform;
    MISSING_TYPE *_opacity;
    MISSING_TYPE *_strokeColor;
    MISSING_TYPE *_fillColor;
    MISSING_TYPE *_tracking;
    MISSING_TYPE *_strokeWidth;
    MISSING_TYPE *outputPath;
}

@end

