//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCCC13GraphQLModels32TimelinePromotedMetadataFragment19AdMetadataContainer19SkAdNetworkDataList : _TtCs12_SwiftObject
{
    MISSING_TYPE *adNetworkId;
    MISSING_TYPE *campaignId;
    MISSING_TYPE *dstAppId;
    MISSING_TYPE *fidelityType;
    MISSING_TYPE *impressionTimeInMillis;
    MISSING_TYPE *nonce;
    MISSING_TYPE *signature;
    MISSING_TYPE *srcAppId;
    MISSING_TYPE *version;
}

@end

