//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC13GraphQLModels25UndoTweetSettingsFragment : _TtCs12_SwiftObject
{
    MISSING_TYPE *undoOriginalTweetEnabled;
    MISSING_TYPE *undoPollTweetEnabled;
    MISSING_TYPE *undoQuoteTweetEnabled;
    MISSING_TYPE *undoReplyTweetEnabled;
    MISSING_TYPE *undoThreadTweetEnabled;
    MISSING_TYPE *undoTweetDurationSecs;
    MISSING_TYPE *viewTweetAfterSendingEnabled;
}

@end

