//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCOC13GraphQLModels37XPaymentsCustomerActionsSliceFragment5Items23XPaymentsCustomerNotice : _TtCs12_SwiftObject
{
    MISSING_TYPE *callToAction;
    MISSING_TYPE *callToActionUrl;
    MISSING_TYPE *level;
    MISSING_TYPE *subtitle;
    MISSING_TYPE *title;
    MISSING_TYPE *topics;
}

@end

