//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC14TFSTwitterCore36TwitterOpenAppDataStatusModelBuilder : NSObject
{
    MISSING_TYPE *$__lazy_storage_$_dateFormatter;
}

- (void).cxx_destruct;
- (id)init;
- (id)modelObjectWithJSONData:(id)arg1 headerFields:(id)arg2 error:(id *)arg3;

@end

