//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14TFSTwitterCore31TwitterTypeaheadResultsHydrator : _TtCs12_SwiftObject
{
    MISSING_TYPE *identifier;
    MISSING_TYPE *modelContext;
    MISSING_TYPE *usersObservable;
    MISSING_TYPE *hashtagsObservable;
    MISSING_TYPE *topics;
    MISSING_TYPE *events;
    MISSING_TYPE *lists;
    MISSING_TYPE *timeout;
    MISSING_TYPE *completion;
    MISSING_TYPE *users;
    MISSING_TYPE *hashtags;
    MISSING_TYPE *usersObserver;
    MISSING_TYPE *hashtagsObserver;
    MISSING_TYPE *usersCallBackHappened;
    MISSING_TYPE *hashtagsCallBackHappened;
    MISSING_TYPE *finished;
}

@end

