//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCOC13GraphQLModels42PaymentsCreateAuthSessionOperationResponse28CreateXPaymentsAuthSessionV220XPaymentsAuthSession : _TtCs12_SwiftObject
{
    MISSING_TYPE *challengeId;
    MISSING_TYPE *customerId;
    MISSING_TYPE *expiryTimeMillis;
    MISSING_TYPE *providerTokens;
    MISSING_TYPE *sessionId;
    MISSING_TYPE *status;
}

@end

