//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC17DMSharedUtilities25NotificationFormatterImpl : _TtCs12_SwiftObject
{
}

- (id)fallbackGroupTitleGroupMemberName:(id)arg1 groupMemberCount:(int)arg2 senderName:(id)arg3;
- (id)bodyText:(id)arg1 attachmentType:(id)arg2;

@end

