//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC13GraphQLModels28TimelineEventSummaryFragment : _TtCs12_SwiftObject
{
    MISSING_TYPE *badge;
    MISSING_TYPE *event;
    MISSING_TYPE *eventDisplayType;
    MISSING_TYPE *eventUrl;
    MISSING_TYPE *groupedTrends;
    MISSING_TYPE *image;
    MISSING_TYPE *media;
    MISSING_TYPE *promotedMetadata;
    MISSING_TYPE *publisherResults;
    MISSING_TYPE *richContext;
    MISSING_TYPE *scoreEvent;
    MISSING_TYPE *socialContext;
    MISSING_TYPE *supportingText;
    MISSING_TYPE *timeString;
    MISSING_TYPE *title;
}

@end

