//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14TFSTwitterCore19TwitterCommerceShop : _TtCs12_SwiftObject
{
    MISSING_TYPE *shopName;
    MISSING_TYPE *shopDescription;
    MISSING_TYPE *isEnabled;
    MISSING_TYPE *merchant;
}

@end

