//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14GraphQLActions37UserStoreKit2PurchaseRedeemV2Mutation : _TtCs12_SwiftObject
{
    MISSING_TYPE *pendingStateNode;
    MISSING_TYPE *additionalHeaderFields;
    MISSING_TYPE *appleEnvironment;
    MISSING_TYPE *bundleID;
    MISSING_TYPE *jwsRepresentation;
    MISSING_TYPE *redemptionMetadataInput;
    MISSING_TYPE *includeSuperFollowRedemptionFields;
}

@end

