//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSString;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface APMAlarm : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_source> *_timer;
    NSString *_name;
    NSDate *_scheduledTimestamp;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSDate *scheduledTimestamp; // @synthesize scheduledTimestamp=_scheduledTimestamp;
- (void)dealloc;
- (_Bool)hasActiveTimer;
- (void)cancel;
- (void)runAfterDelay:(double)arg1 withBlock:(CDUnknownBlockType)arg2;
- (id)initWithDispatchQueue:(id)arg1 name:(id)arg2;

@end

