//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSPointerArray;

@interface APMPObjectManager : NSObject
{
    NSPointerArray *_roots;
    NSPointerArray *_objects;
    _Bool _garbageCollectionEnabled;
}

+ (id)subarrayWithArray:(id)arg1 range:(struct _NSRange)arg2 scope:(id)arg3;
+ (id)arrayValueWithArray:(id)arg1 scope:(id)arg2;
+ (id)arrayValueWithScope:(id)arg1;
+ (id)mapValueWithScope:(id)arg1;
+ (id)functionValueWithFunctionName:(id)arg1 parameterNames:(id)arg2 statements:(id)arg3 definingScope:(id)arg4;
- (void).cxx_destruct;
- (id)roots;
- (id)trackedObjects;
- (void)sweep;
- (void)mark;
- (void)collectGarbage;
- (void)addObject:(id)arg1;
- (void)addRoot:(id)arg1;
- (id)initWithGarbageCollectionEnabled:(_Bool)arg1;

@end

