//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class FIRInstallationsBackoffEventData, NSString;

@interface FIRInstallationsBackoffController : NSObject
{
    CDUnknownBlockType _currentDateProvider;
    FIRInstallationsBackoffEventData *_lastEventData;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FIRInstallationsBackoffEventData *lastEventData; // @synthesize lastEventData=_lastEventData;
@property(readonly, nonatomic) CDUnknownBlockType currentDateProvider; // @synthesize currentDateProvider=_currentDateProvider;
- (void)registerEvent:(long long)arg1;
- (_Bool)isNextRequestAllowed;
- (id)initWithCurrentDateProvider:(CDUnknownBlockType)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

