//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSSet.h>

@interface NSSet (TFSAdditions)
+ (id)tfs_setWithUnionedSets:(id)arg1;
- (id)tfs_setByRemovingObjectsFromSet:(id)arg1;
- (id)tfs_mapWithBlock:(CDUnknownBlockType)arg1;
- (id)tfs_map:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)tfs_map:(SEL)arg1 withObject:(id)arg2;
- (id)tfs_map:(SEL)arg1;
- (void)XKotlin_releaseAsAssociatedObject;
- (struct ObjHeader *)XKotlin_toKotlin:(struct ObjHeader **)arg1;
@end

