//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface TAVAnalyticsAmplifyCardIdentifier : NSObject
{
    NSString *_contentId;
    NSString *_vmapUrl;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *vmapUrl; // @synthesize vmapUrl=_vmapUrl;
@property(readonly, copy, nonatomic) NSString *contentId; // @synthesize contentId=_contentId;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithContentId:(id)arg1 vmapUrl:(id)arg2;

@end

