//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSOperation, NSOperationQueue;

@interface TAVConcurrentOperationCoordinator : NSObject
{
    NSOperationQueue *_queue;
    NSArray *_operations;
    NSOperation *_completionOperation;
}

- (void).cxx_destruct;
- (void)execute;
- (id)initWithConcurrentOperations:(id)arg1 completionOperation:(id)arg2;

@end

