//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@protocol TAVPixelBufferSource
- (void)captureSnapshotWithCompletion:(void (^)(UIImage *))arg1;
- (struct __CVBuffer *)copyPixelBufferForTime:(double)arg1;
- (_Bool)hasNewPixelBufferForTime:(double)arg1;
- (struct __CVBuffer *)lastAcquiredPixelBuffer;
@end

