//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSHashTable;

@interface TAVPlaybackObserverGroup : NSObject
{
    NSHashTable *_weakObservers;
}

- (void).cxx_destruct;
- (void)player:(id)arg1 didUpdatePlaybackState:(id)arg2;
- (id)initWithObservers:(id)arg1;
- (id)init;
@property(readonly, nonatomic) NSArray *observers;

@end

