//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface TAVScribeThriftLiveBroadcastDetails : NSObject
{
    NSString *_hostBroadcastId;
    NSString *_targetBroadcastId;
    long long _broadcastState;
}

- (void).cxx_destruct;
@property(nonatomic) long long broadcastState; // @synthesize broadcastState=_broadcastState;
@property(copy, nonatomic) NSString *targetBroadcastId; // @synthesize targetBroadcastId=_targetBroadcastId;
@property(copy, nonatomic) NSString *hostBroadcastId; // @synthesize hostBroadcastId=_hostBroadcastId;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)marshallerDictionary;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)initWithHostBroadcastId:(id)arg1 targetBroadcastId:(id)arg2 broadcastState:(long long)arg3;

@end

