//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface TAVScribeContext : NSObject
{
    NSString *_page;
    NSString *_section;
    NSString *_component;
}

+ (id)scribeContextWithPage:(id)arg1 section:(id)arg2 component:(id)arg3;
+ (id)scribeContextWithPage:(id)arg1 section:(id)arg2;
+ (id)scribeContextWithPage:(id)arg1;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *component; // @synthesize component=_component;
@property(readonly, copy, nonatomic) NSString *section; // @synthesize section=_section;
@property(readonly, copy, nonatomic) NSString *page; // @synthesize page=_page;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithPage:(id)arg1 section:(id)arg2 component:(id)arg3;
- (id)init;

@end

