//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSString, TFNAttributedTextModel, UIColor;
@protocol TFNAttributedTextViewDelegate;

@interface TFNAttributedTextViewConfiguration
{
    TFNAttributedTextModel *_textModel;
    NSArray *_activeRanges;
    long long _verticalAlignment;
    UIColor *_selectionColor;
    double _preferredMaxLayoutWidth;
    id <TFNAttributedTextViewDelegate> _delegate;
    id __tfn_retained_delegate;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id _tfn_retained_delegate; // @synthesize _tfn_retained_delegate=__tfn_retained_delegate;
@property(nonatomic) __weak id <TFNAttributedTextViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double preferredMaxLayoutWidth; // @synthesize preferredMaxLayoutWidth=_preferredMaxLayoutWidth;
@property(retain, nonatomic) UIColor *selectionColor; // @synthesize selectionColor=_selectionColor;
@property(nonatomic) long long verticalAlignment; // @synthesize verticalAlignment=_verticalAlignment;
@property(copy, nonatomic) NSArray *activeRanges; // @synthesize activeRanges=_activeRanges;
@property(retain, nonatomic) TFNAttributedTextModel *textModel; // @synthesize textModel=_textModel;
- (id)makeSwiftUIRepresentedView;
- (void)_tfn_copyFromComponent_preferredMaxLayoutWidth:(id)arg1;
- (void)_tfn_copyToObject_preferredMaxLayoutWidth:(id)arg1;
- (void)_tfn_copyFromComponent_selectionColor:(id)arg1;
- (void)_tfn_copyToObject_selectionColor:(id)arg1;
- (void)_tfn_copyFromComponent_verticalAlignment:(id)arg1;
- (void)_tfn_copyToObject_verticalAlignment:(id)arg1;
- (void)_tfn_copyFromComponent_delegate:(id)arg1;
- (void)_tfn_copyToObject_delegate:(id)arg1;
- (void)setDelegate:(id)arg1 isRetained:(_Bool)arg2;
- (void)_tfn_copyFromComponent_activeRanges:(id)arg1;
- (void)_tfn_copyToObject_activeRanges:(id)arg1;
- (void)_tfn_copyFromComponent_textModel:(id)arg1;
- (void)_tfn_copyToObject_textModel:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

