//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface TFNAudiowaveArrayViewModel : NSObject
{
    float *_values;
    unsigned long long _valuesLength;
    unsigned long long _valuesCount;
    double _duration;
}

@property(nonatomic) double duration; // @synthesize duration=_duration;
- (void)calculateValues:(out float *)arg1 forNumberOfBars:(unsigned long long)arg2;
- (void)appendValue:(double)arg1;
- (id)valuesWithNumberOfBarsPerSecond:(double)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

