//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableArray, TFNComposableViewSet;

@interface TFNComposableViewSetUpdates : NSObject
{
    TFNComposableViewSet *_viewSet;
    NSDictionary *_updateInfo;
    NSMutableArray *_updates;
}

- (void).cxx_destruct;
- (void)_tfn_performOnUpdates:(CDUnknownBlockType)arg1 passingTest:(CDUnknownBlockType)arg2;
- (void)performAnimationCompletionUpdatesPassingTest:(CDUnknownBlockType)arg1;
- (void)performAnimationCompletionUpdates;
- (void)performAnimationUpdatesPassingTest:(CDUnknownBlockType)arg1;
- (void)performAnimationUpdates;
- (void)performPreAnimationUpdatesPassingTest:(CDUnknownBlockType)arg1;
- (void)performPreAnimationUpdates;
- (void)performUpdatesPassingTest:(CDUnknownBlockType)arg1;
- (void)performUpdates;
- (void)prepare;
- (void)addUpdateForViewAdapter:(id)arg1 type:(long long)arg2;
- (id)objectAtIndexedSubscript:(long long)arg1;
- (id)updatesPassingTest:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSArray *updates;
- (id)initWithViewSet:(id)arg1 updateInfo:(id)arg2;

@end

