//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol TFNCellVisibilityListener;

@interface TFNCellVisibilityWeakRelay : NSObject
{
    id <TFNCellVisibilityListener> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <TFNCellVisibilityListener> delegate; // @synthesize delegate=_delegate;
- (void)cellDidEndDisplayingFromViewport:(id)arg1 inDataViewController:(id)arg2;
- (void)cellDidEndDisplaying:(id)arg1 inDataViewController:(id)arg2 reason:(unsigned long long)arg3;
- (void)cellWillEndDisplaying:(id)arg1 inDataViewController:(id)arg2;
- (void)cellDidDisplay:(id)arg1 inDataViewController:(id)arg2 withVisibilityPercentage:(double)arg3 visibilityState:(unsigned long long)arg4;
- (void)cellWillDisplay:(id)arg1 inDataViewController:(id)arg2;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

