//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class UIViewController;

@interface TFNContainerViewControllerEntry : NSObject
{
    _Bool _visible;
    _Bool _transitioning;
    _Bool _attached;
    UIViewController *_viewController;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool attached; // @synthesize attached=_attached;
@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
- (void)endAppearanceTransition:(_Bool)arg1 animated:(_Bool)arg2;
- (void)beginAppearanceTransition:(_Bool)arg1 animated:(_Bool)arg2;

@end

