//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString, TFNComposableViewAdapterSet, TFNComposableViewLayoutStateSet, TFNReusableViewCache, UIView;
@protocol TFNComposableViewHost, TFNComposableViewLayoutTracer, TFNComposableViewPrepareForReuseTracer;

@interface TFNComposableViewSet : NSObject
{
    NSMutableArray *_views;
    TFNReusableViewCache *_reusableViewCache;
    UIView<TFNComposableViewHost> *_hostView;
    id <TFNComposableViewLayoutTracer> _layoutTracer;
    id <TFNComposableViewPrepareForReuseTracer> _prepareForReuseTracer;
    TFNComposableViewAdapterSet *_viewAdapterSet;
    CDUnknownBlockType _addToHostViewBlock;
    TFNComposableViewLayoutStateSet *_layoutStateSet;
    id _viewModel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) TFNComposableViewLayoutStateSet *layoutStateSet; // @synthesize layoutStateSet=_layoutStateSet;
@property(copy, nonatomic) CDUnknownBlockType addToHostViewBlock; // @synthesize addToHostViewBlock=_addToHostViewBlock;
@property(readonly, nonatomic) TFNComposableViewAdapterSet *viewAdapterSet; // @synthesize viewAdapterSet=_viewAdapterSet;
@property(nonatomic) __weak id <TFNComposableViewPrepareForReuseTracer> prepareForReuseTracer; // @synthesize prepareForReuseTracer=_prepareForReuseTracer;
@property(nonatomic) __weak id <TFNComposableViewLayoutTracer> layoutTracer; // @synthesize layoutTracer=_layoutTracer;
@property(readonly, nonatomic) __weak UIView<TFNComposableViewHost> *hostView; // @synthesize hostView=_hostView;
@property(retain, nonatomic) TFNReusableViewCache *reusableViewCache; // @synthesize reusableViewCache=_reusableViewCache;
- (void)_tfn_removeView:(id)arg1 fromHostViewWithViewAdapter:(id)arg2;
- (void)_tfn_setupStateForView:(id)arg1 withViewAdapter:(id)arg2 includeViewModel:(_Bool)arg3 layoutState:(_Bool)arg4;
- (void)_tfn_addView:(id)arg1 toHostViewWithViewAdapter:(id)arg2;
- (void)_tfn_gatherViewSetUpdates:(id)arg1 toViewWithAdapter:(id)arg2 forViewModelUpdateWithInfo:(id)arg3 isLayoutStateCompatible:(_Bool)arg4;
- (_Bool)applyViewModelUpdateWithInfo:(id)arg1 toViewWithAdapter:(id)arg2 isLayoutStateCompatible:(_Bool)arg3;
- (_Bool)isLayoutStateCompatibleWithViewModel;
- (id)viewSetUpdatesForViewModel:(id)arg1 didUpdateWithInfo:(id)arg2;
- (void)viewModel:(id)arg1 didUpdateWithInfo:(id)arg2;
- (void)enumerateViewsUsingBlock:(CDUnknownBlockType)arg1;
- (void)setObject:(id)arg1 atIndexedSubscript:(long long)arg2;
- (id)objectAtIndexedSubscript:(long long)arg1;
- (id)init;
- (id)initWithHostView:(id)arg1 viewAdapterSet:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

