//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/NSObject-Protocol.h>

@class NSIndexPath, TFNDataViewHelper;

@protocol TFNDataViewHelperDelegate <NSObject>
- (unsigned long long)dataViewHelper:(TFNDataViewHelper *)arg1 sectionBreaksForIndexPath:(NSIndexPath *)arg2;
- (void)dataViewDidUpdateForHelper:(TFNDataViewHelper *)arg1 type:(long long)arg2 animated:(_Bool)arg3;
- (_Bool)dataViewWillUpdateForHelper:(TFNDataViewHelper *)arg1 type:(long long)arg2;

@optional
- (void)dataViewHelper:(TFNDataViewHelper *)arg1 performBatchUpdates:(void (^)(void))arg2 completion:(void (^)(_Bool))arg3;
- (void)endDataViewUpdatesForHelper:(TFNDataViewHelper *)arg1;
- (void)beginDataViewUpdatesForHelper:(TFNDataViewHelper *)arg1;
@end

