//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TFNFloatingActionButtonSubItemLayoutManager
{
    double _initialRotation;
}

@property(nonatomic) double initialRotation; // @synthesize initialRotation=_initialRotation;
- (double)_tfn_rotationAtIndex:(unsigned long long)arg1 withProgress:(double)arg2;
- (double)_tfn_scaleAtIndex:(unsigned long long)arg1 withProgress:(double)arg2;
- (CDStruct_562ed2e6)layoutAtIndex:(unsigned long long)arg1 withProgress:(double)arg2;

@end

