//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface TFNFormFieldAttributedTextAccessoryProvider
{
    CDUnknownBlockType _activeRangeHandler;
}

- (void).cxx_destruct;
- (void)attributedTextView:(id)arg1 didTapRange:(id)arg2 rect:(struct CGRect)arg3;
- (id)private_attributedStringForText:(id)arg1 activeRanges:(id)arg2 alignment:(long long)arg3 font:(id)arg4 color:(id)arg5;
- (struct CGSize)sizeForAccessoryView:(id)arg1 thatFitsSize:(struct CGSize)arg2 text:(id)arg3 layoutMetrics:(id)arg4;
- (_Bool)shouldShowAccessoryView:(id)arg1 forText:(id)arg2;
- (struct UIEdgeInsets)edgeInsetsForAccessoryView:(id)arg1 textFieldEdgeInsets:(struct UIEdgeInsets)arg2;
- (long long)accessoryViewLocation;
- (id)accessoryView;
- (void)setText:(id)arg1 forFormFieldView:(id)arg2 withActiveRanges:(id)arg3 alignment:(long long)arg4 font:(id)arg5 color:(id)arg6;
- (void)setAttributedText:(id)arg1 forFormFieldView:(id)arg2 withActiveRanges:(id)arg3;
- (id)initWithActiveRangeHandler:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

