//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TFNGenericItem : NSObject
{
    CDUnknownBlockType _cellForRowAtIndexPathBlock;
    CDUnknownBlockType _collectionViewCellForItemAtIndexPathBlock;
    CDUnknownBlockType _heightForRowAtIndexPathBlock;
    CDUnknownBlockType _collectionViewSizeForItemAtIndexPathBlock;
    CDUnknownBlockType _didSelectRowAtIndexPathBlock;
    CDUnknownBlockType _shouldSelectRowAtIndexPathBlock;
    CDUnknownBlockType _shouldHighlightRowAtIndexPathBlock;
    CDUnknownBlockType _debugStringsBlock;
    id _userInfo;
}

+ (id)bareText:(id)arg1 color:(id)arg2;
+ (id)blankWithHeight:(double)arg1;
+ (id)dividerWithTitle:(id)arg1 textColor:(id)arg2;
+ (id)centeredItemWithTitle:(id)arg1;
+ (id)itemWithTitle:(id)arg1 subtitle:(id)arg2 disclosure:(_Bool)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(copy, nonatomic) CDUnknownBlockType debugStringsBlock; // @synthesize debugStringsBlock=_debugStringsBlock;
@property(copy, nonatomic) CDUnknownBlockType shouldHighlightRowAtIndexPathBlock; // @synthesize shouldHighlightRowAtIndexPathBlock=_shouldHighlightRowAtIndexPathBlock;
@property(copy, nonatomic) CDUnknownBlockType shouldSelectRowAtIndexPathBlock; // @synthesize shouldSelectRowAtIndexPathBlock=_shouldSelectRowAtIndexPathBlock;
@property(copy, nonatomic) CDUnknownBlockType didSelectRowAtIndexPathBlock; // @synthesize didSelectRowAtIndexPathBlock=_didSelectRowAtIndexPathBlock;
@property(copy, nonatomic) CDUnknownBlockType collectionViewSizeForItemAtIndexPathBlock; // @synthesize collectionViewSizeForItemAtIndexPathBlock=_collectionViewSizeForItemAtIndexPathBlock;
@property(copy, nonatomic) CDUnknownBlockType heightForRowAtIndexPathBlock; // @synthesize heightForRowAtIndexPathBlock=_heightForRowAtIndexPathBlock;
@property(copy, nonatomic) CDUnknownBlockType collectionViewCellForItemAtIndexPathBlock; // @synthesize collectionViewCellForItemAtIndexPathBlock=_collectionViewCellForItemAtIndexPathBlock;
@property(copy, nonatomic) CDUnknownBlockType cellForRowAtIndexPathBlock; // @synthesize cellForRowAtIndexPathBlock=_cellForRowAtIndexPathBlock;
- (id)tfs_debugStrings;

@end

