//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSAttributedString, NSString;

@interface TFNHashflagString : NSObject
{
    NSString *_originalText;
    NSAttributedString *_attributedString;
    NSArray *_hashflagsDownloading;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *hashflagsDownloading; // @synthesize hashflagsDownloading=_hashflagsDownloading;
@property(readonly, copy, nonatomic) NSAttributedString *attributedString; // @synthesize attributedString=_attributedString;
@property(readonly, copy, nonatomic) NSString *originalText; // @synthesize originalText=_originalText;
- (id)initWithString:(id)arg1 font:(id)arg2;

@end

