//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface TFNInlineFeedbackConfirmationStateConfiguration : NSObject
{
    MISSING_TYPE *affirmationTitle;
    MISSING_TYPE *negationTitle;
    MISSING_TYPE *confirmationUpdateCompletionHandler;
}

+ (id)customizedMessageWithAffirmationTitle:(id)arg1 negationTitle:(id)arg2 confirmationUpdateCompletionHandler:(CDUnknownBlockType)arg3;
+ (id)defaultMessageWithTitle:(id)arg1 confirmationUpdateCompletionHandler:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (id)init;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic, readonly) long long hash;
- (id)copyWithZone:(void *)arg1;

@end

