//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIView;

@interface TFNLegacyFormInputViewContentViewController
{
    UIView *_inputView;
    CDUnknownBlockType _willLoseFocusCallback;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType willLoseFocusCallback; // @synthesize willLoseFocusCallback=_willLoseFocusCallback;
@property(readonly, nonatomic) UIView *inputView; // @synthesize inputView=_inputView;
- (void)resignFocus;
- (void)_tfn_didTapOutsideContent:(id)arg1;
- (void)pinContentToHostController:(id)arg1 hostCell:(id)arg2;
- (id)initWithInputView:(id)arg1;

@end

