//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, TFNLayoutMetricsLayoutGuide, UILayoutGuide, UIView;

@interface TFNLayoutMetricsLayoutGuides : NSObject
{
    UIView *_view;
    TFNLayoutMetricsLayoutGuide *_displayArea;
    TFNLayoutMetricsLayoutGuide *_content;
    TFNLayoutMetricsLayoutGuide *_avatar;
    TFNLayoutMetricsLayoutGuide *_username;
    TFNLayoutMetricsLayoutGuide *_body;
    TFNLayoutMetricsLayoutGuide *_accessory;
    NSMutableArray *_allLayoutMetricsLayoutGuides;
    UIView *_canvasView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIView *canvasView; // @synthesize canvasView=_canvasView;
@property(readonly, nonatomic) UILayoutGuide *accessory;
@property(readonly, nonatomic) UILayoutGuide *body;
@property(readonly, nonatomic) UILayoutGuide *username;
@property(readonly, nonatomic) UILayoutGuide *avatar;
@property(readonly, nonatomic) UILayoutGuide *content;
@property(readonly, nonatomic) UILayoutGuide *displayArea;

@end

