//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, TFNModalSheetViewController;

@interface TFNModalSheetLayoutModeFloatingController : NSObject
{
    TFNModalSheetViewController *_modalViewController;
}

- (void).cxx_destruct;
- (void)updateModalPresentationStyle;
- (void)updateModalContentFrames;
- (void)updateCurrentHeight:(double)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)getNavigationBarFrameHeightAdjustment:(inout double *)arg1 yOffset:(inout double *)arg2;
@property(readonly, nonatomic) double totalAnimationDuration;
- (struct CGSize)modalContentSizeWithLayoutMode:(long long)arg1 availableSize:(struct CGSize)arg2;
@property(readonly, nonatomic) double initialCurrentHeight;
@property(readonly, nonatomic) struct UIEdgeInsets calculateModalContentSafeAreaInsets;
- (double)maximumHeight;
- (id)statusBarControllingViewController:(_Bool)arg1;
@property(readonly, nonatomic) struct UIEdgeInsets modalContentViewVisibleEdgeInsets;
@property(readonly, nonatomic) long long layoutModeForLeavingFullScreen;
@property(readonly, nonatomic) long long layoutModeForTransitioningToFullScreen;
- (_Bool)requiresRedisplayToChangeToLayoutMode:(long long)arg1;
- (void)addModalContentViewControllerView:(id)arg1;
- (void)willTransitionOutToNewLayoutMode:(id)arg1;
- (void)willTransitionInFromOldLayoutMode:(id)arg1;
@property(readonly, nonatomic) long long layoutMode;
- (id)initWithModalViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

