//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class CALayer, NSString, TFNModuleHeaderActionConfiguration, UIButton, UIImageView, UILabel;

@interface TFNModuleHeaderView : UIView
{
    UILabel *_headerTextLabel;
    UILabel *_detailHeaderTextLabel;
    UIButton *_caretButton;
    UIImageView *_iconImageView;
    NSString *_entityToken;
    UIView *_actionView;
    TFNModuleHeaderActionConfiguration *_actionConfiguration;
    CALayer *_separatorCoverLayer;
}

+ (double)heightWithHeaderText:(id)arg1 detailText:(id)arg2 actionSize:(struct CGSize)arg3 iconHidden:(_Bool)arg4 caretHidden:(_Bool)arg5 layoutMetrics:(id)arg6 headerFont:(id)arg7 detailFont:(id)arg8;
+ (double)heightWithHeaderText:(id)arg1 detailText:(id)arg2 actionSize:(struct CGSize)arg3 iconHidden:(_Bool)arg4 caretHidden:(_Bool)arg5 layoutMetrics:(id)arg6;
+ (double)heightWithHeaderText:(id)arg1 detailText:(id)arg2 actionConfiguration:(id)arg3 iconHidden:(_Bool)arg4 caretHidden:(_Bool)arg5 layoutMetrics:(id)arg6;
+ (long long)numberOfLinesAllowedInDetailText;
- (void).cxx_destruct;
@property(retain, nonatomic) CALayer *separatorCoverLayer; // @synthesize separatorCoverLayer=_separatorCoverLayer;
@property(retain, nonatomic) TFNModuleHeaderActionConfiguration *actionConfiguration; // @synthesize actionConfiguration=_actionConfiguration;
@property(readonly, nonatomic) UIView *actionView; // @synthesize actionView=_actionView;
@property(copy, nonatomic) NSString *entityToken; // @synthesize entityToken=_entityToken;
@property(readonly, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(readonly, nonatomic) UIButton *caretButton; // @synthesize caretButton=_caretButton;
@property(readonly, nonatomic) UILabel *detailHeaderTextLabel; // @synthesize detailHeaderTextLabel=_detailHeaderTextLabel;
@property(readonly, nonatomic) UILabel *headerTextLabel; // @synthesize headerTextLabel=_headerTextLabel;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)setActionView:(id)arg1;
- (id)_tfn_findTableHeaderOrCellSuperview;
- (void)didMoveToSuperview;
- (id)initWithFrame:(struct CGRect)arg1;

@end

