//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class TFNButton, UIColor;

@interface TFNMenuSheetActionRoundedButtonCell
{
    UIColor *_buttonBackgroundColor;
    UIColor *_buttonHighlightColor;
    TFNButton *_button;
    struct UIEdgeInsets _overrideContentEdgeInsets;
}

- (void).cxx_destruct;
@property(nonatomic) struct UIEdgeInsets overrideContentEdgeInsets; // @synthesize overrideContentEdgeInsets=_overrideContentEdgeInsets;
@property(retain, nonatomic) TFNButton *button; // @synthesize button=_button;
@property(retain, nonatomic) UIColor *buttonHighlightColor; // @synthesize buttonHighlightColor=_buttonHighlightColor;
@property(retain, nonatomic) UIColor *buttonBackgroundColor; // @synthesize buttonBackgroundColor=_buttonBackgroundColor;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

