//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TFNNavigationTransitionContext : NSObject
{
    CDUnknownBlockType _fromBlurFactory;
    CDUnknownBlockType _toBlurFactory;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType toBlurFactory; // @synthesize toBlurFactory=_toBlurFactory;
@property(copy, nonatomic) CDUnknownBlockType fromBlurFactory; // @synthesize fromBlurFactory=_fromBlurFactory;

@end

