//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSNumber, NSString, TFNPromptSeparatorSpec, UIColor;

@interface TFNPromptButtonSpec : NSObject
{
    _Bool _preferFullWidth;
    _Bool _renderAsTemplate;
    NSString *_title;
    UIColor *_backgroundColor;
    UIColor *_highlightBackgroundColor;
    UIColor *_borderColor;
    UIColor *_tintColor;
    UIColor *_titleColor;
    NSString *_imageName;
    CDUnknownBlockType _action;
    NSNumber *_imageTitlePadding;
    TFNPromptSeparatorSpec *_separatorSpec;
    long long _style;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) long long style; // @synthesize style=_style;
@property(readonly, nonatomic) TFNPromptSeparatorSpec *separatorSpec; // @synthesize separatorSpec=_separatorSpec;
@property(readonly, nonatomic) NSNumber *imageTitlePadding; // @synthesize imageTitlePadding=_imageTitlePadding;
@property(readonly, nonatomic) _Bool renderAsTemplate; // @synthesize renderAsTemplate=_renderAsTemplate;
@property(readonly, nonatomic) _Bool preferFullWidth; // @synthesize preferFullWidth=_preferFullWidth;
@property(readonly, nonatomic) CDUnknownBlockType action; // @synthesize action=_action;
@property(readonly, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;
@property(readonly, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(readonly, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(readonly, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(readonly, nonatomic) UIColor *highlightBackgroundColor; // @synthesize highlightBackgroundColor=_highlightBackgroundColor;
@property(readonly, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)private_buttonAction:(id)arg1;
- (id)private_buttonForSizeClass:(long long)arg1;
- (id)barButtonItem;
- (id)buttonWithSizeClass:(long long)arg1;
- (id)initWithTitle:(id)arg1 style:(long long)arg2 tintColor:(id)arg3 backgroundColor:(id)arg4 highlightBackgroundColor:(id)arg5 titleColor:(id)arg6 borderColor:(id)arg7 imageName:(id)arg8 renderAsTemplate:(_Bool)arg9 imageTitlePadding:(id)arg10 preferFullWidth:(_Bool)arg11 separatorSpec:(id)arg12 action:(CDUnknownBlockType)arg13;
- (id)initWithTitle:(id)arg1 style:(long long)arg2 tintColor:(id)arg3 imageName:(id)arg4 renderAsTemplate:(_Bool)arg5 imageTitlePadding:(id)arg6 preferFullWidth:(_Bool)arg7 separatorSpec:(id)arg8 action:(CDUnknownBlockType)arg9;
- (id)initWithTitle:(id)arg1 style:(long long)arg2 tintColor:(id)arg3 imageName:(id)arg4 preferFullWidth:(_Bool)arg5 action:(CDUnknownBlockType)arg6;
- (id)initWithTitle:(id)arg1 style:(long long)arg2 tintColor:(id)arg3 action:(CDUnknownBlockType)arg4;
- (id)initWithTitle:(id)arg1 style:(long long)arg2 action:(CDUnknownBlockType)arg3;

@end

