//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSString, UIColor, UIFont, UILabel;

@interface TFNTextTooltipContentView : UIView
{
    _Bool _shouldCenterLabel;
    CDUnknownBlockType contentSizeChangedBlock;
    UILabel *_label;
    struct UIEdgeInsets _contentEdgeInsets;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(nonatomic) struct UIEdgeInsets contentEdgeInsets; // @synthesize contentEdgeInsets=_contentEdgeInsets;
@property(nonatomic) _Bool shouldCenterLabel; // @synthesize shouldCenterLabel=_shouldCenterLabel;
@property(copy, nonatomic) CDUnknownBlockType contentSizeChangedBlock; // @synthesize contentSizeChangedBlock;
- (struct CGSize)private_labelSizeThatFits:(struct CGSize)arg1;
- (void)tfn_fontSizeChanged;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) UIFont *labelFont;
@property(retain, nonatomic) UIColor *labelColor;
@property(copy, nonatomic) NSString *labelText;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

