//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/NSObject-Protocol.h>

@class TFNTooltipView;

@protocol TFNTooltipViewDelegate <NSObject>
- (void)tooltipViewDidTap:(TFNTooltipView *)arg1;

@optional
- (void)tooltipViewDidDismiss:(TFNTooltipView *)arg1;
- (void)tooltipViewWillDismiss:(TFNTooltipView *)arg1;
- (void)tooltipViewDidShow:(TFNTooltipView *)arg1;
- (void)tooltipViewWillShow:(TFNTooltipView *)arg1;
@end

