//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class NSHashTable, NSString, UIImpactFeedbackGenerator, UINotificationFeedbackGenerator, UISelectionFeedbackGenerator;

@interface TFNViewController : UIViewController
{
    long long _transitionState;
    NSHashTable *_eventObservers;
    _Bool _hasBeenPresented;
    _Bool _hasBeenDismissed;
    _Bool _visible;
    _Bool _changingInterfaceOrientation;
    UIImpactFeedbackGenerator *_impactFeedbackGenerator;
}

+ (id)viewControllerEventObservers;
+ (void)removeViewControllerEventObserver:(id)arg1;
+ (void)addViewControllerEventObserver:(id)arg1;
+ (id)eventObservers;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isChangingInterfaceOrientation) _Bool changingInterfaceOrientation; // @synthesize changingInterfaceOrientation=_changingInterfaceOrientation;
@property(readonly, nonatomic) UIImpactFeedbackGenerator *impactFeedbackGenerator; // @synthesize impactFeedbackGenerator=_impactFeedbackGenerator;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"UIImpactFeedbackGenerator",?,R,N,V_impactFeedbackGenerator

@property(readonly, nonatomic, getter=isVisible) _Bool visible; // @synthesize visible=_visible;
- (id)keyCommands;
- (void)performHapticFeedback:(unsigned long long)arg1;
- (void)prepareHapticFeedback:(unsigned long long)arg1;
- (void)tfn_previewingStateDidChange;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (id)eventObservers;
- (void)removeViewControllerEventObserver:(id)arg1;
- (void)addViewControllerEventObserver:(id)arg1;
- (void)voiceOverStatusDidChange:(id)arg1;
- (void)applicationUserDidTakeScreenshot:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationWillEnterForegroundFromBackground:(id)arg1;
- (void)_tfn_applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)viewDidFullyDisappear:(_Bool)arg1;
- (void)viewWillFullyDisappear:(_Bool)arg1;
- (void)viewDidFullyAppear:(_Bool)arg1;
- (void)viewWillFullyAppear:(_Bool)arg1;
- (_Bool)extendedLayoutIncludesOpaqueBars;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)_enforceFloatingViews;
- (void)viewWillLayoutSubviews;
- (void)viewControllerDidDismissAnimated:(_Bool)arg1;
- (void)viewControllerWillDismissAnimated:(_Bool)arg1;
- (void)viewControllerDidPresentAnimated:(_Bool)arg1;
- (void)viewControllerWillPresentAnimated:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)private_configureHapticFeedback;
- (void)_prepareNotifications;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) UINotificationFeedbackGenerator *notificationFeedbackGenerator;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"UINotificationFeedbackGenerator",?,R,N

@property(readonly, nonatomic) UISelectionFeedbackGenerator *selectionFeedbackGenerator;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"UISelectionFeedbackGenerator",?,R,N

@property(readonly) Class superclass;

@end

