//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TFSAuthOAuth1Helper : NSObject
{
    double _oAuthClockDelta;
}

@property double oAuthClockDelta; // @synthesize oAuthClockDelta=_oAuthClockDelta;
- (void)signRequest:(id)arg1 parameters:(id)arg2 appCredential:(id)arg3 accountCredential:(id)arg4 callbackURLString:(id)arg5 completion:(CDUnknownBlockType)arg6;

@end

