//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSOperationQueue, NSString, TFSDatabaseConnection, TFSDatabaseStateQueue, TFSDatabaseUIApplicationLink;
@protocol TFSDatabaseExpiringActivityManager;

@interface TFSDatabaseOnDisk
{
    NSString *_path;
    NSOperationQueue *_writeOperationQueue;
    TFSDatabaseUIApplicationLink *_applicationLink;
    id <TFSDatabaseExpiringActivityManager> _expiringActivityManager;
    long long _diskSyncMode;
    TFSDatabaseConnection *_writeConnection;
}

+ (id)_tfs_underlyingWriteQueue;
+ (id)statistics;
- (void).cxx_destruct;
@property(retain, nonatomic) TFSDatabaseConnection *writeConnection; // @synthesize writeConnection=_writeConnection;
@property(nonatomic) long long diskSyncMode; // @synthesize diskSyncMode=_diskSyncMode;
@property(retain, nonatomic) id <TFSDatabaseExpiringActivityManager> expiringActivityManager; // @synthesize expiringActivityManager=_expiringActivityManager;
@property(retain, nonatomic) TFSDatabaseUIApplicationLink *applicationLink; // @synthesize applicationLink=_applicationLink;
@property(readonly, nonatomic) NSOperationQueue *writeOperationQueue; // @synthesize writeOperationQueue=_writeOperationQueue;
@property(readonly, copy, nonatomic) NSString *path; // @synthesize path=_path;
- (id)_tfs_enqueuedOperationWithState:(id)arg1 transactionBlock:(CDUnknownBlockType)arg2;
- (void)close;
- (void)flush;
- (void)enqueueWriteTransactionWithLog:(id)arg1 block:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)performTransactionWithLog:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)_tfs_applicationWillResignActive:(id)arg1;
- (void)_tfs_applicationDidBecomeActive:(id)arg1;
- (void)dealloc;
- (id)initWithPath:(id)arg1 applicationLink:(id)arg2 diskSyncMode:(long long)arg3;

// Remaining properties
@property(readonly, nonatomic) TFSDatabaseStateQueue *stateQueue; // @dynamic stateQueue;

@end

