//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface TFSFeatureSwitchesMainThreadCache : NSObject
{
    NSMutableDictionary *_keyToValue;
    NSMutableDictionary *_keyToIsInExperiment;
    NSMutableDictionary *_keyToHasNonDefaultValue;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableDictionary *keyToHasNonDefaultValue; // @synthesize keyToHasNonDefaultValue=_keyToHasNonDefaultValue;
@property(readonly, nonatomic) NSMutableDictionary *keyToIsInExperiment; // @synthesize keyToIsInExperiment=_keyToIsInExperiment;
@property(readonly, nonatomic) NSMutableDictionary *keyToValue; // @synthesize keyToValue=_keyToValue;
- (void)removeValuesForKeys:(id)arg1;
- (void)reset;
- (_Bool)tfs_boolValueForKey:(id)arg1 inDictionary:(id)arg2 fetchIfNotCachedWith:(CDUnknownBlockType)arg3;
- (_Bool)hasNonDefaultValueForKey:(id)arg1 fetchIfNotCachedWith:(CDUnknownBlockType)arg2;
- (_Bool)isInExperimentForKey:(id)arg1 fetchIfNotCachedWith:(CDUnknownBlockType)arg2;
- (id)valueForKey:(id)arg1 fetchIfNotCachedWith:(CDUnknownBlockType)arg2;
- (id)init;

@end

