//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface TFSFeatureSwitchesBucket : NSObject
{
    NSString *_name;
    long long _offset;
}

+ (id)bucketWithDictionary:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long offset; // @synthesize offset=_offset;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (id)initWithName:(id)arg1 offset:(long long)arg2;

@end

