//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TFSLocalized : NSObject
{
}

+ (id)localizedString:(id)arg1 fromFile:(id)arg2 inBundle:(id)arg3;
+ (id)localizedString:(id)arg1 fromFile:(id)arg2;
+ (id)localizedString:(id)arg1;
+ (id)retrieveLocalizationBundleForLanguageCode:(id)arg1;
+ (id)commaSeparatedNameList:(id)arg1;
- (void).cxx_destruct;
- (id)init;

@end

