//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface TFSSpanContext : NSObject
{
    MISSING_TYPE *spanQueue;
    MISSING_TYPE *span;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) _Bool isComplete;
@property(nonatomic, readonly) _Bool isCancelled;
@property(nonatomic, readonly) NSString *debugDescription;

@end

