//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface TFSTwitterAPISavedSearchesCreateCommand
{
    NSString *_query;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *query; // @synthesize query=_query;
- (id)request;
- (id)initWithContext:(id)arg1 accountID:(id)arg2 query:(id)arg3 source:(unsigned long long)arg4 responseModelBuilder:(id)arg5 completionBlock:(CDUnknownBlockType)arg6;

@end

