//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TFSTwitterCoreAPIConfiguration : NSObject
{
    _Bool _isBirdwatchConsumptionEnabled;
    _Bool _isBirdwatchPivotEnabled;
    _Bool _isSafetyModeEnabled;
    _Bool _isSuperFollowsTweetCreationEnabled;
    _Bool _isDontMentionMeAPIEnabled;
    _Bool _isHasSpacesCallEnabled;
    _Bool _isViewCountsAPIEnabled;
    _Bool _isArticleRestAPIEnabled;
    _Bool _isArticlePreviewEnabled;
    _Bool _isNarrowcastPostCreationEnabled;
    long long _scribeAPISampleSize;
    long long _scribeAPIErrorSampleSize;
}

@property(readonly, nonatomic) _Bool isNarrowcastPostCreationEnabled; // @synthesize isNarrowcastPostCreationEnabled=_isNarrowcastPostCreationEnabled;
@property(readonly, nonatomic) _Bool isArticlePreviewEnabled; // @synthesize isArticlePreviewEnabled=_isArticlePreviewEnabled;
@property(readonly, nonatomic) _Bool isArticleRestAPIEnabled; // @synthesize isArticleRestAPIEnabled=_isArticleRestAPIEnabled;
@property(readonly, nonatomic) _Bool isViewCountsAPIEnabled; // @synthesize isViewCountsAPIEnabled=_isViewCountsAPIEnabled;
@property(readonly, nonatomic) _Bool isHasSpacesCallEnabled; // @synthesize isHasSpacesCallEnabled=_isHasSpacesCallEnabled;
@property(readonly, nonatomic) _Bool isDontMentionMeAPIEnabled; // @synthesize isDontMentionMeAPIEnabled=_isDontMentionMeAPIEnabled;
@property(readonly, nonatomic) _Bool isSuperFollowsTweetCreationEnabled; // @synthesize isSuperFollowsTweetCreationEnabled=_isSuperFollowsTweetCreationEnabled;
@property(readonly, nonatomic) _Bool isSafetyModeEnabled; // @synthesize isSafetyModeEnabled=_isSafetyModeEnabled;
@property(readonly, nonatomic) _Bool isBirdwatchPivotEnabled; // @synthesize isBirdwatchPivotEnabled=_isBirdwatchPivotEnabled;
@property(readonly, nonatomic) _Bool isBirdwatchConsumptionEnabled; // @synthesize isBirdwatchConsumptionEnabled=_isBirdwatchConsumptionEnabled;
@property(readonly, nonatomic) long long scribeAPIErrorSampleSize; // @synthesize scribeAPIErrorSampleSize=_scribeAPIErrorSampleSize;
@property(readonly, nonatomic) long long scribeAPISampleSize; // @synthesize scribeAPISampleSize=_scribeAPISampleSize;
- (id)init;
- (id)initWithConfiguration:(id)arg1;

@end

