//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TFSTwitterAPIAccountDeactivateRequest
{
}

+ (unsigned long long)responseHydrationFlags;
- (long long)HTTPMethodValue;
- (id)initWithPassword:(id)arg1 requestTimespan:(unsigned long long)arg2 context:(id)arg3 responseModelBuilder:(id)arg4;

@end

