//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface TFSTwitterAPIUsersByRestIdsCommand
{
    MISSING_TYPE *userIDs;
}

- (void).cxx_destruct;
- (id)request;
- (id)initWithContext:(id)arg1 accountID:(id)arg2 userIDs:(id)arg3 source:(unsigned long long)arg4 responseModelBuilder:(id)arg5 responseProcessorBlock:(CDUnknownBlockType)arg6 completionBlock:(CDUnknownBlockType)arg7;

@end

