//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSDate, NSString;

@interface TFSTwitterTypeaheadServiceRequest : NSObject
{
    MISSING_TYPE *query;
    MISSING_TYPE *resultType;
    MISSING_TYPE *sourceType;
    MISSING_TYPE *prefetch;
    MISSING_TYPE *mediaTaggingInPrefetch;
    MISSING_TYPE *lastCacheAge;
    MISSING_TYPE *geoRequestFilter;
    MISSING_TYPE *contextText;
    MISSING_TYPE *topicType;
    MISSING_TYPE *communityId;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithQuery:(id)arg1 resultType:(long long)arg2 sourceType:(unsigned long long)arg3 prefetch:(_Bool)arg4 mediaTaggingInPrefetch:(_Bool)arg5 lastCacheAge:(id)arg6 geoRequestFilter:(_Bool)arg7 contextText:(id)arg8 topicType:(unsigned long long)arg9 communityId:(id)arg10;
@property(nonatomic, readonly) NSString *communityId;
@property(nonatomic, readonly) unsigned long long topicType; // @synthesize topicType;
@property(nonatomic, readonly) NSString *contextText;
@property(nonatomic, readonly) _Bool geoRequestFilter; // @synthesize geoRequestFilter;
@property(nonatomic, readonly) NSDate *lastCacheAge;
@property(nonatomic, readonly) _Bool mediaTaggingInPrefetch; // @synthesize mediaTaggingInPrefetch;
@property(nonatomic, readonly) _Bool prefetch; // @synthesize prefetch;
@property(nonatomic, readonly) unsigned long long sourceType; // @synthesize sourceType;
@property(nonatomic, readonly) long long resultType; // @synthesize resultType;
@property(nonatomic, readonly) NSString *query;

@end

