//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TFSTwitterAPIMobileSettingsLogoutRequest
{
}

+ (unsigned long long)responseHydrationFlags;
+ (long long)HTTPMethodValue;
+ (id)endpointPath;
- (id)initWithEndpointPath:(id)arg1 parameters:(id)arg2 multipartFormData:(id)arg3 bodyData:(id)arg4 bodyFilePath:(id)arg5 headerFields:(id)arg6 context:(id)arg7 responseModelBuilder:(id)arg8 emptyResponseDataExpected:(_Bool)arg9;
- (id)initWithAppID:(long long)arg1 userID:(long long)arg2 base64PushToken:(id)arg3 udid:(id)arg4 environment:(long long)arg5 context:(id)arg6 responseModelBuilder:(id)arg7;

@end

