//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString, TFSTwitterEntitySet;

@interface TFSTwitterTranslation : NSObject
{
    MISSING_TYPE *translation;
    MISSING_TYPE *entities;
    MISSING_TYPE *translationSource;
    MISSING_TYPE *localizedSourceLanguage;
    MISSING_TYPE *sourceLanguage;
    MISSING_TYPE *destinationLanguage;
    MISSING_TYPE *translationState;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithTranslation:(id)arg1 entities:(id)arg2 translationSource:(id)arg3 localizedSourceLanguage:(id)arg4 sourceLanguage:(id)arg5 destinationLanguage:(id)arg6 translationState:(id)arg7;
@property(nonatomic, readonly) NSString *translationState;
@property(nonatomic, readonly) NSString *destinationLanguage;
@property(nonatomic, readonly) NSString *sourceLanguage;
@property(nonatomic, readonly) NSString *localizedSourceLanguage;
@property(nonatomic, readonly) NSString *translationSource;
@property(nonatomic, readonly) TFSTwitterEntitySet *entities; // @synthesize entities;
@property(nonatomic, readonly) NSString *translation;

@end

