//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TFSTwitterAPIAmplifyMarketplaceDefaultsPostRequest
{
}

+ (unsigned long long)responseHydrationFlags;
+ (id)endpointPath;
+ (long long)HTTPMethodValue;
- (id)initWithMonitize:(_Bool)arg1 videoCategories:(id)arg2 excludedAdvertisers:(id)arg3 excludedMonetizationCategories:(id)arg4 excludedAdsCategories:(id)arg5 context:(id)arg6 responseModelBuilder:(id)arg7;
- (id)initWithEndpointPath:(id)arg1 parameters:(id)arg2 multipartFormData:(id)arg3 bodyData:(id)arg4 bodyFilePath:(id)arg5 headerFields:(id)arg6 context:(id)arg7 responseModelBuilder:(id)arg8 emptyResponseDataExpected:(_Bool)arg9;

@end

