//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface TFSTwitterServiceLogger : NSObject
{
    NSString *_channel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *channel; // @synthesize channel=_channel;
- (void)logWithLevel:(long long)arg1 file:(id)arg2 function:(id)arg3 line:(int)arg4 contextObject:(id)arg5 format:(id)arg6;
- (_Bool)canLogWithLevel:(long long)arg1 contextObject:(id)arg2;
- (id)initWithChannel:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

