//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface TFSTwitterDynamicVideoPassthrough : NSObject
{
    NSNumber *_statusId;
    NSString *_passthroughString;
    NSString *_impressionId;
    NSString *_liveEventId;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *liveEventId; // @synthesize liveEventId=_liveEventId;
@property(readonly, copy, nonatomic) NSString *impressionId; // @synthesize impressionId=_impressionId;
@property(readonly, copy, nonatomic) NSString *passthroughString; // @synthesize passthroughString=_passthroughString;
@property(readonly, nonatomic) NSNumber *statusId; // @synthesize statusId=_statusId;
- (id)initWithJSONDictionary:(id)arg1;

@end

