//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSSet, NSString, NSURLCache;
@protocol OS_dispatch_queue, TFSFeatureSwitchProvider, TFSTwitterAPIURLBaseProvider;

@interface TFSTwitterAPIConfigurationImpl : NSObject
{
    NSDictionary *_optionalStatusParametersDictionary;
    NSDictionary *_optionalUserParametersDictionary;
    NSArray *_additionalContentDecoders;
    NSArray *_additionalContentEncoders;
    id <TFSFeatureSwitchProvider> _featureSwitchProvider;
    NSObject<OS_dispatch_queue> *_urlCacheQueue;
    NSObject<OS_dispatch_queue> *_optionalEndpointAllowListAccessQueue;
    NSString *_cardsPlatformIdentifier;
    id <TFSTwitterAPIURLBaseProvider> _URLBaseProvider;
    NSURLCache *_URLCache;
    NSSet *_optionalEndpointAllowList;
}

+ (void)_tfs_mergeCommaSeparatedEntriesInDictionariesWithKey:(id)arg1 sourceDictionary:(id)arg2 destinationDictionary:(id)arg3;
+ (void)_tfs_mergeEntriesInDictionariesWithKey:(id)arg1 sourceDictionary:(id)arg2 destinationDictionary:(id)arg3;
+ (void)_tfs_mergeEntriesInDictionary:(id)arg1 name:(id)arg2 toDictionary:(id)arg3;
+ (id)mergedCommaSeparatedParameters:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) id <TFSFeatureSwitchProvider> featureSwitchProvider; // @synthesize featureSwitchProvider=_featureSwitchProvider;
@property(readonly, nonatomic) id <TFSTwitterAPIURLBaseProvider> URLBaseProvider; // @synthesize URLBaseProvider=_URLBaseProvider;
@property(readonly, copy, nonatomic) NSString *cardsPlatformIdentifier; // @synthesize cardsPlatformIdentifier=_cardsPlatformIdentifier;
- (id)configurationWithAdditionalStatusParameters:(id)arg1 userParameters:(id)arg2 featureSwitchProvider:(id)arg3;
- (id)additionalContentEncoders;
- (id)additionalContentDecoders;
- (id)momentsParametersDictionary;
- (id)cardsParametersDictionary;
- (id)userParametersDictionary;
- (id)statusParametersDictionary;
@property(readonly, copy, nonatomic) NSSet *optionalEndpointAllowList; // @synthesize optionalEndpointAllowList=_optionalEndpointAllowList;
@property(readonly, nonatomic) NSURLCache *URLCache; // @synthesize URLCache=_URLCache;
- (id)initWithCardsPlatformIdentifier:(id)arg1 URLBaseProvider:(id)arg2 featureSwitchProvider:(id)arg3 URLCacheProvider:(CDUnknownBlockType)arg4 optionalEndpointAllowList:(id)arg5 optionalStatusParametersDictionary:(id)arg6 optionalUserParametersDictionary:(id)arg7 additionalContentDecoders:(id)arg8 additionalContentEncoders:(id)arg9;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

