//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray;

@interface TFSTwitterBirdwatchNoteRatingUserResponseAnswerEntryInput : NSObject
{
    MISSING_TYPE *key;
    MISSING_TYPE *value;
}

- (void).cxx_destruct;
- (id)init;
- (void)encodeWith:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic, readonly) long long hash;
- (id)initWithKey:(long long)arg1 value:(id)arg2;
@property(nonatomic, readonly) NSArray *value;
@property(nonatomic, readonly) long long key; // @synthesize key;

@end

