//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TFSTwitterAPIEmailNotificationSettingsUpdateRequest
{
}

+ (unsigned long long)responseHydrationFlags;
+ (long long)HTTPMethodValue;
+ (id)_tfs_bodyDataFromString:(id)arg1;
+ (id)_tfs_bodyDataFromBool:(_Bool)arg1;
- (id)initWithUserID:(long long)arg1 type:(id)arg2 boolValue:(_Bool)arg3 stringValue:(id)arg4 context:(id)arg5 responseModelBuilder:(id)arg6;

@end

