//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TFSTwitterAPIUploadCommand
{
    CDUnknownBlockType _uploadProgressBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType uploadProgressBlock; // @synthesize uploadProgressBlock=_uploadProgressBlock;
- (void)APIRequest:(id)arg1 requestOperation:(id)arg2 didUpdateUploadProgress:(float)arg3;
- (id)initWithAccountID:(id)arg1 context:(id)arg2 networkTransactionMetrics:(id)arg3 source:(unsigned long long)arg4 uploadProgressBlock:(CDUnknownBlockType)arg5 completionBlock:(CDUnknownBlockType)arg6;
- (id)initWithAccountID:(id)arg1 context:(id)arg2 authContext:(id)arg3 networkTransactionMetrics:(id)arg4 source:(unsigned long long)arg5 completionBlock:(CDUnknownBlockType)arg6;

@end

