//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, TFSTwitterLimitedActionPrompt;

@interface TFSTwitterLimitedAction : NSObject
{
    MISSING_TYPE *actionType;
    MISSING_TYPE *type;
    MISSING_TYPE *prompt;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithLegacyValue:(id)arg1;
@property(nonatomic, readonly) TFSTwitterLimitedActionPrompt *prompt; // @synthesize prompt;
@property(nonatomic, readonly) unsigned long long type; // @synthesize type;

@end

