//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface TFSTwitterAPIMediaSubtitlesDeleteCommand
{
    NSString *_mediaID;
    NSString *_mediaCategory;
    NSString *_subtitlesLanguageCode;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *subtitlesLanguageCode; // @synthesize subtitlesLanguageCode=_subtitlesLanguageCode;
@property(retain, nonatomic) NSString *mediaCategory; // @synthesize mediaCategory=_mediaCategory;
@property(retain, nonatomic) NSString *mediaID; // @synthesize mediaID=_mediaID;
- (id)request;
- (id)initWithContext:(id)arg1 accountID:(id)arg2 mediaID:(id)arg3 mediaCategory:(id)arg4 subtitlesLanguageCode:(id)arg5 source:(unsigned long long)arg6 completionBlock:(CDUnknownBlockType)arg7;
- (id)initWithAccountID:(id)arg1 context:(id)arg2 authContext:(id)arg3 networkTransactionMetrics:(id)arg4 source:(unsigned long long)arg5 completionBlock:(CDUnknownBlockType)arg6;

@end

