//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class TFSTwitterRichTextTag;

@interface TFSTwitterDisplayTextRichTextRange
{
}

- (id)initWithCoder:(id)arg1;
@property(nonatomic, readonly) long long rangeFlavor;
- (id)initWithRichText:(id)arg1;
@property(nonatomic, readonly) TFSTwitterRichTextTag *richTextTag;

@end

