//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TFSTwitterAPIAccountUpdateProfileBannerRequest
{
}

+ (unsigned long long)responseHydrationFlags;
+ (id)endpointPath;
+ (_Bool)isMultipartFormPostRequest;
+ (long long)HTTPMethodValue;
- (id)initWithBannerData:(id)arg1 bannerFileName:(id)arg2 size:(struct CGSize)arg3 leftOffset:(double)arg4 topOffset:(double)arg5 originalMediaHash:(id)arg6 context:(id)arg7 responseModelBuilder:(id)arg8;
- (id)initWithEndpointPath:(id)arg1 parameters:(id)arg2 multipartFormData:(id)arg3 bodyData:(id)arg4 bodyFilePath:(id)arg5 headerFields:(id)arg6 context:(id)arg7 responseModelBuilder:(id)arg8 emptyResponseDataExpected:(_Bool)arg9;

@end

