//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, TFSURTRichText;

@interface TFSTwitterBadgeViolation : NSObject
{
    NSString *_title;
    TFSURTRichText *_descriptionRichText;
    NSString *_descriptionURL;
    unsigned long long _category;
    unsigned long long _status;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(nonatomic) unsigned long long category; // @synthesize category=_category;
@property(readonly, copy, nonatomic) NSString *descriptionURL; // @synthesize descriptionURL=_descriptionURL;
@property(retain, nonatomic) TFSURTRichText *descriptionRichText; // @synthesize descriptionRichText=_descriptionRichText;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (id)initWithTitle:(id)arg1 descriptionRichText:(id)arg2 descriptionURL:(id)arg3 category:(unsigned long long)arg4 status:(unsigned long long)arg5;

@end

