//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface TFSURTUrlEndpointOptions : NSObject
{
    MISSING_TYPE *requestParams;
    MISSING_TYPE *title;
    MISSING_TYPE *cacheID;
    MISSING_TYPE *subtitle;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithRequestParams:(id)arg1 title:(id)arg2 cacheID:(id)arg3 subtitle:(id)arg4;

@end

