//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSData, NSMutableArray, NSMutableData;

@interface TLPEventStream : NSObject
{
    NSData *_newline;
    NSData *_commentPrefix;
    NSData *_dataPrefix;
    NSData *_eventPrefix;
    NSMutableData *_partialBuffer;
    NSData *_eventBuffer;
    NSMutableArray *_events;
}

- (void).cxx_destruct;
- (_Bool)handleLine:(id)arg1 start:(unsigned long long)arg2 length:(unsigned long long)arg3;
- (id)popEvent;
- (_Bool)appendData:(id)arg1;
@property(readonly, nonatomic) unsigned long long eventCount;
- (id)init;

@end

