//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface TLSCrashReportLogger : NSObject
{
    MISSING_TYPE *logger;
}

+ (void)setSharedInstance:(id)arg1;
+ (id)sharedInstance;
+ (id)defaultLoggingChannel;
- (void).cxx_destruct;
- (id)init;
- (void)handleNonFatalEventWithNotification:(id)arg1;

@end

