//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSDictionary, NSString;

@interface TLSLogMessageInfo : NSObject
{
    NSDictionary *_formattedMessages;
    NSString *_fileFunctionLineString;
    unsigned int _threadId;
    long long _level;
    NSString *_file;
    NSString *_function;
    long long _line;
    NSString *_channel;
    id _contextObject;
    NSDate *_timestamp;
    double _logLifespan;
    NSString *_threadName;
    NSString *_message;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(readonly, copy, nonatomic) NSString *threadName; // @synthesize threadName=_threadName;
@property(readonly, nonatomic) unsigned int threadId; // @synthesize threadId=_threadId;
@property(readonly, nonatomic) double logLifespan; // @synthesize logLifespan=_logLifespan;
@property(readonly, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, nonatomic) id contextObject; // @synthesize contextObject=_contextObject;
@property(readonly, copy, nonatomic) NSString *channel; // @synthesize channel=_channel;
@property(readonly, nonatomic) long long line; // @synthesize line=_line;
@property(readonly, copy, nonatomic) NSString *function; // @synthesize function=_function;
@property(readonly, copy, nonatomic) NSString *file; // @synthesize file=_file;
@property(readonly, nonatomic) long long level; // @synthesize level=_level;
- (id)composeFileFunctionLineString;
- (id)composeFormattedMessageWithOptions:(long long)arg1;
- (id)composeFormattedMessage;
- (id)init;
- (id)initWithLevel:(long long)arg1 file:(id)arg2 function:(id)arg3 line:(long long)arg4 channel:(id)arg5 timestamp:(id)arg6 logLifespan:(double)arg7 threadId:(unsigned int)arg8 threadName:(id)arg9 contextObject:(id)arg10 message:(id)arg11;

@end

