//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSString;
@protocol TNLRequestRetryPolicyProvider;

@interface TNUChainedHttpRequestRetryPolicyProvider : NSObject
{
    NSArray<TNLRequestRetryPolicyProvider> *_childProviders;
    id <TNLRequestRetryPolicyProvider> _selectedChildProvider;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id <TNLRequestRetryPolicyProvider> selectedChildProvider; // @synthesize selectedChildProvider=_selectedChildProvider;
@property(copy, nonatomic) NSArray<TNLRequestRetryPolicyProvider> *childProviders; // @synthesize childProviders=_childProviders;
- (void)tnl_requestOperation:(id)arg1 didStartRetryFromResponse:(id)arg2;
- (void)tnl_requestOperation:(id)arg1 willStartRetryFromResponse:(id)arg2 afterDelay:(double)arg3;
- (id)tnl_configurationOfRetryForRequestOperation:(id)arg1 withResponse:(id)arg2 priorConfiguration:(id)arg3;
- (double)tnl_delayBeforeRetryForRequestOperation:(id)arg1 withResponse:(id)arg2;
- (_Bool)tnl_shouldRetryRequestOperation:(id)arg1 withResponse:(id)arg2;
- (id)initWithChildProviders:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

