//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class TPXDecaySolver;
@protocol TPXDecayAnimation3DObserver;

@interface TPXDecayAnimator3D
{
    TPXDecaySolver *_decayX;
    TPXDecaySolver *_decayY;
    TPXDecaySolver *_decayZ;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) TPXDecaySolver *decayZ; // @synthesize decayZ=_decayZ;
@property(readonly, nonatomic) TPXDecaySolver *decayY; // @synthesize decayY=_decayY;
@property(readonly, nonatomic) TPXDecaySolver *decayX; // @synthesize decayX=_decayX;
- (void)notifyDecayZStabilized;
- (void)notifyDecayYStabilized;
- (void)notifyDecayXStabilized;
- (void)updateAnimation;
- (_Bool)animationShouldComplete;
@property(nonatomic) struct TPXPoint3D velocity;
@property(nonatomic) struct TPXPoint3D position;
- (id)init;

// Remaining properties
@property(nonatomic) __weak id <TPXDecayAnimation3DObserver> delegate; // @dynamic delegate;

@end

