//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@interface UIView (TFNPointerInteraction)
- (void)tfn_removePointerInteraction;
- (void)tfn_setupPointerInteractionsWithStyleProvider:(CDUnknownBlockType)arg1;
- (void)tfn_setupHoverPointerInteractionsWithTintMode:(long long)arg1;
- (void)tfn_setupRoundRectCursorPointerInteractionsWithMargin:(struct CGSize)arg1;
@end

