//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/XKotlinKotlinCoroutineContextElement-Protocol.h>

@class XKotlinKotlinCancellationException;
@protocol XKotlinKotlinSequence, XKotlinKotlinx_coroutines_coreChildHandle, XKotlinKotlinx_coroutines_coreChildJob, XKotlinKotlinx_coroutines_coreDisposableHandle, XKotlinKotlinx_coroutines_coreJob, XKotlinKotlinx_coroutines_coreSelectClause0;

@protocol XKotlinKotlinx_coroutines_coreJob <XKotlinKotlinCoroutineContextElement>
@property(nonatomic, readonly) id <XKotlinKotlinx_coroutines_coreJob> parent;
@property(nonatomic, readonly) id <XKotlinKotlinx_coroutines_coreSelectClause0> onJoin;
@property(nonatomic, readonly) _Bool isCompleted;
@property(nonatomic, readonly) _Bool isCancelled;
@property(nonatomic, readonly) _Bool isActive;
@property(nonatomic, readonly) id <XKotlinKotlinSequence> children;
- (_Bool)start_;
- (id <XKotlinKotlinx_coroutines_coreJob>)plusOther_:(id <XKotlinKotlinx_coroutines_coreJob>)arg1;
- (void)joinWithCompletionHandler:(void (^)(NSError *))arg1;
- (id <XKotlinKotlinx_coroutines_coreDisposableHandle>)invokeOnCompletionOnCancelling:(_Bool)arg1 invokeImmediately:(_Bool)arg2 handler:(void (^)(XKotlinKotlinThrowable *))arg3;
- (id <XKotlinKotlinx_coroutines_coreDisposableHandle>)invokeOnCompletionHandler:(void (^)(XKotlinKotlinThrowable *))arg1;
- (XKotlinKotlinCancellationException *)getCancellationException;
- (void)cancelCause:(XKotlinKotlinCancellationException *)arg1;
- (id <XKotlinKotlinx_coroutines_coreChildHandle>)attachChildChild:(id <XKotlinKotlinx_coroutines_coreChildJob>)arg1;
@end

