//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface XKotlinBase : NSObject
{
    struct BackRefFromAssociatedObject refHolder;
    _Bool permanent;
}

+ (id)createRetainedWrapper:(struct ObjHeader *)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)initialize;
+ (void)load;
- (unsigned long long)externalRCRef;
- (id)initWithExternalRCRef:(unsigned long long)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)XKotlin_releaseAsAssociatedObject;
- (oneway void)release;
- (_Bool)_tryRetain;
- (id)retain;
- (struct ObjHeader *)XKotlin_toKotlin:(struct ObjHeader **)arg1;

@end

