//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIButton.h>

@interface _TtC14T1TwitterSwiftP33_62AC29E4F88B62C8A334BAA89C65783629RoundedModalSheetCancelButton : UIButton
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic) _Bool highlighted;
- (_Bool)isHighlighted;

@end

