//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TAVControlBarItem.h>

@class MISSING_TYPE, UIView;

@interface _TtCC14T1TwitterSwift25VideoHeaderViewControlBarP33_10EA23A0F7840EFFF25C997951E28E4017FlexibleSpaceItem : TAVControlBarItem
{
    MISSING_TYPE *$__lazy_storage_$_spacer;
}

- (void).cxx_destruct;
- (id)initWithIdentifier:(id)arg1;
@property(nonatomic, readonly) UIView *view;

@end

