//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC14T1TwitterSwiftP33_95F21C00624F16120340BD95D99F151833T1UnifiedCardPlayableEventHandler : NSObject
{
    MISSING_TYPE *context;
    MISSING_TYPE *account;
    MISSING_TYPE *status;
}

- (void).cxx_destruct;
- (id)init;
- (void)handlePlayableEvent:(id)arg1 presentingViewController:(id)arg2;

@end

