//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNViewController.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC14T1TwitterSwift45ImmersiveBroadcastChatContainerViewController : TFNViewController
{
    MISSING_TYPE *hostViewController;
    MISSING_TYPE *tapGesture;
    MISSING_TYPE *panGesture;
    MISSING_TYPE *panTranslation;
    MISSING_TYPE *panStartAnchorPoint;
    MISSING_TYPE *stickToTop;
    MISSING_TYPE *delegate;
    MISSING_TYPE *isFullscreenEnabled;
    MISSING_TYPE *bottomInset;
    MISSING_TYPE *midPoint;
    MISSING_TYPE *opacity;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)handlePan:(id)arg1;
- (void)handleTap:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;

@end

