//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC14T1TwitterSwift19SurveyCardViewModel : NSObject
{
    MISSING_TYPE *survey;
    MISSING_TYPE *cardContext;
    MISSING_TYPE *fullScreen;
    MISSING_TYPE *completedInFullScreen;
    MISSING_TYPE *surveyCardView;
    MISSING_TYPE *delegate;
    MISSING_TYPE *$__lazy_storage_$_numberOfPages;
    MISSING_TYPE *$__lazy_storage_$_surveyPages;
    MISSING_TYPE *$__lazy_storage_$_response;
    MISSING_TYPE *$__lazy_storage_$_cardPersistedStateManager;
    MISSING_TYPE *$__lazy_storage_$_didCompleteSurvey;
}

- (void).cxx_destruct;
- (id)init;

@end

