//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNComposableViewLayoutState.h>

@interface _TtC14T1TwitterSwiftP33_4CBA8A5E93693E6BF28A7C06DE1AF80024GrokFollowupsLayoutState : TFNComposableViewLayoutState
{
}

- (id)init;

@end

