//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC14T1TwitterSwift39URTTimelineListViewModelTableRowAdapter : NSObject
{
    MISSING_TYPE *accountID;
    MISSING_TYPE *featureSwitches;
    MISSING_TYPE *impressionLogger;
    MISSING_TYPE *scribe;
    MISSING_TYPE *homeVariantCoordinator;
    MISSING_TYPE *style;
    MISSING_TYPE *feedbackPresenter;
    MISSING_TYPE *listDetailsViewControllerFactory;
    MISSING_TYPE *imagePipeline;
    MISSING_TYPE *listFeatures;
    MISSING_TYPE *listMutationsManager;
    MISSING_TYPE *persistentModelObservable;
    MISSING_TYPE *delegate;
    MISSING_TYPE *$__lazy_storage_$_cellStyle;
    MISSING_TYPE *$__lazy_storage_$_stringsProvider;
    MISSING_TYPE *$__lazy_storage_$_userBadger;
}

- (void).cxx_destruct;
- (id)init;
- (id)broadcaster:(id)arg1 focalViewForCell:(id)arg2;

@end

