//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC14T1TwitterSwift24T1ProfileModulesFeatures : NSObject
{
    MISSING_TYPE *featureSwitches;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithFeatureSwitches:(id)arg1;
@property(nonatomic, readonly) _Bool jobsModuleEnabled;
@property(nonatomic, readonly) _Bool profileAboutModuleSharingEnabled;
@property(nonatomic, readonly) long long offboardingDisclaimerVariant;
@property(nonatomic, readonly) _Bool noSpotlightModuleEnabled;
@property(nonatomic, readonly) _Bool spotlightConfigurationPageEnabled;
@property(nonatomic, readonly) _Bool linkModuleEnabled;
@property(nonatomic, readonly) _Bool professionalProfileModuleSettingsGoogleMapsEnabled;
@property(nonatomic, readonly) _Bool mobileAppSpotlightIOSOnlyEnabled;
@property(nonatomic, readonly) _Bool mobileAppModuleEnabled;
@property(nonatomic, readonly) _Bool createCommunitiesModuleEnabled;
@property(nonatomic, readonly) long long createShopModuleStepRetryCount;
@property(nonatomic, readonly) _Bool createShopModuleEnabled;
@property(nonatomic, readonly) _Bool editModuleEnabled;
@property(nonatomic, readonly) _Bool shopModuleShopV2IDEnabled;
@property(nonatomic, readonly) _Bool shopModuleButtonEnabled;
@property(nonatomic, readonly) _Bool shopModuleEnabled;
@property(nonatomic, readonly) _Bool aboutModuleDesignV2Enabled;
@property(nonatomic, readonly) _Bool aboutModuleEnabled;

@end

