//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "_$s20TwitterCommunitiesUI0B22CarouselViewControllerCN.h"

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC14T1TwitterSwift35T1CommunitiesCarouselViewController : _$s20TwitterCommunitiesUI0B22CarouselViewControllerCN
{
    MISSING_TYPE *account;
    MISSING_TYPE *presentedURTViewController;
}

- (void).cxx_destruct;
- (void)didSelectShowMore;

@end

