//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNItemsDataViewController.h>

@class MISSING_TYPE;

@interface _TtC14T1TwitterSwift25LandingPageViewController : TFNItemsDataViewController
{
    MISSING_TYPE *viewModel;
    MISSING_TYPE *customHeaderImageViewBottomAnchorConstant;
    MISSING_TYPE *$__lazy_storage_$_headerImageView;
}

- (void).cxx_destruct;
- (id)initWithCollectionViewLayout:(id)arg1;
- (void)closeTapped;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)willDisplayCell:(id)arg1 forItem:(id)arg2 atIndexPath:(id)arg3;
- (void)update:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, readonly) unsigned long long tfn_supportedInterfaceOrientations;
- (id)scribeImpressionParameters;
- (id)scribePage;
- (id)scribe;

@end

