//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC14T1TwitterSwift31PCFAccountNavigationCoordinator : NSObject
{
    MISSING_TYPE *rootViewController;
    MISSING_TYPE *account;
    MISSING_TYPE *controllerFactory;
    MISSING_TYPE *scribePage;
    MISSING_TYPE *scribeContext;
    MISSING_TYPE *hasParodyProfileLabelEnabled;
    MISSING_TYPE *parodyCommentaryFanLabel;
    MISSING_TYPE *isEditProfileEnabled;
    MISSING_TYPE *profileLabelsLearnMoreURL;
    MISSING_TYPE *currentlyPresentedViewController;
}

- (void).cxx_destruct;
- (id)init;

@end

