//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC14T1TwitterSwift24PageHeaderViewController
{
    MISSING_TYPE *adapter;
    MISSING_TYPE *scribeContext;
    MISSING_TYPE *backButtonUpdater;
}

- (void).cxx_destruct;
- (id)initWithHeaderViewConstructor:(CDUnknownBlockType)arg1 scribe:(id)arg2;
- (id)initWithHeaderViewClass:(Class)arg1 scribe:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)bannerAccessibilityLabelForResizableHeaderView:(id)arg1;
- (void)resizableHeaderView:(id)arg1 didTapShareHeaderButton:(id)arg2;
- (void)resizableHeaderViewDidTapBackButton:(id)arg1;
- (id)scribeSection;
- (id)scribePage;

@end

