//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFSConcurrentOperation.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC14T1TwitterSwift38CheckUploadContactsPermissionOperation : TFSConcurrentOperation
{
    MISSING_TYPE *account;
    MISSING_TYPE *settings;
}

- (void).cxx_destruct;
- (id)init;
- (void)run;
- (id)initWithAccount:(id)arg1 settings:(id)arg2;

@end

