//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC14T1TwitterSwift31ImmersiveBroadcastChatInputView : UIView
{
    MISSING_TYPE *viewModel;
    MISSING_TYPE *tapGesture;
    MISSING_TYPE *textInput;
    MISSING_TYPE *placeholderTransitioningView;
    MISSING_TYPE *textInputPlaceholderTransition;
    MISSING_TYPE *tapAction;
    MISSING_TYPE *isTextInputEnabled;
    MISSING_TYPE *keyboardUpdateHandler;
}

- (void).cxx_destruct;
- (void)handleTap;
- (void)keyboardWillHideHandlerWithNotification:(id)arg1;
- (void)keyboardWillShowHandlerWithNotification:(id)arg1;
- (void)didMoveToWindow;
- (_Bool)resignFirstResponder;
- (_Bool)becomeFirstResponder;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;

@end

