//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNItemsDataViewController.h>

@class MISSING_TYPE;

@interface _TtC14T1TwitterSwift33BrandedLikePreviewsViewController : TFNItemsDataViewController
{
    MISSING_TYPE *animationParser;
    MISSING_TYPE *tweetProvider;
    MISSING_TYPE *featureSwitches;
    MISSING_TYPE *animation;
    MISSING_TYPE *$__lazy_storage_$_moreBarButtonItem;
    MISSING_TYPE *$__lazy_storage_$_documentPicker;
    MISSING_TYPE *$__lazy_storage_$_landingItem;
    MISSING_TYPE *$__lazy_storage_$_animationHeaderItem;
    MISSING_TYPE *$__lazy_storage_$_statusHeaderItem;
}

- (void).cxx_destruct;
- (id)initWithCollectionViewLayout:(id)arg1;
- (void)reduceMotionStatusDidChange;
- (void)update:(_Bool)arg1;
- (id)previewConfigurationForItem:(id)arg1 location:(struct CGPoint)arg2 inCell:(id)arg3 atIndexPath:(id)arg4;
- (void)didPressMoreButton;
- (void)dealloc;
- (void)viewDidLoad;
- (id)scribeSection;
- (id)scribePage;
- (long long)dashContentItemType;
- (void)documentPicker:(id)arg1 didPickDocumentsAtURLs:(id)arg2;
- (void)didTapInlineActionButton:(id)arg1;

@end

