//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterAppSPMMigration/TUICardViewLayoutState.h>

@interface _TtC14T1TwitterSwiftP33_48872C0712F915ECDF236EFFE06ED83233ExclusiveSpaceCardViewLayoutState : TUICardViewLayoutState
{
}

- (id)init;

@end

