//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNCollectionViewCell.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC14T1TwitterSwift44URTTimelinePagedCarouselItemFeedbackItemView : TFNCollectionViewCell
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *scribeContext;
    MISSING_TYPE *isRelevantButton;
    MISSING_TYPE *notRelevantButton;
    MISSING_TYPE *buttonStackView;
    MISSING_TYPE *tweetView;
}

- (void).cxx_destruct;
- (void)didTapShowLessButton:(id)arg1;
- (void)didTapShowMoreButton:(id)arg1;
- (void)accessibilityElementDidBecomeFocused:(id)arg1;
- (void)prepareForReuse;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

