//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNItemsDataViewController.h>

@class MISSING_TYPE;

@interface _TtC14T1TwitterSwift37PCFAccountLabelSettingsViewController : TFNItemsDataViewController
{
    MISSING_TYPE *account;
    MISSING_TYPE *scribeContext;
    MISSING_TYPE *isEditProfileEnabled;
    MISSING_TYPE *isParodyAccountProfileLabelEnabled;
    MISSING_TYPE *parodyLabelSettings;
    MISSING_TYPE *actionService;
    MISSING_TYPE *$__lazy_storage_$_descriptionItem;
    MISSING_TYPE *$__lazy_storage_$_enableParodyItem;
}

- (void).cxx_destruct;
- (id)initWithCollectionViewLayout:(id)arg1;
- (void)didTapBack;
- (void)update:(_Bool)arg1;
- (void)pickerViewController:(id)arg1 didPickValue:(id)arg2 inSectionAtIndex:(unsigned long long)arg3 willConfirm:(_Bool)arg4 willDismiss:(_Bool)arg5;
- (id)initiallyPickedValueForPicker:(id)arg1;
- (id)valuesForPicker:(id)arg1;
- (id)scribeComponent;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;

@end

