//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "_$s10TFNUISwift28BridgingItemsDataViewAdapterCN.h"

@interface _TtC14T1TwitterSwift34T1URTTimelineCursorTableRowAdapter : _$s10TFNUISwift28BridgingItemsDataViewAdapterCN
{
}

- (id)initWithScribe:(id)arg1 scribeContext:(id)arg2 featureSwitches:(id)arg3;

@end

