//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14T1TwitterSwift15DraftJSRenderer : _TtCs12_SwiftObject
{
    MISSING_TYPE *orderedListCounter;
    MISSING_TYPE *prevBlockType;
    MISSING_TYPE *renderError;
    MISSING_TYPE *draftJSON;
    MISSING_TYPE *config;
}

@end

