//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE, NSArray, NSString;

@interface _TtC14T1TwitterSwift9TrendView : UIView
{
    MISSING_TYPE *cardEventHandler;
    MISSING_TYPE *feedbackHandler;
    MISSING_TYPE *navigationHelper;
    MISSING_TYPE *imagePipeline;
    MISSING_TYPE *contentStackView;
    MISSING_TYPE *outerColumnStackView;
    MISSING_TYPE *quotePostStackView;
    MISSING_TYPE *domainContextView;
    MISSING_TYPE *titleView;
    MISSING_TYPE *descriptionView;
    MISSING_TYPE *imageView;
    MISSING_TYPE *$__lazy_storage_$_cardView;
    MISSING_TYPE *$__lazy_storage_$_quotedStandardStatusView;
    MISSING_TYPE *socialProofView;
    MISSING_TYPE *promotedView;
    MISSING_TYPE *caretView;
    MISSING_TYPE *$__lazy_storage_$_caretCenterOnDomainContextConstraint;
    MISSING_TYPE *$__lazy_storage_$_caretCenterOnTitleConstraint;
    MISSING_TYPE *$__lazy_storage_$_caretTrailingConstraint;
    MISSING_TYPE *relatedTrendsView;
    MISSING_TYPE *trendAccessibility;
    MISSING_TYPE *socialContextContainerView;
    MISSING_TYPE *socialContextFacepile;
    MISSING_TYPE *socialContextLabel;
    MISSING_TYPE *MaximumNumberOfAvatars;
    MISSING_TYPE *viewModel;
}

- (void).cxx_destruct;
- (void)feedbackCaretTapped;
- (id)autoplayable;
- (void)voiceOverStatusChanged;
@property(nonatomic, copy) NSArray *accessibilityCustomActions;
@property(nonatomic, copy) NSString *accessibilityHint;
@property(nonatomic, copy) NSString *accessibilityLabel;
@property(nonatomic) _Bool accessibilityElementsHidden;
- (id)previewConfigurationForLocation:(struct CGPoint)arg1;
- (void)layoutMetricsDidChange:(id)arg1 to:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

