//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCV14T1TwitterSwift26ProfileAnalyticsUpsellView9ViewModel : _TtCs12_SwiftObject
{
    MISSING_TYPE *_metric;
    MISSING_TYPE *_isHidden;
    MISSING_TYPE *onUpdate;
    MISSING_TYPE *account;
    MISSING_TYPE *didLogImpression;
    MISSING_TYPE *$__lazy_storage_$_actionService;
}

@end

