//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterAppSPMMigration/TUICardViewLayoutState.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC14T1TwitterSwift25SurveyCardViewLayoutState : TUICardViewLayoutState
{
    MISSING_TYPE *actionButtonFrame;
    MISSING_TYPE *currentPageFrame;
    MISSING_TYPE *currentPage;
    MISSING_TYPE *currentPageLayout;
}

- (void).cxx_destruct;
- (id)init;
- (_Bool)isLayoutStateValidForCardContext:(id)arg1;

@end

