//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@protocol _TtP20TwitterNotifications20NotificationScribing_
- (void)scribeForCurrentAccountWithPage:(NSString *)arg1 section:(NSString *)arg2 component:(NSString *)arg3 element:(NSString *)arg4 action:(NSString *)arg5;
@end

