//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@protocol _TtP14T1TwitterSwift17T1VideoDownloader_
- (void)tappedDownload;
@end

