//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <WebKit/WKWebView.h>

@class UIView;

@interface CustomWKWebView : WKWebView
{
    _Bool _hideInputAccessoryView;
    UIView *_accessoryView;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool hideInputAccessoryView; // @synthesize hideInputAccessoryView=_hideInputAccessoryView;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
- (id)inputAccessoryView;
- (id)initWithFrame:(struct CGRect)arg1 configuration:(id)arg2;

@end

