//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/GADAdLoaderDelegate-Protocol.h>

@class GADAdLoader, GADNativeAd;

@protocol GADNativeAdLoaderDelegate <GADAdLoaderDelegate>
- (void)adLoader:(GADAdLoader *)arg1 didReceiveNativeAd:(GADNativeAd *)arg2;
@end

