//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSSet, NSString, NSURL, PTVAPIResponseErrorInfo, PTVBroadcast, PTVMergeParticipantUser, UIImage, UIView, UIViewController;

@protocol PTVTwitterCameraLiveDelegate <NSObject>
- (NSURL *)twitterCameraLiveCopyrightViolationLearnMoreURL;

@optional
- (long long)twitterCameraLiveClient;
- (void)twitterCameraLiveLogAction:(NSString *)arg1 element:(NSString *)arg2;
- (_Bool)twitterCameraLiveShouldUseModalSheetForUserProfile;
- (_Bool)twitterCameraLiveIsGuestBroadcastingCreationEnabled;
- (double)twitterCameraLiveGuestViewsTopMargin;
- (void)twitterCameraLiveDidDismissCopyrightViewController;
- (void)twitterCameraLiveDidObserveAuthErrorWithInfo:(PTVAPIResponseErrorInfo *)arg1;
- (void)twitterCameraLiveDidDetectCopyrightViolation;
- (UIViewController *)twitterCameraLiveViewControllerForProfileFollow:(NSString *)arg1;
- (void)twitterCameraLiveDeleteBroadcast:(PTVBroadcast *)arg1;
- (void)twitterCameraLiveDidStopBroadcast:(PTVBroadcast *)arg1;
- (void)twitterCameraLiveDidStartBroadcast:(PTVBroadcast *)arg1;
- (NSSet *)twitterCameraLiveBlockedTwitterIDs;
- (void)twitterCameraLiveDidUnblockUser:(PTVMergeParticipantUser *)arg1;
- (void)twitterCameraLiveDidBlockUser:(PTVMergeParticipantUser *)arg1;
- (void)twitterCameraLiveRetweetBroadcast:(PTVBroadcast *)arg1 withCompletion:(void (^)(_Bool, NSError *))arg2;
- (_Bool)twitterCameraLiveShouldSaveToCameraRoll;
- (_Bool)twitterCameraLiveCanRetweetBroadcast:(PTVBroadcast *)arg1;
- (void)twitterCameraLiveReportBroadcast:(PTVBroadcast *)arg1;
- (void)twitterCameraLiveShareURLOfBroadcast:(PTVBroadcast *)arg1 atTimecode:(double)arg2 initialTimecode:(double)arg3 fromRect:(struct CGRect)arg4 inView:(UIView *)arg5 withCompletion:(void (^)(_Bool, NSError *))arg6;
- (void)twitterCameraLiveComposeDirectMessageForBroadcast:(PTVBroadcast *)arg1 atTimecode:(double)arg2 initialTimecode:(double)arg3 fromRect:(struct CGRect)arg4 inView:(UIView *)arg5 withCompletion:(void (^)(_Bool, NSError *))arg6;
- (void)twitterCameraLiveComposeTweetForBroadcast:(PTVBroadcast *)arg1 atTimecode:(double)arg2 initialTimecode:(double)arg3 screenshot:(UIImage *)arg4 fromRect:(struct CGRect)arg5 inView:(UIView *)arg6 withCompletion:(void (^)(_Bool, NSError *))arg7;
- (_Bool)twitterCameraLiveCanShareBroadcast;
- (void)twitterCameraLiveBroadcastStatusChangedForBroadcast:(PTVBroadcast *)arg1 status:(long long)arg2;
- (void)twitterCameraLiveBroadcastCapabilityChanged:(long long)arg1;
@end

