//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface T1ActionServiceApplicationStateMonitor : NSObject
{
    MISSING_TYPE *sync;
}

- (void).cxx_destruct;
- (void)onApplicationDidEnterBackground:(id)arg1;
- (void)onApplicationDidBecomeActive:(id)arg1;
- (void)onApplicationWillEnterForeground:(id)arg1;
- (void)onApplicationWillResignActive:(id)arg1;
- (void)onApplicationDidFinishLaunching:(id)arg1;
- (void)configureWith:(id)arg1;
- (id)init;

@end

