//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class TFNBadgesImageView, TFNTwitterAccount, TUIAvatarImageView, TUIUserBadger, UILabel;

@interface T1AccountAvatarAndNameView : UIView
{
    TUIUserBadger *_userBadger;
    TUIAvatarImageView *_avatarImageView;
    TFNBadgesImageView *_verifiedOrProtectedBadge;
    UILabel *_fullNameLabel;
    UILabel *_usernameLabel;
    TFNTwitterAccount *_account;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(readonly, nonatomic) UILabel *usernameLabel; // @synthesize usernameLabel=_usernameLabel;
@property(readonly, nonatomic) UILabel *fullNameLabel; // @synthesize fullNameLabel=_fullNameLabel;
@property(readonly, nonatomic) TFNBadgesImageView *verifiedOrProtectedBadge; // @synthesize verifiedOrProtectedBadge=_verifiedOrProtectedBadge;
@property(readonly, nonatomic) TUIAvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)_accountUserDidUpdate:(id)arg1;
- (void)layoutSubviews;
- (void)_t1_updateSubviews;
- (id)userBadger;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

