//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNItemsDataViewController.h>

@class TFNTwitterAccount;

@interface T1AccountDeactivateSettingsViewController : TFNItemsDataViewController
{
    TFNTwitterAccount *_account;
    unsigned long long _timespan;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long timespan; // @synthesize timespan=_timespan;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void)_t1_presentDeactivationConfirmationAlertForSoftUser;
- (void)_t1_presentPasswordConfirmationController;
- (id)_t1_displayStringForTimespan;
- (void)_t1_updateForRegularUser;
- (void)_t1_updateForSoftUser;
- (void)update:(_Bool)arg1;
- (id)initWithCollectionViewLayout:(id)arg1;
- (id)init;
- (id)initWithAccount:(id)arg1;

@end

