//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSDictionary, NSString, TFNActionItem, TFNTwitterStatus, TUITwitterUserContext, UIViewController;
@protocol TFSTwitterCanonicalUser;

@protocol T1AccountActions <NSObject>
- (void)toggleMuteForUser:(id <TFSTwitterCanonicalUser>)arg1 showConfirmationIfNeeded:(_Bool)arg2 impressionID:(NSString *)arg3 isPromoted:(_Bool)arg4 isEarned:(_Bool)arg5 scribePage:(NSString *)arg6 scribeSection:(NSString *)arg7 scribeComponent:(NSString *)arg8 scribeParameters:(NSDictionary *)arg9 completion:(void (^)(NSError *))arg10;
- (TFNActionItem *)createFollowActionItemForUser:(id <TFSTwitterCanonicalUser>)arg1 userContext:(TUITwitterUserContext *)arg2 associatedStatus:(TFNTwitterStatus *)arg3 showConfirmation:(_Bool)arg4 fromViewController:(UIViewController *)arg5;
@end

