//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSString, TVPVideoContextCTAInfo, UIButton;
@protocol T1AmplifyCTADelegate;

@interface T1AmplifyCTA : UIView
{
    UIButton *_button;
    id <T1AmplifyCTADelegate> _delegate;
    TVPVideoContextCTAInfo *_currentCTAInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TVPVideoContextCTAInfo *currentCTAInfo; // @synthesize currentCTAInfo=_currentCTAInfo;
@property(nonatomic) __weak id <T1AmplifyCTADelegate> delegate; // @synthesize delegate=_delegate;
- (id)_t1_fullscreenOpenURLCTATextForAdVideo:(id)arg1;
- (void)_t1_updateCTAButtonWithCTAInfo:(id)arg1 isAd:(_Bool)arg2 adVideoContext:(id)arg3;
- (void)_t1_setUpLayout;
- (void)_ctaButtonDidTap;
@property(readonly, nonatomic) double preferredHeight;
@property(retain, nonatomic) NSString *title;
@property(readonly, nonatomic) UIButton *button; // @synthesize button=_button;
- (void)reset;
- (void)updateWithCTAInfo:(id)arg1 isAd:(_Bool)arg2 adVideoContext:(id)arg3;
- (void)updateWithPlaylistItem:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

