//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, NSURL, _TtC20TwitterNotifications33TFSTwitterPushNotificationPayload;

@interface T1AppLaunchOptionsInfo : NSObject
{
    _Bool _populated;
    _Bool _applicationHasStartedLaunching;
    _Bool _applicationHasCompletedLaunching;
    _Bool _composerWillBePresented;
    long long _appState;
    _Bool _isLaunching;
    _Bool _isLaunchingToPanelRoot;
    _Bool _isBackgroundLaunch;
    long long _entryPoint;
    NSString *_launchID;
    long long _launchDestinationHandlerActionType;
    long long _launchType;
    long long _launchPanelID;
    NSURL *_launchURL;
    _TtC20TwitterNotifications33TFSTwitterPushNotificationPayload *_deferredPushPayload;
    long long _deferredPushContext;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isBackgroundLaunch; // @synthesize isBackgroundLaunch=_isBackgroundLaunch;
@property(nonatomic) long long deferredPushContext; // @synthesize deferredPushContext=_deferredPushContext;
@property(retain, nonatomic) _TtC20TwitterNotifications33TFSTwitterPushNotificationPayload *deferredPushPayload; // @synthesize deferredPushPayload=_deferredPushPayload;
@property(retain, nonatomic) NSURL *launchURL; // @synthesize launchURL=_launchURL;
@property(nonatomic) long long launchPanelID; // @synthesize launchPanelID=_launchPanelID;
@property(nonatomic) _Bool isLaunchingToPanelRoot; // @synthesize isLaunchingToPanelRoot=_isLaunchingToPanelRoot;
@property(nonatomic) long long launchType; // @synthesize launchType=_launchType;
@property(nonatomic) long long launchDestinationHandlerActionType; // @synthesize launchDestinationHandlerActionType=_launchDestinationHandlerActionType;
@property(retain, nonatomic) NSString *launchID; // @synthesize launchID=_launchID;
@property(nonatomic) _Bool isLaunching; // @synthesize isLaunching=_isLaunching;
@property(nonatomic) long long entryPoint; // @synthesize entryPoint=_entryPoint;
@property(readonly, nonatomic) _Bool handledPushNotificationOrURLOnLaunch;
@property(readonly, nonatomic) _Bool isLaunchFromPush;
@property(nonatomic) long long appState;
- (_Bool)_t1_deviceIsMirroringScreen;
- (void)_t1_assertPopulated;
- (long long)_t1_launchDestinationHandlerActionTypeForURL:(id)arg1;
- (void)_t1_applicationDidLaunchWithTwitterSchemaURL:(id)arg1;
- (void)_t1_applicationDidLaunchWithDeepLinkUserActivity:(id)arg1;
- (void)_t1_applicationDidLaunchWithQuickActionMenuOptions:(id)arg1;
- (void)_t1_applicationDidLaunchWithRemoteNotificationUserInfo:(id)arg1;
- (void)_t1_applicationDidLaunchWithUserActivity:(id)arg1;
- (void)_t1_resetAppLaunchOptions;
- (void)_t1_logApplicationState;
- (void)_t1_computePanelID;
- (void)composerWillBePresentedOnLaunch;
- (void)onApplicationStartWithOptions:(id)arg1;
- (void)notifyAppLaunchCompleted;
- (void)notifyAppLaunchBegan;
- (void)onApplicationReceivedRemoteNotificationWithUserInfo:(id)arg1;
- (void)onApplicationContinueUserActivity:(id)arg1;
- (void)onDeferredSetupOnTwitterStart;
- (void)onApplicationWillEnterForegroundFromBackground;
- (void)onApplicationDidEnterBackground;
- (void)onApplicationDidBecomeActive;
- (void)onApplicationDidFinishLaunchingWithState:(long long)arg1;
- (id)init;

@end

