//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class TFNTwitterAccount, UIViewController;
@protocol T1AppNavigationProvider;

@protocol T1AppNavigationProviderFactory <NSObject>
@property(nonatomic, readonly) long long maximumVisiblePanelCount;
- (UIViewController<T1AppNavigationProvider> *)appNavigationProviderControllerForAccount:(TFNTwitterAccount *)arg1;
@end

