//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSString, T1AppShutdownConfiguration, T1UserGeneratedContentDeletionManager;
@protocol OS_dispatch_queue;

@interface T1AppShutdownManager : NSObject
{
    _Bool _shutdownApp;
    NSObject<OS_dispatch_queue> *_stateDispatchQueue;
    NSObject<OS_dispatch_queue> *_defaultsDispatchQueue;
    unsigned long long _stateChange;
    T1AppShutdownConfiguration *_configuration;
    NSString *_currentAppVersion;
    NSString *_lastAppVersion;
    CDUnknownBlockType _scribeProvider;
    T1UserGeneratedContentDeletionManager *_UGCDeletionManager;
}

- (void).cxx_destruct;
@property(retain, nonatomic) T1UserGeneratedContentDeletionManager *UGCDeletionManager; // @synthesize UGCDeletionManager=_UGCDeletionManager;
@property(copy, nonatomic) CDUnknownBlockType scribeProvider; // @synthesize scribeProvider=_scribeProvider;
@property(copy, nonatomic) NSString *lastAppVersion; // @synthesize lastAppVersion=_lastAppVersion;
@property(copy, nonatomic) NSString *currentAppVersion; // @synthesize currentAppVersion=_currentAppVersion;
@property(retain, nonatomic) T1AppShutdownConfiguration *configuration; // @synthesize configuration=_configuration;
@property(nonatomic) unsigned long long stateChange; // @synthesize stateChange=_stateChange;
@property(nonatomic) _Bool shutdownApp; // @synthesize shutdownApp=_shutdownApp;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *defaultsDispatchQueue; // @synthesize defaultsDispatchQueue=_defaultsDispatchQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *stateDispatchQueue; // @synthesize stateDispatchQueue=_stateDispatchQueue;
- (id)APIEndpointAllowListByAddingDefaultEndpoints:(id)arg1 toEndpointList:(id)arg2;
- (void)_t1_stateQueue_saveConfigurationInGroupUserDefaults:(id)arg1;
- (void)_t1_applicationWillTerminate;
- (void)_t1_applicationDidEnterBackground;
- (void)deleteUserGeneratedContent;
- (void)_t1_updateShutdownFeatureSwitchesInGroupUserDefaults;
- (void)_t1_deviceFeatureSwitchesDidUpdate;
- (void)_t1_stateQueue_resurrect;
- (void)_t1_stateQueue_update;
- (void)_t1_stateQueue_shutdown;
- (_Bool)_t1_stateQueue_pendingAppShutdownWithConfiguration:(id)arg1;
- (void)_t1_stateQueue_processShutdownStateChange;
- (void)_t1_stateQueue_processAppShutdown;
- (void)processAppShutdown;
@property(readonly, copy, nonatomic) NSArray *APIEndpointAllowList;
@property(readonly, nonatomic) unsigned long long shutdownStateChange;
@property(readonly, nonatomic) _Bool shouldShutdownApp;
- (id)scribe;
- (void)dealloc;
- (id)initWithScribeProvider:(CDUnknownBlockType)arg1 appState:(long long)arg2;
- (id)initWithScribeProvider:(CDUnknownBlockType)arg1;

@end

