//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@interface T1AppSplitHostView : UIView
{
    UIView *_dividerView;
    _Bool _hasDivider;
    _Bool _suppressLayout;
    UIView *_hostedView;
    UIView *_overlayView;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool suppressLayout; // @synthesize suppressLayout=_suppressLayout;
@property(nonatomic) _Bool hasDivider; // @synthesize hasDivider=_hasDivider;
@property(readonly, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(readonly, nonatomic) UIView *hostedView; // @synthesize hostedView=_hostedView;
- (_Bool)tfn_isLayoutSuppressed;
- (void)_t1_updateDivider;
- (void)_t1_layout;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 hostedView:(id)arg2 hasDivider:(_Bool)arg3;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

