//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterAppSPMMigration/TUICardViewLayoutState.h>

@interface T1AppCardDetailsViewLayoutState : TUICardViewLayoutState
{
    struct CGRect _titleFrame;
    struct CGRect _subtitleFrame;
    struct CGRect _ratingsFrame;
    struct CGRect _callToActionFrame;
    struct CGRect _descriptionHighlightFrame;
    struct CGRect _appCategoryLabelFrame;
}

@property(nonatomic) struct CGRect appCategoryLabelFrame; // @synthesize appCategoryLabelFrame=_appCategoryLabelFrame;
@property(nonatomic) struct CGRect descriptionHighlightFrame; // @synthesize descriptionHighlightFrame=_descriptionHighlightFrame;
@property(nonatomic) struct CGRect callToActionFrame; // @synthesize callToActionFrame=_callToActionFrame;
@property(nonatomic) struct CGRect ratingsFrame; // @synthesize ratingsFrame=_ratingsFrame;
@property(nonatomic) struct CGRect subtitleFrame; // @synthesize subtitleFrame=_subtitleFrame;
@property(nonatomic) struct CGRect titleFrame; // @synthesize titleFrame=_titleFrame;

@end

