//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSError, T1BroadcastContainerView, TAVPlayer, TAVVideoContext, TFSTwitterBroadcast;
@protocol TAVPlayback, TFCCardDataSource;

@protocol T1BroadcastContainerViewDelegate <NSObject>

@optional
- (void)broadcastContainerViewDidTapInitialPlayButton:(T1BroadcastContainerView *)arg1;
- (void)broadcastContainerView:(T1BroadcastContainerView *)arg1 didUpdateMuteState:(_Bool)arg2;
- (void)broadcastContainerView:(T1BroadcastContainerView *)arg1 didTapToPlay:(_Bool)arg2;
- (void)broadcastContainerView:(T1BroadcastContainerView *)arg1 didTapToExpandBroadcast:(TFSTwitterBroadcast *)arg2 cardDataSource:(id <TFCCardDataSource>)arg3;
- (void)broadcastContainerView:(T1BroadcastContainerView *)arg1 didEndAdPlaybackWithContext:(TAVVideoContext *)arg2;
- (void)broadcastContainerView:(T1BroadcastContainerView *)arg1 didStartAdPlaybackWithContext:(TAVVideoContext *)arg2;
- (void)broadcastContainerView:(T1BroadcastContainerView *)arg1 didSetPlayer:(TAVPlayer *)arg2;
- (void)broadcastContainerView:(T1BroadcastContainerView *)arg1 playbackDidFailWithError:(NSError *)arg2;
- (void)broadcastContainerView:(T1BroadcastContainerView *)arg1 didCompletePlayback:(id <TAVPlayback>)arg2;
- (void)broadcastContainerView:(T1BroadcastContainerView *)arg1 didStartPlayback:(id <TAVPlayback>)arg2;
@end

