//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, T1CardContainerView, TFNTwitterCardContext;

@interface T1CardItem : NSObject
{
    TFNTwitterCardContext *_cardContext;
    T1CardContainerView *_cardContainerView;
    NSString *_scribeComponent;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *scribeComponent; // @synthesize scribeComponent=_scribeComponent;
@property(retain, nonatomic) T1CardContainerView *cardContainerView; // @synthesize cardContainerView=_cardContainerView;
@property(retain, nonatomic) TFNTwitterCardContext *cardContext; // @synthesize cardContext=_cardContext;

@end

