//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface T1CameraCaptureCameraModeLetterboxParameters : NSObject
{
    double _aspectRatio;
    double _heightDifference;
}

@property(readonly, nonatomic) double heightDifference; // @synthesize heightDifference=_heightDifference;
@property(readonly, nonatomic) double aspectRatio; // @synthesize aspectRatio=_aspectRatio;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithAspectRatio:(double)arg1 heightDifference:(double)arg2;

@end

