//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface T1Canary : NSObject
{
    NSObject<OS_dispatch_queue> *_canaryQueue;
    _Bool _didResetCanary;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool didResetCanary; // @synthesize didResetCanary=_didResetCanary;
- (void)start;
- (void)_t1_resetCanaryIfNecessary;
- (void)_t1_setKeychainCanary;
- (id)init;

@end

