//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/UIScrollViewDelegate-Protocol.h>

@class T1ComposeRichTextView, UIView;

@protocol T1ComposeRichTextViewDelegate <UIScrollViewDelegate>

@optional
- (void)richTextViewDidLayoutSubviews:(T1ComposeRichTextView *)arg1;
- (void)richTextView:(T1ComposeRichTextView *)arg1 didTapMonetizationPromptInRect:(struct CGRect)arg2 ofView:(UIView *)arg3;
- (void)richTextViewDidTapPlaceText:(T1ComposeRichTextView *)arg1;
- (void)richTextView:(T1ComposeRichTextView *)arg1 didTapTaggingPromptInRect:(struct CGRect)arg2 ofView:(UIView *)arg3;
@end

