//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNTableViewCell.h>

@class T1ComposableModuleTreeView, TFNTwitterAccount;
@protocol T1URTRichTextInteractionHandler, TFNTwitterConversationTreeContextProvider;

@interface T1ComposableModuleTreeCell : TFNTableViewCell
{
    TFNTwitterAccount *_account;
    id _layoutState;
    CDUnknownBlockType _tombstoneViewTapHandler;
    id <T1URTRichTextInteractionHandler> _tombstoneRichTextHandler;
    T1ComposableModuleTreeView *_treeItemView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) T1ComposableModuleTreeView *treeItemView; // @synthesize treeItemView=_treeItemView;
@property(retain, nonatomic) id <T1URTRichTextInteractionHandler> tombstoneRichTextHandler; // @synthesize tombstoneRichTextHandler=_tombstoneRichTextHandler;
@property(copy, nonatomic) CDUnknownBlockType tombstoneViewTapHandler; // @synthesize tombstoneViewTapHandler=_tombstoneViewTapHandler;
@property(readonly, nonatomic) id layoutState; // @synthesize layoutState=_layoutState;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)didTapOnViewButtonWithTombstoneView:(id)arg1;
- (void)_t1_updateRichTextHandlerOnTombstoneView;
- (void)setCellLayout:(id)arg1;
@property(readonly, nonatomic) id <TFNTwitterConversationTreeContextProvider> viewModel;
- (void)updateViewModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

