//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TAVControlBarItem.h>

@class T1VideoAdButton, T1VideoSkipCountdownLabel, UIStackView, UIView;

@interface T1ControlBarAdSkipControl : TAVControlBarItem
{
    T1VideoAdButton *_skipAdButton;
    T1VideoSkipCountdownLabel *_skipCountdownLabel;
    UIView *_skipCountdownLabelContainerView;
    UIStackView *_containerView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIStackView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *skipCountdownLabelContainerView; // @synthesize skipCountdownLabelContainerView=_skipCountdownLabelContainerView;
@property(retain, nonatomic) T1VideoSkipCountdownLabel *skipCountdownLabel; // @synthesize skipCountdownLabel=_skipCountdownLabel;
@property(retain, nonatomic) T1VideoAdButton *skipAdButton; // @synthesize skipAdButton=_skipAdButton;
- (void)_t1_didTapSkipAdButton;
- (void)t1_updateWithPlaybackState:(id)arg1;
- (void)player:(id)arg1 didUpdatePlaybackState:(id)arg2;
- (id)view;
- (id)initWithIdentifier:(id)arg1;

@end

