//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSArray, T1AccordionButton, T1DurationPickerView, TFNButton, UILabel;

@interface T1ComposePollingCardPreviewView : UIView
{
    _Bool _durationPickerVisible;
    _Bool _isAudienceSelectorVisible;
    NSArray *_textFields;
    TFNButton *_removeButton;
    TFNButton *_addChoiceButton;
    T1AccordionButton *_durationButton;
    T1DurationPickerView *_durationPicker;
    TFNButton *_audienceSelectorButton;
    unsigned long long _numberOfVisibleChoices;
    UIView *_durationContainer;
    UILabel *_durationLabel;
    UIView *_audienceSelectorContainer;
    UIView *_audienceSelectorSeparator;
    UILabel *_audienceSelectorLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *audienceSelectorLabel; // @synthesize audienceSelectorLabel=_audienceSelectorLabel;
@property(retain, nonatomic) UIView *audienceSelectorSeparator; // @synthesize audienceSelectorSeparator=_audienceSelectorSeparator;
@property(retain, nonatomic) UIView *audienceSelectorContainer; // @synthesize audienceSelectorContainer=_audienceSelectorContainer;
@property(retain, nonatomic) UILabel *durationLabel; // @synthesize durationLabel=_durationLabel;
@property(retain, nonatomic) UIView *durationContainer; // @synthesize durationContainer=_durationContainer;
@property(nonatomic) _Bool isAudienceSelectorVisible; // @synthesize isAudienceSelectorVisible=_isAudienceSelectorVisible;
@property(nonatomic) _Bool durationPickerVisible; // @synthesize durationPickerVisible=_durationPickerVisible;
@property(nonatomic) unsigned long long numberOfVisibleChoices; // @synthesize numberOfVisibleChoices=_numberOfVisibleChoices;
@property(retain, nonatomic) TFNButton *audienceSelectorButton; // @synthesize audienceSelectorButton=_audienceSelectorButton;
@property(retain, nonatomic) T1DurationPickerView *durationPicker; // @synthesize durationPicker=_durationPicker;
@property(readonly, nonatomic) T1AccordionButton *durationButton; // @synthesize durationButton=_durationButton;
@property(readonly, nonatomic) TFNButton *addChoiceButton; // @synthesize addChoiceButton=_addChoiceButton;
@property(readonly, nonatomic) TFNButton *removeButton; // @synthesize removeButton=_removeButton;
@property(retain, nonatomic) NSArray *textFields; // @synthesize textFields=_textFields;
- (id)accessibilityElements;
- (long long)indexOfAccessibilityElement:(id)arg1;
- (id)accessibilityElementAtIndex:(long long)arg1;
- (long long)accessibilityElementCount;
- (_Bool)isAccessibilityElement;
- (_Bool)resignFirstResponder;
- (_Bool)isFirstResponder;
- (_Bool)becomeFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (void)setDurationPickerVisible:(_Bool)arg1 animated:(_Bool)arg2 animations:(CDUnknownBlockType)arg3;
- (void)_endingAlphaStateForChoices:(unsigned long long)arg1;
- (void)_endingHiddenStateForChoices:(unsigned long long)arg1;
- (void)setNumberOfVisibleChoices:(unsigned long long)arg1 animated:(_Bool)arg2;
- (double)_heightForNumberOfVisibleChoices:(unsigned long long)arg1;
- (double)_textFieldsHeightForNumberOfChoices:(unsigned long long)arg1;
- (void)_updateAddChoiceButtonForNumberOfChoices:(long long)arg1;
- (void)_updateTextFieldsPositionsForNumberOfChoices:(long long)arg1;
- (void)layoutSubviews;
- (id)_choiceFieldForIndex:(long long)arg1;
@property(readonly, nonatomic) _Bool canAddAnotherChoice;
- (id)choiceTextFields;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1 minInterval:(double)arg2 maxInterval:(double)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

