//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface T1ContactsProfileImageCacheReader : NSObject
{
}

+ (void)readProfileImageCacheWithAccountID:(id)arg1 userID:(long long)arg2 profileImageURL:(id)arg3 completion:(CDUnknownBlockType)arg4;

@end

