//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, TFNComposableViewAdapter, TFNComposableViewSet, TFSSpanContext, TFSTraceConfiguration, TFSTraceSamplingPolicy, TFSTracer;

@interface T1ComposableViewPrepareForReuseTracer : NSObject
{
    _Bool _shouldReportTrace;
    TFNComposableViewSet *_composableViewSet;
    TFNComposableViewAdapter *_composableViewAdapter;
    TFSTracer *_tracer;
    TFSTraceSamplingPolicy *_samplingPolicy;
    TFSTraceConfiguration *_tracerConfiguration;
    TFSSpanContext *_composableViewSetSpan;
    TFSSpanContext *_composableViewAdapterSpan;
}

- (void).cxx_destruct;
- (void)composableViewSetPrepareForReuseCompleted:(id)arg1;
- (void)composableViewSet:(id)arg1 adapterNotInitialized:(id)arg2;
- (void)composableViewSet:(id)arg1 adapterPrepareForReuseCompleted:(id)arg2;
- (void)composableViewSet:(id)arg1 adapterPrepareToReuseBegan:(id)arg2;
- (void)composableViewSetPrepareForReuseBegan:(id)arg1;
- (id)initWithTraceName:(id)arg1 samplingPolicy:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

