//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNComposableViewLayoutStateSet.h>

@class TFNVerticalLayout;

@interface T1ComposableModuleTreeViewLayoutState : TFNComposableViewLayoutStateSet
{
    TFNVerticalLayout *_verticalLayout;
    struct CGSize _size;
    struct CGRect _avatarFrame;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(nonatomic) struct CGRect avatarFrame; // @synthesize avatarFrame=_avatarFrame;
@property(retain, nonatomic) TFNVerticalLayout *verticalLayout; // @synthesize verticalLayout=_verticalLayout;
- (_Bool)isEqual:(id)arg1;

@end

