//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, TFNMenuSheetViewController;
@protocol T1ConversationControlTypeSelectionControllerDelegate;

@interface T1ConversationControlTypeSelectionController : NSObject
{
    _Bool _selectionMade;
    TFNMenuSheetViewController *_menuSheetViewController;
    unsigned long long _selectedConversationControlType;
    id <T1ConversationControlTypeSelectionControllerDelegate> _delegate;
}

+ (_Bool)didSaveFirstNonAllDefaultConversationControlTypeForAccount:(id)arg1;
+ (unsigned long long)savedDefaultConversationControlTypeForAccount:(id)arg1;
+ (void)saveDefaultConversationControlType:(unsigned long long)arg1 account:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) __weak id <T1ConversationControlTypeSelectionControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool selectionMade; // @synthesize selectionMade=_selectionMade;
@property(nonatomic) unsigned long long selectedConversationControlType; // @synthesize selectedConversationControlType=_selectedConversationControlType;
@property(retain, nonatomic) TFNMenuSheetViewController *menuSheetViewController; // @synthesize menuSheetViewController=_menuSheetViewController;
- (void)modalSheetViewControllerDidDismiss:(id)arg1 fromGesture:(_Bool)arg2;
- (void)gestureDidDismissModalContainerViewController:(id)arg1;
- (void)_handleModalGestureDismiss;
- (void)_t1_dismissAnimatedWithDelayAndCompletion:(CDUnknownBlockType)arg1;
- (void)tfn_presentFromViewController:(id)arg1 animated:(_Bool)arg2 sourceInfo:(id)arg3;
- (void)tfn_presentFromViewController:(id)arg1 animated:(_Bool)arg2 sourceInfo:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_t1_didCompleteSelectionWithType:(unsigned long long)arg1 cancelled:(_Bool)arg2;
- (id)initWithInitialConversationControlType:(unsigned long long)arg1 delegate:(id)arg2 account:(id)arg3;
- (void)_t1_setupConversationControlTypeSelectionControllerWithAccount:(id)arg1;
- (id)_t1_createAdapterForInitialConversationControlType:(unsigned long long)arg1;
- (id)_t1_createConversationControlSelectionItemActionForType:(unsigned long long)arg1;
- (void)_t1_selectConversationControlType:(unsigned long long)arg1 initialSetting:(_Bool)arg2;
- (void)_t1_selectConversationControlType:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

