//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNViewController.h>

@class MISSING_TYPE;

@interface T1CreatorTipJarCompleteTipViewController : TFNViewController
{
    MISSING_TYPE *account;
    MISSING_TYPE *tipJarItem;
    MISSING_TYPE *profileViewModel;
    MISSING_TYPE *tipJarCompleteTipView;
}

+ (void)resetDidAlreadyShowLeaveAppAlertWithAccount:(id)arg1;
- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)closeTapped;
- (id)initWithCoder:(id)arg1;
- (void)viewDidLoad;
- (double)preferredHeightForModalSheetViewController:(id)arg1 modalContentViewVisibleEdgeInsets:(struct UIEdgeInsets)arg2;
- (id)scribePage;
- (id)scribe;

@end

