//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, T1DashContentPresenter;

@interface T1DashContentController : NSObject
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *presenter;
    MISSING_TYPE *dataSource;
    MISSING_TYPE *visiblePanelIDs;
    MISSING_TYPE *badgeCountsForUserID;
    MISSING_TYPE *communitiesAppNavigationEntryVisibilityManager;
    MISSING_TYPE *communitiesEntryVisibilityObservationHandle;
    MISSING_TYPE *listFeatureSwitches;
    MISSING_TYPE *profileViewModel;
    MISSING_TYPE *cachedFollowerRequestsItem;
    MISSING_TYPE *cachedTeamsInvitationItem;
    MISSING_TYPE *cachedFeatureSwitchAppReviewItem;
    MISSING_TYPE *interactionsTimelineBridge;
    MISSING_TYPE *cancellables;
    MISSING_TYPE *account;
}

- (void).cxx_destruct;
- (id)init;
- (void)updateDashItems;
- (void)updateVisiblePanelIDs;
- (void)prepareForReuse;
- (void)appSplitViewControllerDidUpdate:(id)arg1;
- (void)dealloc;
- (id)initWithAccount:(id)arg1 interactionsTimelineBridge:(id)arg2;
@property(nonatomic, readonly) T1DashContentPresenter *presenter; // @synthesize presenter;
- (void)teamsInvitationDidUpdateWithNotification:(id)arg1;
- (void)accountUserDidUpdateWithNotification:(id)arg1;

@end

