//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSIndexPath, T1DirectMessageUserTypeaheadRowAdapter, TFNDirectMessageUser;

@protocol T1DirectMessageUserTypeaheadRowAdapterDelegate <NSObject>
- (void)directMessageUserTypeaheadRowAdapter:(T1DirectMessageUserTypeaheadRowAdapter *)arg1 didSelectUser:(TFNDirectMessageUser *)arg2 atIndexPath:(NSIndexPath *)arg3;
@end

