//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNLegacyFormField.h>

@class NSString;

@interface T1EditProfileFormField : TFNLegacyFormField
{
    NSString *_scribeElement;
}

+ (_Bool)validURLString:(id)arg1;
+ (id)formFieldWithTitle:(id)arg1 hintText:(id)arg2 userInput:(id)arg3 maxLength:(unsigned long long)arg4 scribeElement:(id)arg5;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *scribeElement; // @synthesize scribeElement=_scribeElement;

@end

