//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNLegacyFormViewController.h>

@class NSString, T1EditProfileBlurrableBannerImageView, T1EditProfileForm, T1PhotoSelection, T1PickAndFilterPhotoFlowController, TFNAvatarHeaderView, TFNTwitterAccount, UIBarButtonItem, UIImageView, UIView;
@protocol T1EditProfileViewControllerDelegate><T1ProfessionalModuleObserver;

@interface T1EditProfileViewController : TFNLegacyFormViewController
{
    _Bool _didShowAddBirthdayWarning;
    _Bool _userAddedAvatar;
    _Bool _userAddedBanner;
    _Bool _userRemovedBanner;
    _Bool _clearNavigationBarMode;
    double _bannerHeight;
    UIBarButtonItem *_doneBarButtonItem;
    struct CGRect _keyboardViewFrame;
    _Bool _keyboardViewShowing;
    UIView *_bannerContainerView;
    UIView *_darkenView;
    long long _keyboardAnimationCurve;
    double _keyboardAnimationDuration;
    id <T1EditProfileViewControllerDelegate><T1ProfessionalModuleObserver> _delegate;
    TFNTwitterAccount *_account;
    unsigned long long _blueCheckmarkCalloutType;
    T1EditProfileBlurrableBannerImageView *_bannerView;
    UIImageView *_cameraIcon;
    TFNAvatarHeaderView *_avatarHeaderView;
    long long _selectedField;
    T1PhotoSelection *_selectedAvatarPhoto;
    T1PhotoSelection *_selectedBannerPhoto;
    T1PickAndFilterPhotoFlowController *_photoPicker;
}

- (void).cxx_destruct;
@property(retain, nonatomic) T1PickAndFilterPhotoFlowController *photoPicker; // @synthesize photoPicker=_photoPicker;
@property(retain, nonatomic) T1PhotoSelection *selectedBannerPhoto; // @synthesize selectedBannerPhoto=_selectedBannerPhoto;
@property(retain, nonatomic) T1PhotoSelection *selectedAvatarPhoto; // @synthesize selectedAvatarPhoto=_selectedAvatarPhoto;
@property(nonatomic) long long selectedField; // @synthesize selectedField=_selectedField;
@property(retain, nonatomic) TFNAvatarHeaderView *avatarHeaderView; // @synthesize avatarHeaderView=_avatarHeaderView;
@property(retain, nonatomic) UIImageView *cameraIcon; // @synthesize cameraIcon=_cameraIcon;
@property(retain, nonatomic) T1EditProfileBlurrableBannerImageView *bannerView; // @synthesize bannerView=_bannerView;
@property(readonly, nonatomic) unsigned long long blueCheckmarkCalloutType; // @synthesize blueCheckmarkCalloutType=_blueCheckmarkCalloutType;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(nonatomic) __weak id <T1EditProfileViewControllerDelegate><T1ProfessionalModuleObserver> delegate; // @synthesize delegate=_delegate;
- (void)_t1_scribeFinish;
- (void)scribeAction:(id)arg1 inComponent:(id)arg2 forPhotoType:(long long)arg3 parameters:(id)arg4;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (struct CGRect)additionalGutterFrame;
- (void)_t1_uploadAvatarAndBannerThenUpdateProfile;
- (void)_t1_showErrorForEditProfileDeniedForBlueSubscriberUnderReview;
- (void)_t1_confirmUploadAvatarAndBannerThenUpdateProfileForBlueCheckmark;
- (void)submitForm;
- (void)layoutMetricsDidChange:(id)arg1 to:(id)arg2;
- (void)editProfileFormDidTapAccountAuthenticityLearnMore:(id)arg1;
- (void)editProfileFormDidTapBlueCheckmarkHintLearnMore:(id)arg1;
- (void)tweetTakeoverPromptViewController:(id)arg1 didSelectSendTweetWithComposition:(id)arg2;
- (void)tweetTakeoverPromptViewController:(id)arg1 didSelectEditTweetWithComposition:(id)arg2;
- (void)_t1_dropImage:(id)arg1 ofType:(long long)arg2;
- (_Bool)dropInteraction:(id)arg1 canHandleSession:(id)arg2;
- (id)dropInteraction:(id)arg1 sessionDidUpdate:(id)arg2;
- (void)dropInteraction:(id)arg1 performDrop:(id)arg2;
- (void)profileModulesDidChange;
- (void)_t1_userDataSourceDidUpdate:(id)arg1;
- (void)tipJarSettingsShowTipsOnPrompt;
- (void)tipJarSettingsDidChange:(_Bool)arg1;
- (void)pickAndFilterPhotoFlowController:(id)arg1 removePhotoType:(long long)arg2;
- (void)pickAndFilterPhotoFlowController:(id)arg1 userDidCancelPhotoType:(long long)arg2;
- (void)pickAndFilterPhotoFlowController:(id)arg1 userDidSelectPhoto:(id)arg2 type:(long long)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_updateNavigationBarStyle:(_Bool)arg1;
- (void)applicationWillEnterForegroundFromBackground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)tfn_addDirectlyOwnedViewControllersToMutableArray:(id)arg1;
- (void)_setupBannerAppearance;
- (void)viewWillLayoutSubviews;
- (void)didSelectItem:(id)arg1 atIndexPath:(id)arg2;
- (void)_didSelectField:(id)arg1;
- (void)loadBlueProfileEditWarningMessageConfig;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)_uploadBanner:(id)arg1;
- (void)_requestUserRefreshForced;
- (void)_uploadAvatar:(id)arg1;
- (void)_didTapBanner:(id)arg1;
- (void)_didTapAvatar:(id)arg1;
- (void)_closeAction;
- (void)proceedAfterSaving;
- (void)save;
- (void)_removeBanner;
- (void)setPhoto:(id)arg1 ofType:(long long)arg2;
- (void)_t1_selectPhotoOfTypeWithPhotoGallery:(long long)arg1 fromView:(id)arg2;
- (unsigned long long)inputRequiredBehavior;
- (id)doneBarButtonItem;
- (double)headerHeightForScrollView:(id)arg1 minimumHeight:(double)arg2;
- (_Bool)shouldShowCloseButton;
- (_Bool)addsDoneBarButtonButtonItemToNavigationBar;
- (unsigned long long)_t1_blueCheckmarkCalloutTypeWithAccount:(id)arg1;
@property(readonly, nonatomic) T1EditProfileForm *profileForm;
- (void)dealloc;
- (id)initWithForm:(id)arg1 appearance:(id)arg2;
- (id)initWithAccount:(id)arg1 selectedField:(long long)arg2;
- (id)initWithAccount:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

