//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol TPSFeatureSwitchesAccess;

@interface T1ExploreFeatures : NSObject
{
    id <TPSFeatureSwitchesAccess> _featureSwitches;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <TPSFeatureSwitchesAccess> featureSwitches; // @synthesize featureSwitches=_featureSwitches;
@property(readonly, nonatomic) _Bool enableNewsTab;
@property(readonly, nonatomic) _Bool enableNewExplore;
@property(readonly, nonatomic) long long shrunkSummaryLines;
@property(readonly, nonatomic) _Bool shouldAutoExpandSummary;
@property(readonly, nonatomic) _Bool isAITrendsEnabled;
@property(readonly, nonatomic) _Bool isAITrendsImagesEnabled;
@property(readonly, nonatomic) unsigned long long videoCarouselModuleMediaContextType;
@property(readonly, nonatomic) _Bool isSpotlightAdMuteEnabled;
@property(readonly, nonatomic) double dynamicChromeRefreshInterval;
@property(readonly, nonatomic) _Bool isExploreSettingsEnabled;
@property(readonly, nonatomic) NSString *tabIconName;
@property(readonly, nonatomic) double minimumAutoRefreshInterval;
@property(readonly, nonatomic) _Bool isTrendingTabEnabled;
@property(readonly, nonatomic) _Bool isTabsEnabled;
- (id)init;
- (id)initWithFeatureSwitches:(id)arg1;

@end

