//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, T1FoundMediaConfiguration, T1FoundMediaSearchContainerStreamViewController, TFNTwitterAccount, UINavigationController;
@protocol T1FoundMediaControllerDelegate;

@interface T1FoundMediaController : NSObject
{
    UINavigationController *_rootFoundMediaNavigationController;
    _Bool _useLayoutModeNumberOfColumns;
    id <T1FoundMediaControllerDelegate> _delegate;
    T1FoundMediaConfiguration *_configuration;
    TFNTwitterAccount *_account;
    NSString *_scribePage;
    NSString *_scribeSection;
    T1FoundMediaSearchContainerStreamViewController *_foundMediaViewController;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool useLayoutModeNumberOfColumns; // @synthesize useLayoutModeNumberOfColumns=_useLayoutModeNumberOfColumns;
@property(retain, nonatomic) T1FoundMediaSearchContainerStreamViewController *foundMediaViewController; // @synthesize foundMediaViewController=_foundMediaViewController;
@property(readonly, copy, nonatomic) NSString *scribeSection; // @synthesize scribeSection=_scribeSection;
@property(readonly, copy, nonatomic) NSString *scribePage; // @synthesize scribePage=_scribePage;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(readonly, nonatomic) T1FoundMediaConfiguration *configuration; // @synthesize configuration=_configuration;
@property(nonatomic) __weak id <T1FoundMediaControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)modalSheetViewControllerDidDismiss:(id)arg1 fromGesture:(_Bool)arg2;
- (void)modalSheetViewController:(id)arg1 willTransitionToLayoutMode:(long long)arg2 withTransitionCoordinator:(id)arg3;
- (void)foundMediaSearchContainerStreamViewController:(id)arg1 traitCollectionDidChange:(id)arg2;
- (void)foundMediaSearchContainerStreamViewController:(id)arg1 didLongPressFoundMediaItem:(id)arg2 sourceView:(id)arg3;
- (void)foundMediaSearchContainerStreamViewControllerDidDismissFromGesture:(id)arg1;
- (void)foundMediaSearchContainerStreamViewControllerDidCancel:(id)arg1;
- (void)foundMediaSearchContainerStreamViewController:(id)arg1 didSelectFoundMediaItem:(id)arg2;
- (id)_objectsStreamWithGroup:(id)arg1 account:(id)arg2;
- (void)foundMediaSearchContainerStreamViewController:(id)arg1 didSelectFoundMediaGroup:(id)arg2;
- (id)_rootStreamWithAccount:(id)arg1;
@property(readonly, nonatomic) UINavigationController *rootFoundMediaNavigationController;
- (id)initWithConfiguration:(id)arg1 account:(id)arg2 scribePage:(id)arg3 scribeSection:(id)arg4;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

