//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol T1FoundMediaStreamSource;

@interface T1FoundMediaStreamTopLevelGroupsSource : NSObject
{
    id <T1FoundMediaStreamSource> _upstreamSource;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <T1FoundMediaStreamSource> upstreamSource; // @synthesize upstreamSource=_upstreamSource;
- (id)_t1_retrieveValidSavedItemsForAccountID:(id)arg1;
- (id)loadWithOptions:(id)arg1 account:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

