//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface T1GetVerifiedSheetPresenter : NSObject
{
}

+ (void)presentFromViewController:(id)arg1 account:(id)arg2 scribePage:(id)arg3 title:(id)arg4 message:(id)arg5 cancelButtonTitle:(id)arg6 shouldShowVerifiedIcon:(_Bool)arg7;
- (id)init;

@end

