//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSSet, NSString;

@interface T1HostMapEntry : NSObject
{
    NSString *_host;
    NSString *_mappedHost;
    NSSet *_literalPaths;
    NSSet *_prefixPaths;
}

+ (id)entryWithHostMapString:(id)arg1;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSSet *prefixPaths; // @synthesize prefixPaths=_prefixPaths;
@property(readonly, copy, nonatomic) NSSet *literalPaths; // @synthesize literalPaths=_literalPaths;
@property(readonly, copy, nonatomic) NSString *mappedHost; // @synthesize mappedHost=_mappedHost;
@property(readonly, copy, nonatomic) NSString *host; // @synthesize host=_host;
- (id)initWithHost:(id)arg1 mappedHost:(id)arg2 literalPaths:(id)arg3 prefixPaths:(id)arg4;
- (_Bool)matchesPath:(id)arg1;
- (_Bool)doesMatchEverything;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

