//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class TIPImageFetchOperation;

@protocol T1ImagePipelineLoadSourceEventObserver <NSObject>

@optional
- (void)imageFetchOperation:(TIPImageFetchOperation *)arg1 didFail:(long long)arg2;
- (void)imageFetchOperation:(TIPImageFetchOperation *)arg1 didCancel:(long long)arg2;
- (void)imageFetchOperation:(TIPImageFetchOperation *)arg1 didMiss:(long long)arg2;
- (void)imageFetchOperation:(TIPImageFetchOperation *)arg1 didHit:(long long)arg2;
@end

