//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSNumber, TIPGlobalConfiguration, TNLCommunicationAgent;
@protocol OS_dispatch_queue;

@interface T1ImageQualitySettings : NSObject
{
    _Bool _hasCellularInterface;
    TNLCommunicationAgent *_communicationAgent;
    TIPGlobalConfiguration *_tipConfiguration;
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSNumber *_internalCurrentValueNumber;
}

+ (id)sharedSettings;
- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *internalCurrentValueNumber; // @synthesize internalCurrentValueNumber=_internalCurrentValueNumber;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(readonly, nonatomic) TIPGlobalConfiguration *tipConfiguration; // @synthesize tipConfiguration=_tipConfiguration;
@property(readonly, nonatomic) TNLCommunicationAgent *communicationAgent; // @synthesize communicationAgent=_communicationAgent;
@property(readonly, nonatomic) _Bool hasCellularInterface; // @synthesize hasCellularInterface=_hasCellularInterface;
- (void)tnl_communicationAgent:(id)arg1 didUpdateReachabilityFromPreviousFlags:(unsigned int)arg2 previousStatus:(long long)arg3 toCurrentFlags:(unsigned int)arg4 currentStatus:(long long)arg5;
- (void)_tfn_clearRenderedCacheIfNeededWhenSwitchingFromOldSettings:(long long)arg1 oldStatus:(long long)arg2 toNewSettings:(long long)arg3 newStatus:(long long)arg4;
@property(readonly) _Bool shouldUseHighQualityImages;
@property long long currentValue;
- (void)setHasCellularInterface:(_Bool)arg1;
- (id)initWithCommunicationAgent:(id)arg1 tipConfiguration:(id)arg2;
- (id)init;

@end

