//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNViewController.h>

@class MISSING_TYPE;
@protocol T1ImmersiveViewControllerDelegate;

@interface T1ImmersiveViewController : TFNViewController
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *audioSessionManager;
    MISSING_TYPE *autoplayPolicies;
    MISSING_TYPE *blurTransitionAnimation;
    MISSING_TYPE *initialSeekTime;
    MISSING_TYPE *lastCardControlState;
    MISSING_TYPE *isActivePane;
    MISSING_TYPE *forcedOrientation;
    MISSING_TYPE *viewModel;
    MISSING_TYPE *account;
    MISSING_TYPE *scribeContext;
    MISSING_TYPE *viewSource;
    MISSING_TYPE *initialStatus;
    MISSING_TYPE *initialBroadcast;
    MISSING_TYPE *initialBroadcastID;
    MISSING_TYPE *autoAdvanceDurationThreshold;
    MISSING_TYPE *mediaCastEnabled;
    MISSING_TYPE *accessibilityPostNotification;
    MISSING_TYPE *videoLoopCount;
    MISSING_TYPE *features;
    MISSING_TYPE *cardContainer;
    MISSING_TYPE *cardViews;
    MISSING_TYPE *cardReusePool;
    MISSING_TYPE *errorView;
    MISSING_TYPE *bottomBarControls;
    MISSING_TYPE *immersiveLoadingView;
    MISSING_TYPE *_primaryCardIndex;
    MISSING_TYPE *verticalPanRecognizer;
    MISSING_TYPE *cardContentTop;
    MISSING_TYPE *videoMayPlay;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)resetInitialVideoIfNeeded;
- (id)getCurrentCardBroadcast;
- (id)getCurrentCardView;
@property(nonatomic, readonly) struct CGRect firstVideoPlayerFrame;
- (void)userUpdatedFavoriteStatusForTweetWithNotification:(id)arg1;
- (void)handleVerticalPan:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)requestRetryTapped;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForegroundFromBackground:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) double cardContentTop; // @synthesize cardContentTop;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithAccount:(id)arg1 scribeContext:(id)arg2 viewSource:(long long)arg3 initialStatus:(id)arg4 initialStatusID:(id)arg5 initialBroadcast:(id)arg6 initialBroadcastID:(id)arg7 isMuted:(_Bool)arg8 enteredViaTimestamp:(id)arg9 viewModel:(id)arg10;
@property(nonatomic) _Bool isActivePane; // @synthesize isActivePane;
@property(nonatomic) __weak id <T1ImmersiveViewControllerDelegate> delegate; // @synthesize delegate;
- (void)graduatedAccessUserPrompt:(id)arg1 didTapLearnMoreURL:(id)arg2;
@property(nonatomic, readonly) long long preferredInterfaceOrientationForPresentation;
@property(nonatomic, readonly) unsigned long long tfn_supportedInterfaceOrientations;
- (void)orientationChanged:(id)arg1;
- (id)scribeImpressionParameters;
- (id)scribeParameters;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (_Bool)accessibilityScroll:(long long)arg1;
- (_Bool)allowsJumpBackToHomeTimeline;

@end

