//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol TPSFeatureSwitchesAccess;

@interface T1InterestsFeatures : NSObject
{
    id <TPSFeatureSwitchesAccess> _featureSwitches;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id <TPSFeatureSwitchesAccess> featureSwitches; // @synthesize featureSwitches=_featureSwitches;
@property(readonly, nonatomic) long long focusedTimelineActionsOnboardingLikesToComplete;
@property(readonly, nonatomic) _Bool isHomeTimelineLikeReactivityEnabled;
@property(readonly, nonatomic) long long homeTimelineLikeReactivitySessionLengthInMinutes;
@property(readonly, nonatomic) long long homeTimelineLikeReactivityNumTweets;
@property(readonly, nonatomic) long long homeTimelineLikeReactivityFatigue;
- (id)initWithFeatureSwitches:(id)arg1;
- (id)init;

@end

