//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class T1LiveEventCarouselEntry, T1LiveEventCarouselTransitionHandler;

@protocol T1LiveEventCarouselTransitionObserver <NSObject>
- (void)carouselTransitionHandlerDidRequestReplayOfCurrentItem:(T1LiveEventCarouselTransitionHandler *)arg1;
- (void)carouselTransitionHandler:(T1LiveEventCarouselTransitionHandler *)arg1 didCompleteTransitionToCarouselEntry:(T1LiveEventCarouselEntry *)arg2;
@end

