//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface T1LiveEventCardViewTheme : NSObject
{
}

+ (id)_t1_guideHeroTheme;
+ (id)_t1_cardTheme;
+ (id)themeForCardContext:(id)arg1;
- (id)init;

@end

