//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/T1AccountAdder-Protocol.h>

@class UIViewController;

@protocol T1LoginChallengeProtocol <T1AccountAdder>
+ (_Bool)isAuthenticationInProgress;
- (void)presentLoginChallengeFromViewController:(UIViewController *)arg1 animated:(_Bool)arg2 completion:(void (^)(void))arg3;
@end

