//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class TUICardView;
@protocol TUICardViewDelegate;

@interface T1MessageMeCardEventRegistry : NSObject
{
    TUICardView *_view;
    id <TUICardViewDelegate> _delegate;
    SEL _didTapDMButtonSEL;
}

- (void).cxx_destruct;
@property(nonatomic) SEL didTapDMButtonSEL; // @synthesize didTapDMButtonSEL=_didTapDMButtonSEL;
@property(nonatomic) __weak id <TUICardViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) __weak TUICardView *view; // @synthesize view=_view;
- (void)_registerEventHandlers;
- (void)didTapDMPromptButton:(id)arg1 event:(id)arg2;
- (void)registerDMPromptButton:(id)arg1;
- (id)initWithView:(id)arg1;

@end

