//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSDictionary, T1NetworkTrafficMappingService, TNLRequestOperation, TNUTransactionMetrics;

@protocol T1NetworkTrafficMappingServiceDelegate <NSObject>
- (double)trafficMappingService:(T1NetworkTrafficMappingService *)arg1 normalizedRequestDuration:(TNLRequestOperation *)arg2;
- (void)trafficMappingServiceDidEncounterPredictionMeasurementFailed:(T1NetworkTrafficMappingService *)arg1;
- (void)trafficMappingServiceDidEncounterIncorrectPrediction:(T1NetworkTrafficMappingService *)arg1;
- (void)trafficMappingServiceDidEncounterCorrectPrediction:(T1NetworkTrafficMappingService *)arg1;
- (void)trafficMappingServiceDidThrottleProbe;
- (void)trafficMappingService:(T1NetworkTrafficMappingService *)arg1 didCaptureProbeMetrics:(TNUTransactionMetrics *)arg2 hostToContextDic:(NSDictionary *)arg3;
- (void)trafficMappingServiceDidEncounterInvalidTrafficMap:(T1NetworkTrafficMappingService *)arg1;
- (void)trafficMappingServiceDidDiscardTrafficMap:(T1NetworkTrafficMappingService *)arg1;
- (void)trafficMappingServiceDidPurgeTrafficMap:(T1NetworkTrafficMappingService *)arg1;
- (void)trafficMappingServiceDidClearTrafficMap:(T1NetworkTrafficMappingService *)arg1;
- (void)trafficMappingServiceDidApplyTrafficMap:(T1NetworkTrafficMappingService *)arg1;
@end

