//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface T1OnboardingTrustedDeviceIDProvider : NSObject
{
    NSString *_trustedDeviceIDString;
    NSObject<OS_dispatch_queue> *_keychainQueue;
}

+ (id)sharedProvider;
+ (void)createSharedProviderWithKeychain:(id)arg1;
- (void).cxx_destruct;
@property(retain) NSString *trustedDeviceIDString; // @synthesize trustedDeviceIDString=_trustedDeviceIDString;
- (id)_t1_generateTrustedDeviceID;
- (void)_t1_fetchOrCreateTrustedDeviceIDWithKeychain:(id)arg1;
- (id)init;

@end

