//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray;
@protocol T1PeopleAddressBookViewControllerDataSourceDelegate;

@protocol T1PeopleAddressBookViewControllerDataSource
@property(nonatomic) __weak id <T1PeopleAddressBookViewControllerDataSourceDelegate> delegate;
- (void)refresh;
@property(nonatomic, readonly) NSArray *recommendations;
@property(nonatomic, readonly) _Bool contactsSynchronizationAuthorized;
@property(nonatomic, readonly) _Bool hasError;
@property(nonatomic, readonly) _Bool loading;
@property(nonatomic, readonly) double progress;
@end

