//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSDate;

@protocol T1PeopleAddressBookSynchronizationSettings <NSObject>
@property(nonatomic, copy) NSDate *addressBookSynchronizationLastExtReuploadTime;
@property(nonatomic) long long addressBookSynchronizationUploadMode;
- (void)setAddressBookSynchronizationStatusDeniedWithReason:(long long)arg1;
@property(nonatomic, readonly) long long addressBookSynchronizationDenialReason;
@property(nonatomic) long long addressBookSynchronizationStatus;
@end

