//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class T1PhotoGalleryLimitedAuthorizationStatusView;

@protocol T1PhotoGalleryLimitedAuthorizationStatusViewDelegate <NSObject>

@optional
- (void)limitedAuthorizationStatusViewDidTapManage:(T1PhotoGalleryLimitedAuthorizationStatusView *)arg1;
@end

