//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class PHCachingImageManager, PHImageRequestOptions;
@protocol T1PhotoCachingImageManagerHelperDelegate;

@interface T1PhotoCachingImageManagerHelper : NSObject
{
    PHCachingImageManager *_imageManager;
    id <T1PhotoCachingImageManagerHelperDelegate> _delegate;
    long long _contentMode;
    PHImageRequestOptions *_options;
    struct CGSize _targetSize;
    struct CGRect _cachedRect;
}

- (void).cxx_destruct;
@property(retain, nonatomic) PHImageRequestOptions *options; // @synthesize options=_options;
@property(nonatomic) long long contentMode; // @synthesize contentMode=_contentMode;
@property(nonatomic) struct CGSize targetSize; // @synthesize targetSize=_targetSize;
@property(readonly, nonatomic) struct CGRect cachedRect; // @synthesize cachedRect=_cachedRect;
@property(nonatomic) __weak id <T1PhotoCachingImageManagerHelperDelegate> delegate; // @synthesize delegate=_delegate;
- (int)requestImageForAsset:(id)arg1 resultHandler:(CDUnknownBlockType)arg2;
- (void)updateForRect:(struct CGRect)arg1;
- (void)invalidate;
- (_Bool)_canUseCachingImageManager;
@property(readonly, nonatomic) PHCachingImageManager *imageManager;
- (void)dealloc;

@end

