//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class T1PhotoSelection, T1PickAndFilterPhotoFlowController;

@protocol T1PickAndFilterPhotoFlowControllerDelegate <NSObject>

@optional
- (void)pickAndFilterPhotoFlowController:(T1PickAndFilterPhotoFlowController *)arg1 removePhotoType:(long long)arg2;
- (void)pickAndFilterPhotoFlowController:(T1PickAndFilterPhotoFlowController *)arg1 userDidCancelPhotoType:(long long)arg2;
- (void)pickAndFilterPhotoFlowController:(T1PickAndFilterPhotoFlowController *)arg1 userDidSelectPhoto:(T1PhotoSelection *)arg2 type:(long long)arg3;
@end

