//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNTappableHighlightView.h>

@class TFNAttributedTextView, UIView;

@interface T1ProfileVerificationPolicyViolationView : TFNTappableHighlightView
{
    UIView *_violationImageView;
    UIView *_violationTitleLabel;
    TFNAttributedTextView *_violationDescriptionView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TFNAttributedTextView *violationDescriptionView; // @synthesize violationDescriptionView=_violationDescriptionView;
@property(retain, nonatomic) UIView *violationTitleLabel; // @synthesize violationTitleLabel=_violationTitleLabel;
@property(retain, nonatomic) UIView *violationImageView; // @synthesize violationImageView=_violationImageView;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithViolation:(id)arg1 urlString:(id)arg2;

@end

