//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class T1ProfileActionButtonsView;

@protocol T1ProfileActionButtonsViewDelegate <NSObject>
- (void)profileActionButtonsViewDidUpdateButtons:(T1ProfileActionButtonsView *)arg1;
- (void)profileActionButtonsViewDidUpdateOccupiedContentRect:(T1ProfileActionButtonsView *)arg1;
- (struct UIEdgeInsets)buttonInsetsForProfileActionButtonsView:(T1ProfileActionButtonsView *)arg1;
@end

