//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNViewController.h>

@class NSString, T1ProfileFriendsFollowingViewModel, TFNAttributedTextView, TFNFlexibleLayoutView, TFNSolidColorView, TFNTappableHighlightView, TIPImagePipeline, TUIUserFacepileView;

@interface T1ProfileFriendsFollowingViewController : TFNViewController
{
    id subheaderInfo;
    CDUnknownBlockType preferredHeightCheckBlock;
    T1ProfileFriendsFollowingViewModel *_viewModel;
    TFNSolidColorView *_backgroundView;
    TUIUserFacepileView *_facepileView;
    TFNFlexibleLayoutView *_flexibleLayoutView;
    TFNAttributedTextView *_followCountsTextView;
    TFNAttributedTextView *_friendsFollowingTextView;
    TFNTappableHighlightView *_highlightView;
    TIPImagePipeline *_imagePipeline;
}

+ (struct CGSize)estimatedSizeForSize:(struct CGSize)arg1 layoutMetrics:(id)arg2 viewModel:(id)arg3 account:(id)arg4;
- (void).cxx_destruct;
@property(retain, nonatomic) TIPImagePipeline *imagePipeline; // @synthesize imagePipeline=_imagePipeline;
@property(retain, nonatomic) TFNTappableHighlightView *highlightView; // @synthesize highlightView=_highlightView;
@property(retain, nonatomic) TFNAttributedTextView *friendsFollowingTextView; // @synthesize friendsFollowingTextView=_friendsFollowingTextView;
@property(retain, nonatomic) TFNAttributedTextView *followCountsTextView; // @synthesize followCountsTextView=_followCountsTextView;
@property(retain, nonatomic) TFNFlexibleLayoutView *flexibleLayoutView; // @synthesize flexibleLayoutView=_flexibleLayoutView;
@property(retain, nonatomic) TUIUserFacepileView *facepileView; // @synthesize facepileView=_facepileView;
@property(retain, nonatomic) TFNSolidColorView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) T1ProfileFriendsFollowingViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(copy, nonatomic) CDUnknownBlockType preferredHeightCheckBlock; // @synthesize preferredHeightCheckBlock;
@property(retain, nonatomic) id subheaderInfo; // @synthesize subheaderInfo;
- (double)preferredHeight;
- (void)attributedTextView:(id)arg1 didTapRange:(id)arg2 rect:(struct CGRect)arg3;
- (void)showCreatorSubscriptions;
- (void)showSuperFollowing;
- (void)showFollowing;
- (void)showFollowersWithTab:(unsigned long long)arg1;
- (void)_t1_setNeedsUpdate;
- (void)_t1_profileViewModelDidInvalidate:(id)arg1;
- (id)_t1_segmentedViewControllerWithTab:(long long)arg1;
- (void)_t1_presentViewController:(id)arg1;
- (void)_t1_logAction:(id)arg1;
- (void)_t1_didTapButton:(id)arg1;
- (void)_t1_layoutSubviews;
- (void)tfn_fontSizeChanged;
- (void)layoutMetricsDidChange:(id)arg1 to:(id)arg2;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithAccount:(id)arg1 profileViewModel:(id)arg2 imagePipeline:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

