//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class T1AccountNotificationSettingsProperty, TFNActionItem, TFNButton, UIViewController;
@protocol T1ProfileActionButtonProviderTweetPerspective;

@interface T1ProfileActionTweetNotificationsButtonProvider
{
    _Bool _shouldShowButton;
    TFNButton *_notificationsButton;
    TFNActionItem *_notificationsOverflowItem;
    id <T1ProfileActionButtonProviderTweetPerspective> _sourceStatus;
    long long _tweetNotificationsRelationshipState;
    UIViewController *_controller;
    T1AccountNotificationSettingsProperty *_notificationSettingsProperty;
}

- (void).cxx_destruct;
@property(retain, nonatomic) T1AccountNotificationSettingsProperty *notificationSettingsProperty; // @synthesize notificationSettingsProperty=_notificationSettingsProperty;
@property(nonatomic) __weak UIViewController *controller; // @synthesize controller=_controller;
@property(nonatomic) long long tweetNotificationsRelationshipState; // @synthesize tweetNotificationsRelationshipState=_tweetNotificationsRelationshipState;
@property(nonatomic) _Bool shouldShowButton; // @synthesize shouldShowButton=_shouldShowButton;
@property(retain, nonatomic) id <T1ProfileActionButtonProviderTweetPerspective> sourceStatus; // @synthesize sourceStatus=_sourceStatus;
@property(retain, nonatomic) TFNActionItem *notificationsOverflowItem; // @synthesize notificationsOverflowItem=_notificationsOverflowItem;
@property(retain, nonatomic) TFNButton *notificationsButton; // @synthesize notificationsButton=_notificationsButton;
- (void)_notificationsButtonTapped:(id)arg1;
- (id)_promotedContent;
- (void)viewModelDidInvalidateForReason:(long long)arg1;
- (id)overflowItem;
- (id)buttonView;
- (_Bool)isVisibleWithAvailableWidth:(double)arg1;
- (void)presentNotificationSettings:(id)arg1;
- (void)presentNotificationSettingsRequireChangeAlert:(id)arg1;
- (void)presentNotificationOptions:(id)arg1;
- (id)initWithAccount:(id)arg1 viewModel:(id)arg2 controller:(id)arg3 sourceStatus:(id)arg4;

@end

