//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIButton.h>

@class UIFont, UIImageView;

@interface T1PrerollCTAButton : UIButton
{
    UIFont *_labelFont;
    UIImageView *_iconView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UIFont *labelFont; // @synthesize labelFont=_labelFont;
- (void)_t1_updateColors;
- (void)_t1_updateIcon;
- (void)_t1_setup;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithVerticalSpacing:(double)arg1;

@end

