//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSArray, NSString, TFNFlexibleLayoutView, TFNTwitterUserDataSource;
@protocol T1ProfileActionButtonsViewDelegate, TFNActionItem;

@interface T1ProfileActionButtonsView : UIView
{
    TFNFlexibleLayoutView *_innerContentView;
    TFNFlexibleLayoutView *_outerContentView;
    NSArray<TFNActionItem> *_overflowItems;
    id <T1ProfileActionButtonsViewDelegate> _delegate;
    NSArray *_buttonProviders;
    TFNTwitterUserDataSource *_userDataSource;
    struct CGRect _occupiedContentRect;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TFNTwitterUserDataSource *userDataSource; // @synthesize userDataSource=_userDataSource;
@property(copy, nonatomic) NSArray *buttonProviders; // @synthesize buttonProviders=_buttonProviders;
@property(nonatomic) struct CGRect occupiedContentRect; // @synthesize occupiedContentRect=_occupiedContentRect;
@property(nonatomic) __weak id <T1ProfileActionButtonsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_t1_showOverflowMenu:(id)arg1;
- (id)_t1_overflowButtonForItems:(id)arg1;
- (void)_t1_updateArrangedButtonItemsForContentWidth:(double)arg1;
- (void)_t1_updateAllButtonViews;
- (id)effectiveViewForButtonView:(id)arg1;
- (_Bool)isButtonViewPresentAndVisible:(id)arg1;
- (void)actionButtonProviderDidUpdateButton:(id)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)tfn_fontSizeChanged;
- (id)visibleButtonSpecs;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

