//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, TFNTwitterAccount, TFNTwitterUserDataSource;
@protocol T1GraphQLFeaturesProtocol;

@interface T1ProfileSegmentedFollowingViewControllerDataSource : NSObject
{
    long long _primaryTab;
    TFNTwitterAccount *_account;
    TFNTwitterUserDataSource *_userDataSource;
    _Bool _showSegmentedFollowersYouKnowViewController;
    _Bool _showSegmentedVerifiedFollowersViewController;
    _Bool _showSegmentedSuperFollowersViewController;
    _Bool _showSegmentedSubscriptionsViewController;
    _Bool _showPrimaryTabOnly;
    id <T1GraphQLFeaturesProtocol> _graphQLFeatures;
}

+ (_Bool)_t1_isUserDataSource:(id)arg1 protectedFromViewingByAccount:(id)arg2;
+ (id)_t1_friendsFollowingViewControllerWithUserDataSource:(id)arg1 account:(id)arg2;
- (void).cxx_destruct;
- (long long)_t1_segmentTabForIndex:(long long)arg1;
- (long long)tabForSegmentIndex:(long long)arg1;
- (long long)segmentIndexForTab:(long long)arg1;
- (id)segmentedViewController:(id)arg1 viewControllerAtIndex:(long long)arg2;
- (long long)segmentedViewController:(id)arg1 caretAtIndex:(long long)arg2;
- (id)segmentedViewController:(id)arg1 titleAtIndex:(long long)arg2;
- (long long)numberOfEntriesForSegmentedViewController:(id)arg1;
- (id)followingViewController;
- (id)subscriptionsViewController;
- (id)superFollowersViewController;
- (id)followersViewController;
- (id)verifiedFollowersViewController;
- (id)initWithTab:(long long)arg1 userDataSource:(id)arg2 account:(id)arg3 showFollowersYouKnow:(_Bool)arg4 showPrimaryTabOnly:(_Bool)arg5 shouldHideCreatorSubscriptions:(_Bool)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

