//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class TFNAttributedTextView;
@protocol T1ProfileVerificationPolicyErrorViewDelegate;

@interface T1ProfileVerificationPolicyErrorView : UIView
{
    id <T1ProfileVerificationPolicyErrorViewDelegate> _delegate;
    TFNAttributedTextView *_errorTitleLabel;
    TFNAttributedTextView *_errorDescriptionLabel;
    UIView *_retryButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *retryButton; // @synthesize retryButton=_retryButton;
@property(retain, nonatomic) TFNAttributedTextView *errorDescriptionLabel; // @synthesize errorDescriptionLabel=_errorDescriptionLabel;
@property(retain, nonatomic) TFNAttributedTextView *errorTitleLabel; // @synthesize errorTitleLabel=_errorTitleLabel;
@property(nonatomic) __weak id <T1ProfileVerificationPolicyErrorViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_t1_didTapRetryButton:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

