//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface T1QuotedStandardStatusViewLayoutStateGenerator : NSObject
{
}

+ (id)_t1_customizeLayoutMetrics:(id)arg1 width:(double)arg2 viewModel:(id)arg3;
- (id)_t1_updateLayoutStateForDefaultQuoteTweetViewModel:(id)arg1 layoutState:(id)arg2 viewAdapterSet:(id)arg3 options:(unsigned long long)arg4 account:(id)arg5 width:(double)arg6 layoutMetrics:(id)arg7;
- (id)_t1_updateLayoutStateForMediaFirstMediumQuoteTweetViewModel:(id)arg1 layoutState:(id)arg2 viewAdapterSet:(id)arg3 options:(unsigned long long)arg4 account:(id)arg5 width:(double)arg6 layoutMetrics:(id)arg7;
- (id)layoutStateForViewModel:(id)arg1 options:(unsigned long long)arg2 account:(id)arg3 width:(double)arg4 layoutMetrics:(id)arg5 withPreviousLayoutState:(id)arg6;
- (id)layoutStateForViewModel:(id)arg1 options:(unsigned long long)arg2 account:(id)arg3 layoutMetrics:(id)arg4 withPreviousLayoutState:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

