//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSError, NSMutableArray, NSString, TFNTwitterAccount;
@protocol OS_dispatch_queue, TFNApplicationBackgroundTaskHandle;

@interface T1ReportProblem : NSObject
{
    NSObject<OS_dispatch_queue> *_gatherQueue;
    NSString *_zipFilePath;
    NSError *_zipFileError;
    NSMutableArray *_gatheringCompletionBlocks;
    NSMutableArray *_uploadCompletionBlocks;
    id <TFNApplicationBackgroundTaskHandle> _gatheringTaskHandle;
    id <TFNApplicationBackgroundTaskHandle> _uploadTaskHandle;
    _Bool _logsGathered;
    unsigned long long _uploadSize;
    TFNTwitterAccount *_account;
}

+ (void)uploadLogsWithData:(id)arg1 filePath:(id)arg2 contentType:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void).cxx_destruct;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(readonly, nonatomic) unsigned long long uploadSize; // @synthesize uploadSize=_uploadSize;
@property(readonly, nonatomic) _Bool logsGathered; // @synthesize logsGathered=_logsGathered;
- (void)_cleanup;
- (void)_background_didFinishGatheringLogsIntoZipFile;
- (void)_background_didFinishGatheringReport:(id)arg1;
- (void)dealloc;
- (id)initWithAccount:(id)arg1;
- (id)init;
- (void)bugReporter:(id)arg1 sendBugReport:(id)arg2 didCompleteWithResult:(long long)arg3;
- (void)bugReporter:(id)arg1 didTriggerBugReport:(id)arg2;
- (id)contextForBugReporter:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

