//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface T1SettingsViewControllers : NSObject
{
}

+ (id)navigationStackForDeeplinkStringWithLink:(id)arg1 account:(id)arg2 referringPage:(id)arg3;
+ (id)notificationsForAccount:(id)arg1;
+ (id)timelineForAccount:(id)arg1;
+ (id)rootViewControllerForAccount:(id)arg1;
- (id)init;

@end

