//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNComposableViewAdapter.h>

@class NSString, TFSTimer, TTACoreStatusLiveEngagementManager;
@protocol TTACoreStatusViewInlineActions;

@interface T1StandardStatusInlineActionsViewAdapter : TFNComposableViewAdapter
{
    TFSTimer *_updateStatusCountTimer;
    _Bool _shouldPauseLivePipelineUpdates;
    TTACoreStatusLiveEngagementManager *_livePipelineTweetManager;
    long long _displayType;
    long long _originDisplayType;
    CDUnknownBlockType _displayTextOptionsOverride;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType displayTextOptionsOverride; // @synthesize displayTextOptionsOverride=_displayTextOptionsOverride;
@property(nonatomic) long long originDisplayType; // @synthesize originDisplayType=_originDisplayType;
@property(readonly, nonatomic) long long displayType; // @synthesize displayType=_displayType;
@property(nonatomic) _Bool shouldPauseLivePipelineUpdates; // @synthesize shouldPauseLivePipelineUpdates=_shouldPauseLivePipelineUpdates;
@property(nonatomic) __weak TTACoreStatusLiveEngagementManager *livePipelineTweetManager; // @synthesize livePipelineTweetManager=_livePipelineTweetManager;
- (void)inlineActionsView:(id)arg1 didStartBrandedAnimationFromInlineActionWithType:(unsigned long long)arg2;
- (void)inlineActionsView:(id)arg1 didLongPressInlineActionWithType:(unsigned long long)arg2;
- (void)inlineActionsView:(id)arg1 didTapInlineActionWithType:(unsigned long long)arg2;
- (void)_t1_handleEventType:(id)arg1 forInlineActionsView:(id)arg2 withEventActionTypeValue:(id)arg3 inlineActionType:(unsigned long long)arg4;
- (void)_t1_updateAccessibilityForButtonType:(unsigned long long)arg1 label:(id)arg2 hint:(id)arg3 inlineActionsView:(id)arg4;
- (void)_t1_updateAccessibilityWithViewModel:(id)arg1 forView:(id)arg2;
- (_Bool)isLayoutState:(id)arg1 validForViewModel:(id)arg2 layoutMetrics:(id)arg3;
- (id)layoutStateForViewModel:(id)arg1 layoutMetrics:(id)arg2;
- (void)viewModel:(id)arg1 didUpdateWithInfo:(id)arg2 forView:(id)arg3;
- (void)unsetViewModelForView:(id)arg1;
- (_Bool)_t1_shouldShowShareInlineActionForViewModel:(id)arg1;
- (void)setViewModel:(id)arg1 forView:(id)arg2;
- (void)view:(id)arg1 willMoveToHostView:(id)arg2;
- (id)initializeView;
- (_Bool)shouldBeVisibleForViewModel:(id)arg1;
- (id)initWithViewIdentifier:(long long)arg1 displayType:(long long)arg2 originDisplayType:(long long)arg3;
- (void)_t1_invalidateUpdateStatusCountTimer;
- (void)_t1_updateViewModel:(id)arg1 statusCountForView:(id)arg2;
@property(readonly, nonatomic) id <TTACoreStatusViewInlineActions> inlineActions;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

