//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, T1StatusViewAttachmentContainerView, T1StatusViewCombinedViewModel, UIImage, UIView;
@protocol TVPPlayerSessionSource;

@interface T1StandardStatusAttachmentAutoplayViewContainer : NSObject
{
    T1StatusViewAttachmentContainerView *_attachmentContainerView;
    T1StatusViewCombinedViewModel *_viewModel;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIImage *playerPreviewImage;
@property(readonly, nonatomic) UIView *playerContainerView;
@property(readonly, nonatomic) id <TVPPlayerSessionSource> playerSessionSource;
- (id)initWithAttachmentContainerView:(id)arg1 viewModel:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

