//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNComposableViewAdapter.h>

@class MISSING_TYPE;

@interface T1StandardStatusPromotedLabelViewAdapter : TFNComposableViewAdapter
{
    MISSING_TYPE *imageSize;
    MISSING_TYPE *$__lazy_storage_$_promotedView;
    MISSING_TYPE *$__lazy_storage_$_promotedImageView;
    MISSING_TYPE *$__lazy_storage_$_promotedLabel;
}

- (void).cxx_destruct;
- (id)initWithViewIdentifier:(long long)arg1;
- (_Bool)isLayoutState:(id)arg1 validForViewModel:(id)arg2 layoutMetrics:(id)arg3;
- (id)layoutStateForViewModel:(id)arg1 layoutMetrics:(id)arg2;
- (id)initializeView;
- (_Bool)shouldBeVisibleForViewModel:(id)arg1;

@end

