//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNComposableViewAdapter.h>

@interface T1StandardStatusConversationTreeConnectorsViewAdapter : TFNComposableViewAdapter
{
}

- (_Bool)isLayoutState:(id)arg1 validForViewModel:(id)arg2 layoutMetrics:(id)arg3;
- (struct CGRect)avatarFrameForBodyLayoutOriginY:(double)arg1 viewModel:(id)arg2 layoutMetrics:(id)arg3;
- (id)layoutStateForViewModel:(id)arg1 layoutMetrics:(id)arg2 avatarFrame:(struct CGRect)arg3 containerHeight:(double)arg4 tweetStormIndicatorMidY:(double)arg5;
- (id)layoutStateForViewModel:(id)arg1 layoutMetrics:(id)arg2 avatarFrame:(struct CGRect)arg3 containerHeight:(double)arg4;
- (id)layoutStateForViewModel:(id)arg1 layoutMetrics:(id)arg2;
- (void)setLayoutState:(id)arg1 forView:(id)arg2;
- (void)setViewModel:(id)arg1 forView:(id)arg2;
- (id)initializeView;
- (_Bool)shouldBeVisibleForViewModel:(id)arg1;

@end

