//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/_TtP8TAPTweet19TAPTweetPerspective_-Protocol.h>

@class NSArray, NSDictionary, NSNumber, NSString, TFCCardData, TFNTwitterAccount, TFNTwitterUser, TFSTwitterCommunityMembership, TFSTwitterEntitySet, TFSTwitterMediaInfo, _TtC14TFSTwitterCore25TFSTwitterPromotedContent;

@protocol T1StatusActionItemsPerspective <_TtP8TAPTweet19TAPTweetPerspective_>
@property(readonly, nonatomic) _Bool isPromoted;
@property(readonly, nonatomic) NSString *twitterURLForCopy;
@property(readonly, nonatomic) NSString *statusIDString;
@property(readonly, nonatomic) NSNumber *statusIDNumber;
@property(readonly, nonatomic) long long statusID;
@property(readonly, nonatomic) NSDictionary *scribeParameters;
@property(readonly, nonatomic) NSString *scribeElementAccountingForQuoteTweet;
@property(readonly, copy, nonatomic) NSString *scribeComponent;
@property(readonly, nonatomic) NSArray *representedMediaEntities;
@property(readonly, nonatomic) TFCCardData *representedCardData;
@property(retain, nonatomic) _TtC14TFSTwitterCore25TFSTwitterPromotedContent *promotedContent;
@property(readonly, nonatomic) unsigned long long primaryMediaType;
@property(readonly, nonatomic) TFSTwitterMediaInfo *primaryMediaInfo;
@property(readonly, nonatomic) _Bool isSelfThreadStatus;
@property(readonly, nonatomic) _Bool isReply;
@property(readonly, nonatomic) _Bool isPrivateOrNonCompliant;
@property(readonly, nonatomic) _Bool isPoll;
@property(readonly, nonatomic) _Bool isLeaveConversationEnabled;
@property(readonly, nonatomic) _Bool isGIF;
@property(readonly, nonatomic) _Bool isLatestEdit;
@property(readonly, nonatomic) _Bool isEditable;
@property(readonly, nonatomic) long long editsRemaining;
@property(readonly, nonatomic) _Bool isInEditableTimeWindow;
@property(readonly, nonatomic) _Bool isAmplifyCardVideo;
@property(readonly, nonatomic) NSArray *inlineMediaInfos;
@property(readonly, nonatomic) NSString *fromUserName;
@property(retain, nonatomic) TFNTwitterUser *fromUser;
@property(readonly, nonatomic) TFSTwitterEntitySet *entities;
@property(nonatomic) long long draftTweetID;
@property(readonly, nonatomic) long long conversationID;
@property(readonly, nonatomic) TFSTwitterCommunityMembership *communityMembership;
- (_Bool)isPrerollContent;
- (_Bool)isFromUserUsernameless;
- (_Bool)isAdPreviewTweet;
- (_Bool)displaySensitiveContentAppealForAccount:(TFNTwitterAccount *)arg1;
@end

