//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface T1StatusViewPhotoLoadDurationStatusEventHandler : NSObject
{
    NSObject<OS_dispatch_queue> *_eventQueue;
}

+ (void)handleStatusViewEvent:(id)arg1 controller:(id)arg2;
- (void).cxx_destruct;
- (void)handleStatusViewEvent:(id)arg1 controller:(id)arg2;
- (id)init;

@end

