//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class NSArray, NSMutableDictionary, NSNumber, NSString, T1AppSplitViewController, T1DashContentController, T1DockedUploadBarController, T1TabCustomizationPanelPresentationHandler, T1TabNavigationController, T1TabbedAppNavigation, T1TabbedAppNavigationViewControllerActionContext, T1TabbedContainerViewController, TAFBottomOverlayWindow, TFNFloatingActionButton, TFNTabbedViewController, TFNToastWindow, TFNTwitterAccount, TFSTimer, UINavigationController;
@protocol T1AppNavigation, T1ExtendedContentNavigationControllerDataSource, T1TabbedAppNavigationDataSource, TASSpacesNavigatable;

@interface T1TabbedAppNavigationViewController : UIViewController
{
    _Bool _floatingActionButtonIsAvoidingOverlap;
    TFNTwitterAccount *_account;
    id <T1TabbedAppNavigationDataSource> _dataSource;
    T1TabbedAppNavigation *_tabbedAppNavigation;
    T1AppSplitViewController *_appSplitViewController;
    id <T1ExtendedContentNavigationControllerDataSource> _extendedContentDataSource;
    NSNumber *_lastScribedDisplayExtendedContent;
    T1TabbedContainerViewController *_tabbedContainerViewController;
    TFNTabbedViewController *_tabbedViewController;
    NSMutableDictionary *_transferTabViewControllers;
    TFSTimer *_unloadUnviewedTabsTimer;
    TFNToastWindow *_toastWindow;
    TAFBottomOverlayWindow *_bottomOverlayWindow;
    T1DashContentController *_dashContentController;
    T1TabCustomizationPanelPresentationHandler *_tabCustomizationPanelPresentationHandler;
    T1TabbedAppNavigationViewControllerActionContext *_currentActionContext;
    TFNFloatingActionButton *_floatingActionButton;
    T1DockedUploadBarController *_dockedUploadBarController;
    NSArray *_visibleTabEntries;
    id <TASSpacesNavigatable> _spacesNavigation;
    double _floatingActionButtonMargin;
    struct CGRect _floatingActionButtonDesiredFrame;
    struct UIEdgeInsets _floatingActionButtonMinimumInsets;
}

- (void).cxx_destruct;
@property(nonatomic) double floatingActionButtonMargin; // @synthesize floatingActionButtonMargin=_floatingActionButtonMargin;
@property(retain, nonatomic) id <TASSpacesNavigatable> spacesNavigation; // @synthesize spacesNavigation=_spacesNavigation;
@property(retain, nonatomic) NSArray *visibleTabEntries; // @synthesize visibleTabEntries=_visibleTabEntries;
@property(nonatomic) struct UIEdgeInsets floatingActionButtonMinimumInsets; // @synthesize floatingActionButtonMinimumInsets=_floatingActionButtonMinimumInsets;
@property(nonatomic) _Bool floatingActionButtonIsAvoidingOverlap; // @synthesize floatingActionButtonIsAvoidingOverlap=_floatingActionButtonIsAvoidingOverlap;
@property(nonatomic) struct CGRect floatingActionButtonDesiredFrame; // @synthesize floatingActionButtonDesiredFrame=_floatingActionButtonDesiredFrame;
@property(retain, nonatomic) T1DockedUploadBarController *dockedUploadBarController; // @synthesize dockedUploadBarController=_dockedUploadBarController;
@property(retain, nonatomic) TFNFloatingActionButton *floatingActionButton; // @synthesize floatingActionButton=_floatingActionButton;
@property(retain, nonatomic) T1TabbedAppNavigationViewControllerActionContext *currentActionContext; // @synthesize currentActionContext=_currentActionContext;
@property(readonly, nonatomic) T1TabCustomizationPanelPresentationHandler *tabCustomizationPanelPresentationHandler; // @synthesize tabCustomizationPanelPresentationHandler=_tabCustomizationPanelPresentationHandler;
@property(readonly, nonatomic) T1DashContentController *dashContentController; // @synthesize dashContentController=_dashContentController;
@property(readonly, nonatomic) TAFBottomOverlayWindow *bottomOverlayWindow; // @synthesize bottomOverlayWindow=_bottomOverlayWindow;
@property(readonly, nonatomic) TFNToastWindow *toastWindow; // @synthesize toastWindow=_toastWindow;
@property(readonly, nonatomic) TFSTimer *unloadUnviewedTabsTimer; // @synthesize unloadUnviewedTabsTimer=_unloadUnviewedTabsTimer;
@property(readonly, nonatomic) NSMutableDictionary *transferTabViewControllers; // @synthesize transferTabViewControllers=_transferTabViewControllers;
@property(readonly, nonatomic) TFNTabbedViewController *tabbedViewController; // @synthesize tabbedViewController=_tabbedViewController;
@property(readonly, nonatomic) T1TabbedContainerViewController *tabbedContainerViewController; // @synthesize tabbedContainerViewController=_tabbedContainerViewController;
@property(readonly, nonatomic) NSNumber *lastScribedDisplayExtendedContent; // @synthesize lastScribedDisplayExtendedContent=_lastScribedDisplayExtendedContent;
@property(readonly, nonatomic) id <T1ExtendedContentNavigationControllerDataSource> extendedContentDataSource; // @synthesize extendedContentDataSource=_extendedContentDataSource;
@property(readonly, nonatomic) T1AppSplitViewController *appSplitViewController; // @synthesize appSplitViewController=_appSplitViewController;
@property(readonly, nonatomic) T1TabbedAppNavigation *tabbedAppNavigation; // @synthesize tabbedAppNavigation=_tabbedAppNavigation;
@property(readonly, nonatomic) id <T1TabbedAppNavigationDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (_Bool)_t1_showCreateSpaceTutorial;
- (void)viewControllerViewWillFullyDisappear:(id)arg1;
- (void)viewControllerViewWillFullyAppear:(id)arg1;
- (void)dropInteraction:(id)arg1 sessionDidEnter:(id)arg2;
- (_Bool)dropInteraction:(id)arg1 canHandleSession:(id)arg2;
- (void)_t1_updateComposeItemDropInteraction;
- (void)_t1_updateFloatingActionButtonAdditionalEdgeInsets;
- (_Bool)_t1_layoutFloatingActionButton;
- (void)_t1_handleActionButtonStatusChangedNotification:(id)arg1;
- (void)_t1_updateContentVisibleSafeAreaOffsetsForFloatingActionButton;
- (void)_t1_configureActionButtonForContext:(id)arg1 animated:(_Bool)arg2;
- (void)_t1_configureActionForViewController:(id)arg1 forcibly:(_Bool)arg2 animated:(_Bool)arg3;
- (_Bool)_t1_updateFloatingActionButtonPositionWithDockedViewFrame:(struct CGRect)arg1 finalPosition:(struct CGPoint)arg2;
- (struct CGRect)_t1_floatingActionButtonFrame;
- (double)_t1_floatingActionButtonHeight;
- (void)_t1_setUpFloatingActionButton;
- (void)_t1_accountFeatureSwitchesDidUpdate:(id)arg1;
- (void)_t1_prepromptPresentationCompletionScribe:(id)arg1 withResult:(long long)arg2 forServiceType:(long long)arg3;
- (void)_t1_showBackstopPermissionPromptsIfNecessary;
- (void)_t1_unloadTabs;
- (void)_t1_syncTabBarSelectionWithSelectedController;
- (void)_t1_syncControllerSelectionWithTabBarDueToUserInteraction:(_Bool)arg1;
- (void)_t1_didEndDisplayingNavigationController:(id)arg1;
- (long long)_t1_visibleIndexForPanel:(long long)arg1;
- (_Bool)_t1_getPanelID:(long long *)arg1 viewControllers:(id *)arg2 movedToNavigationController:(id)arg3;
- (void)_t1_didMoveViewControllers:(id)arg1 fromPanelID:(long long)arg2;
- (void)_t1_updateTabViewControllers;
- (void)_t1_updateTabContent;
- (void)_t1_initializeTabContent;
- (void)_t1_dockingControllerDidDismissCurrentDockedView;
- (void)_t1_dockingControllerDidDockView;
- (void)dockingControllerDockedViewDragEnded:(id)arg1;
- (void)dockingControllerDockedViewDragUpdated:(id)arg1;
- (void)dockingControllerDockedViewDragBegan:(id)arg1;
- (void)tfn_addDirectlyOwnedViewControllersToMutableArray:(id)arg1;
- (void)_t1_scribeDisplayExtendedContent;
- (id)scribeContext;
- (id)scribePage;
- (id)scribe;
- (void)_t1_displaySettingsDidChange;
- (void)_applicationWillEnterForeground:(id)arg1;
- (void)tabBarViewController:(id)arg1 didUpdateAlpha:(double)arg2;
- (_Bool)tabBarViewController:(id)arg1 gestureRecognizer:(id)arg2 shouldRequireFailureOfGestureRecognizer:(id)arg3;
- (_Bool)shouldShowProgressBarForTabBarViewController:(id)arg1;
- (void)tabBarViewController:(id)arg1 longPressOnTabAtIndex:(long long)arg2 withView:(id)arg3;
- (void)tabBarViewController:(id)arg1 selectTabAtIndex:(long long)arg2 withView:(id)arg3;
- (_Bool)tabBarViewController:(id)arg1 selectTabRequiresLongPressFailureForTabAtIndex:(long long)arg2 withView:(id)arg3;
- (id)t1_tabBarIntegration;
- (void)tabbedViewController:(id)arg1 didSelectViewControllerAtIndex:(long long)arg2;
- (void)_t1_updateDashBarButtonItemForTabNavigationController:(id)arg1;
- (id)tabbedViewController:(id)arg1 viewControllerAtIndex:(long long)arg2;
- (long long)numberOfViewControllersInTabbedViewController:(id)arg1;
- (_Bool)appSplitViewController:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)appSplitViewController:(id)arg1 canPresentDashFromViewController:(id)arg2;
- (id)contentPresentingViewControllerForAppSplitViewController:(id)arg1;
- (id)panelPresentingViewControllerForAppSplitViewController:(id)arg1;
- (void)appSplitViewControllerDashPanelOpenPercentDidChange:(id)arg1;
- (void)appSplitViewControllerExtendedContentAvailableDidChange:(id)arg1;
- (void)appSplitViewController:(id)arg1 splitModeDidChange:(long long)arg2;
@property(readonly, nonatomic, getter=isDashOpen) _Bool dashOpen;
- (void)dismissDashAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentDashFromViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)tabbedContainerViewControllerView:(id)arg1 didChangeViewDockedBarsSafeAreaInsets:(struct UIEdgeInsets)arg2;
- (void)_t1_updateToastWindowSize;
- (void)_t1_tearDownToasts;
- (void)_t1_setUpToasts;
- (void)recalculateVisiblePanels;
- (id)appSplitViewControllerForAppNavigation:(id)arg1;
- (id)presentationViewControllerForAppNavigation:(id)arg1;
- (void)appNavigation:(id)arg1 setCurrentPanel:(long long)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (id)visiblePanelIDsForAppNavigation:(id)arg1;
- (long long)currentPanelIDForAppNavigation:(id)arg1;
- (id)currentPanelNavigationControllerForAppNavigation:(id)arg1;
@property(readonly, nonatomic) id <T1AppNavigation> appNavigation;
- (void)layoutMetricsDidChange:(id)arg1 to:(id)arg2;
- (void)willMoveToParentViewController:(id)arg1;
- (unsigned long long)tfn_supportedInterfaceOrientations;
- (id)childViewControllerForStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (id)childViewControllerForStatusBarStyle;
- (void)traitCollectionDidChange:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)_t1_main_handleMarchMadnessLaunchIfNeeded;
- (void)viewDidLoad;
- (_Bool)accessibilityPerformMagicTap;
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;
- (void)openAboutTwitterCommand;
- (void)handleSearchKeyCommand;
- (_Bool)_t1_canHandleSearchKeyCommand;
- (void)_t1_handlePanelKeyCommand:(long long)arg1;
- (void)handleChatPanelKeyCommand;
- (void)handleNewsPanelKeyCommand;
- (void)handleAccountAnalyticsPanelKeyCommand;
- (void)handleOfflineCachePanelKeyCommand;
- (void)handlePaymentsPanelKeyCommand;
- (void)handleJobsPanelKeyCommand;
- (void)handleConferencesPanelKeyCommand;
- (void)handlePremiumHubPanelKeyCommand;
- (void)handleMediaPanelKeyCommand;
- (void)handleGrokPanelKeyCommand;
- (void)handleBirdwatchPanelKeyCommand;
- (void)handleCreatorPanelKeyCommand;
- (void)handleVoicePanelKeyCommand;
- (void)handleTopArticlesPanelKeyCommand;
- (void)handleCommunitiesPanelKeyCommand;
- (void)handleProfilePanelKeyCommand;
- (void)handleListsPanelKeyCommand;
- (void)handleBookmarksPanelKeyCommand;
- (void)handleDMsPanelKeyCommand;
- (void)handleConnectPanelKeyCommand;
- (void)handleMomentsPanelKeyCommand;
- (void)handleHomePanelKeyCommand;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)keyCommands;
- (_Bool)becomeFirstResponder;
- (_Bool)canBecomeFirstResponder;
@property(readonly, nonatomic) UINavigationController *visibleExtendedContentNavigationController;
@property(readonly, nonatomic) T1TabNavigationController *currentTabNavigationController;
@property(readonly, nonatomic) long long selectedIndex;
- (id)initWithAccount:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(readonly, nonatomic) struct CGRect timelineFrameInWindow;
- (void)graduatedAccessUserPrompt:(id)arg1 didTapLearnMoreURL:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

