//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface T1TabCustomizationConfig : NSObject
{
    MISSING_TYPE *migrationHelper;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) _Bool isTabCustomizationEnabled;
- (id)initWithAccount:(id)arg1;

@end

