//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNTableViewCell.h>

@class T1TextSizeSliderView;

@interface T1TextSizeSliderCell : TFNTableViewCell
{
    T1TextSizeSliderView *_textSizeSliderView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) T1TextSizeSliderView *textSizeSliderView; // @synthesize textSizeSliderView=_textSizeSliderView;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

