//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface T1TFNUIScribeConstants : NSObject
{
}

@property(readonly, nonatomic) NSString *actionOpen;
@property(readonly, nonatomic) NSString *actionImpression;
@property(readonly, nonatomic) NSString *actionDropped;
@property(readonly, nonatomic) NSString *actionClick;
@property(readonly, nonatomic) NSString *actionCancel;
@property(readonly, nonatomic) NSString *componentSystem;
@property(readonly, nonatomic) NSString *componentSocial;
@property(readonly, nonatomic) NSString *sectionToasts;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

