//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol TFSTwitterLegacyScribeLogMethods;

@interface T1TFNUIScribeSink : NSObject
{
    id <TFSTwitterLegacyScribeLogMethods> _scribe;
}

- (void).cxx_destruct;
- (void)receivedActionWithSender:(id)arg1 action:(id)arg2;
- (void)receiveAction:(id)arg1 withContext:(id)arg2;
- (id)initWithScribe:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

