//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class T1TipJarSettingsViewController;

@protocol T1TipJarSettingsViewControllerDelegate <NSObject>
- (void)tipJarSettingsViewControllerShowTipsPrompt:(T1TipJarSettingsViewController *)arg1;
- (void)tipJarSettingsViewController:(T1TipJarSettingsViewController *)arg1 didUpdateEnabled:(_Bool)arg2;
@end

