//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterAppSPMMigration/TUCLayoutableView.h>

@class MISSING_TYPE, TIPImagePipeline, TUCUnifiedCard, UIView;
@protocol TUCComponentModel, TUCComponentViewEventDelegate;

@interface T1UnifiedCardCommerceDropComponentView : TUCLayoutableView
{
    MISSING_TYPE *unifiedCard;
    MISSING_TYPE *component;
    MISSING_TYPE *eventDelegate;
    MISSING_TYPE *imagePipeline;
    MISSING_TYPE *autoplayableContainerView;
    MISSING_TYPE *viewModelObserver;
    MISSING_TYPE *account;
    MISSING_TYPE *scribeContext;
    MISSING_TYPE *$__lazy_storage_$_api;
    MISSING_TYPE *viewModel;
    MISSING_TYPE *$__lazy_storage_$_backgroundHighlightView;
    MISSING_TYPE *$__lazy_storage_$_backgroundView;
    MISSING_TYPE *$__lazy_storage_$_backgroundGradientView;
    MISSING_TYPE *cachedDominantColor;
    MISSING_TYPE *$__lazy_storage_$_countdownView;
    MISSING_TYPE *$__lazy_storage_$_dropLabel;
    MISSING_TYPE *$__lazy_storage_$_nameLabel;
    MISSING_TYPE *$__lazy_storage_$_dateLabel;
    MISSING_TYPE *$__lazy_storage_$_subscriberInfoLabel;
    MISSING_TYPE *$__lazy_storage_$_dateIconView;
    MISSING_TYPE *$__lazy_storage_$_primaryButton;
    MISSING_TYPE *userAttributionView;
}

+ (id)sharedLayoutDelegate;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)accessibilityCustomUCActions;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithAccount:(id)arg1 scribeContext:(id)arg2;
@property(nonatomic, retain) UIView *autoplayableContainerView; // @synthesize autoplayableContainerView;
@property(nonatomic, retain) TIPImagePipeline *imagePipeline; // @synthesize imagePipeline;
@property(nonatomic) __weak id <TUCComponentViewEventDelegate> eventDelegate; // @synthesize eventDelegate;
@property(nonatomic, retain) id <TUCComponentModel> component; // @synthesize component;
@property(nonatomic, retain) TUCUnifiedCard *unifiedCard; // @synthesize unifiedCard;
- (id)updatedScribeContextForComponentViewEvent:(id)arg1 sourceScribeContext:(id)arg2;
- (id)supplementalParamsForEvent:(id)arg1;
- (void)prepareForReuse;
- (_Bool)handlesTouchHighlighting;
- (void)setupActions;
- (void)t1_didTapPrimaryButton;
- (void)t1_didTap;

@end

