//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSArray, NSString, NSValue, T1AdFormatsFeatures, TFNLayoutableView, TFNTwitterAccount, TIPImagePipeline, TUCLayoutContext, TUCUnifiedCard, TUCViewLayoutState;
@protocol TUCComponentContainerView, TUCComponentViewEventDelegate, TUCViewRegistryProtocol;

@interface T1UnifiedCardView : UIView
{
    TFNTwitterAccount *_account;
    _Bool _dataSaverEnabled;
    TUCViewLayoutState *_layoutState;
    TUCUnifiedCard *_unifiedCard;
    TFNLayoutableView<TUCComponentContainerView> *_containerView;
    id <TUCViewRegistryProtocol> _viewRegistry;
    TIPImagePipeline *_imagePipeline;
    id <TUCComponentViewEventDelegate> _eventDelegate;
    UIView *_proxyHighlightView;
    TUCLayoutContext *_layoutContext;
    TUCViewLayoutState *_ucLayoutState;
    NSValue *_touchPointValue;
    UIView *_footerView;
    T1AdFormatsFeatures *_adFormatsFeatures;
}

- (void).cxx_destruct;
@property(retain, nonatomic) T1AdFormatsFeatures *adFormatsFeatures; // @synthesize adFormatsFeatures=_adFormatsFeatures;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) NSValue *touchPointValue; // @synthesize touchPointValue=_touchPointValue;
@property(retain, nonatomic) TUCViewLayoutState *ucLayoutState; // @synthesize ucLayoutState=_ucLayoutState;
@property(nonatomic, getter=isDataSaverEnabled) _Bool dataSaverEnabled; // @synthesize dataSaverEnabled=_dataSaverEnabled;
@property(retain, nonatomic) TUCLayoutContext *layoutContext; // @synthesize layoutContext=_layoutContext;
@property(readonly, nonatomic) UIView *proxyHighlightView; // @synthesize proxyHighlightView=_proxyHighlightView;
@property(nonatomic) __weak id <TUCComponentViewEventDelegate> eventDelegate; // @synthesize eventDelegate=_eventDelegate;
@property(retain, nonatomic) TIPImagePipeline *imagePipeline; // @synthesize imagePipeline=_imagePipeline;
@property(retain, nonatomic) id <TUCViewRegistryProtocol> viewRegistry; // @synthesize viewRegistry=_viewRegistry;
@property(readonly, nonatomic) TFNLayoutableView<TUCComponentContainerView> *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) TUCUnifiedCard *unifiedCard; // @synthesize unifiedCard=_unifiedCard;
- (void)_t1_updateContainerViewAndReuseComponentViews:(_Bool)arg1;
- (id)previewConfigurationForLocation:(struct CGPoint)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)injectViewControllerForCarousel:(id)arg1;
- (id)filterComponentViewsByClass:(Class)arg1;
@property(readonly, nonatomic) NSArray *allComponentViews;
- (_Bool)openURL;
@property(readonly, nonatomic) _Bool hasURL;
@property(readonly, nonatomic) UIView *autoplayableContainerView;
@property(nonatomic) _Bool hideBorder;
@property(retain, nonatomic) TUCViewLayoutState *layoutState; // @synthesize layoutState=_layoutState;
- (void)setUnifiedCard:(id)arg1 viewRegistry:(id)arg2;
- (id)accessibilityCustomUCActions;
- (id)accessibilityLabel;
- (id)componentViewAtPoint:(struct CGPoint)arg1;
- (void)prepareForReuse;
- (id)initWithAccount:(id)arg1;
- (void)unifiedCardVanityViewDidTapCTAButton:(id)arg1;
- (void)statusPhotoVideoDetailsViewDidTapView:(id)arg1;
- (id)containerView:(id)arg1 didFireViewEvent:(id)arg2;
- (id)componentView:(id)arg1 didFireViewEvent:(id)arg2;
- (void)handleTweetConversationAdClickOnStatusCell;
- (void)handleTweetConversationAdClickOnStatusCell_deprecated;
- (void)handleTweetDetailsOpportunitySizingClickOnStatusCell;
- (id)oneBasedIndexOfCurrentCarouselItem;
- (id)swipeableMediaComponentView;
- (id)carouselViewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

