//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIImageView.h>

@class NSString, UIImage;
@protocol TUCImageViewLoadDelegate;

@interface T1UnifiedCardImageView : UIImageView
{
    id <TUCImageViewLoadDelegate> _loadDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <TUCImageViewLoadDelegate> loadDelegate; // @synthesize loadDelegate=_loadDelegate;
- (void)reset;
- (id)tui_fetchHelper;
- (void)setImageWithMediaEntity:(id)arg1 imagePipeline:(id)arg2;
- (void)tui_fetchHelper:(id)arg1 readyToConfigureView:(id)arg2 state:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) UIImage *image;
@property(readonly) Class superclass;

@end

