//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface T1URTConnectViewControllerFactory : NSObject
{
}

+ (id)viewControllerForAccount:(id)arg1 pivotParameters:(id)arg2 sourceViewController:(id)arg3 isCreatorOnly:(_Bool)arg4;
- (id)init;

@end

