//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface T1UserRecommendationViewLayoutDelegate : NSObject
{
}

+ (id)sharedLayoutDelegate;
- (void)layoutSubviewsForLayoutableView:(id)arg1;
- (double)_t1_maxYForLayoutState:(id)arg1;
- (double)_t1_layoutBio:(id)arg1 user:(id)arg2 width:(double)arg3 yCoordinate:(double)arg4;
- (double)_t1_layoutAuthor:(id)arg1 user:(id)arg2 userBadger:(id)arg3 followControlSize:(struct CGSize)arg4 width:(double)arg5 yCoordinate:(double)arg6;
- (double)_t1_layoutFollowControl:(id)arg1 followControlSize:(struct CGSize)arg2 width:(double)arg3 yCoordinate:(double)arg4;
- (double)_t1_layoutAvatar:(id)arg1 bannerViewMaxY:(double)arg2 followControlHeight:(double)arg3 account:(id)arg4;
- (double)_t1_layoutBannerImage:(id)arg1 width:(double)arg2 mediaViewMaxY:(double)arg3;
- (double)_t1_mediaView:(id)arg1 width:(double)arg2 mediaViewHeight:(double)arg3;
- (id)_t1_performLayoutForViewModel:(id)arg1 account:(id)arg2 width:(double)arg3 mediaViewSize:(struct CGSize)arg4;
- (_Bool)_t1_layoutState:(id)arg1 isValidForViewModel:(id)arg2 account:(id)arg3 width:(double)arg4 mediaViewSize:(struct CGSize)arg5;
- (id)layoutForViewModel:(id)arg1 account:(id)arg2 width:(double)arg3 mediaViewSize:(struct CGSize)arg4 withPreviousLayoutState:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

