//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSString, T1VoiceRoomUserPrivateEmojisView;

@protocol T1VoiceRoomUserPrivateEmojisViewDelegate <NSObject>
- (void)voiceRoomUserPrivateEmojisView:(T1VoiceRoomUserPrivateEmojisView *)arg1 didTapEmoji:(NSString *)arg2;
@end

