//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNViewController.h>

@class MISSING_TYPE;

@interface T1VoiceRoomScheduleDetailsViewController : TFNViewController
{
    MISSING_TYPE *viewModel;
    MISSING_TYPE *hasAddedActions;
    MISSING_TYPE *$__lazy_storage_$_shouldShowStartNowButton;
    MISSING_TYPE *$__lazy_storage_$_eventStore;
    MISSING_TYPE *$__lazy_storage_$_cardEventHandler;
    MISSING_TYPE *$__lazy_storage_$_googleCalendarURL;
    MISSING_TYPE *$__lazy_storage_$_hasValidGoogleCalendarURL;
    MISSING_TYPE *$__lazy_storage_$_closeBarButtonItem;
    MISSING_TYPE *cardTopConstraint;
    MISSING_TYPE *$__lazy_storage_$_spaceCard;
    MISSING_TYPE *actionsTopConstraint;
    MISSING_TYPE *$__lazy_storage_$_startNowButton;
    MISSING_TYPE *$__lazy_storage_$_shareButton;
    MISSING_TYPE *$__lazy_storage_$_editButton;
    MISSING_TYPE *$__lazy_storage_$_cancelButton;
    MISSING_TYPE *$__lazy_storage_$_reminderButton;
    MISSING_TYPE *$__lazy_storage_$_calendarButton;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)scribeParameters;
- (id)scribeComponent;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (void)didTapRemindWithSender:(id)arg1;
- (void)didTapCancel;
- (void)didTapShare;
- (void)didTapAppleCalendarItem;
- (void)didTapGoogleCalendarItem;
- (void)didTapAddToCalendar;
- (void)didTapEdit;
- (void)didTapStartNow;
- (void)didTapClose;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithViewModel:(id)arg1;
- (void)spaceModel:(id)arg1 didChangeSubscriptionState:(_Bool)arg2;
- (void)spaceModel:(id)arg1 didUpdateLoggedInUserModel:(id)arg2;
- (double)preferredHeightForModalSheetViewController:(id)arg1 modalContentViewVisibleEdgeInsets:(struct UIEdgeInsets)arg2;
- (void)cardView:(id)arg1 didUpdateContentAnimated:(_Bool)arg2;
- (id)cardView:(id)arg1 didFireViewEvent:(id)arg2;
- (id)layoutMetricsForCardView:(id)arg1;
- (void)eventEditViewController:(id)arg1 didCompleteWithAction:(long long)arg2;

@end

