//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNGenericItem.h>

@interface TFNGenericItem (ProfileCalloutDivider)
+ (id)profileDividerWithTitle:(id)arg1 font:(id)arg2 lineBreakMode:(long long)arg3 multipleLines:(_Bool)arg4 dismissBlock:(CDUnknownBlockType)arg5 selectionStyle:(long long)arg6;
@end

