//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSArray, NSString, TFNPickerViewController;
@protocol TFNPickableValue;

@protocol TFNPickerViewControllerDelegate <NSObject>

@optional
- (void)pickerViewControllerWillShowMoreValues:(TFNPickerViewController *)arg1;
- (void)pickerViewController:(TFNPickerViewController *)arg1 didReorderValue:(id <TFNPickableValue>)arg2 fromPosition:(unsigned long long)arg3 toPosition:(unsigned long long)arg4 inSectionAtIndex:(unsigned long long)arg5;
- (void)pickerViewController:(TFNPickerViewController *)arg1 didSelectValueForEditing:(id <TFNPickableValue>)arg2;
- (void)pickerViewController:(TFNPickerViewController *)arg1 didRemoveValue:(id <TFNPickableValue>)arg2 fromSectionAtIndex:(unsigned long long)arg3;
- (_Bool)pickerViewController:(TFNPickerViewController *)arg1 shouldRemoveValue:(id <TFNPickableValue>)arg2 fromSectionAtIndex:(unsigned long long)arg3;
- (void)pickerViewController:(TFNPickerViewController *)arg1 willAddValueToSectionAtIndex:(unsigned long long)arg2 withAddValueMessage:(NSString *)arg3 index:(unsigned long long)arg4 sender:(id)arg5;
- (void)pickerViewController:(TFNPickerViewController *)arg1 didDeselectValue:(id <TFNPickableValue>)arg2 inSectionAtIndex:(unsigned long long)arg3 willConfirm:(_Bool)arg4 willDismiss:(_Bool)arg5;
- (void)pickerViewController:(TFNPickerViewController *)arg1 didPickValue:(id <TFNPickableValue>)arg2 inSectionAtIndex:(unsigned long long)arg3 willConfirm:(_Bool)arg4 willDismiss:(_Bool)arg5;
- (void)pickerViewController:(TFNPickerViewController *)arg1 didConfirmWithSections:(NSArray *)arg2;
- (void)pickerViewControllerDidCancel:(TFNPickerViewController *)arg1;
- (void)pickerViewControllerDidDismiss:(TFNPickerViewController *)arg1;
@end

