//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class TFNTwitterAccount;

@protocol TFNTwitterTimelineManagerProtocol <NSObject>
- (void)accountDidBecomeActive;
- (void)refreshHomeTimelineWithSource:(long long)arg1;
- (id)initWithAccount:(TFNTwitterAccount *)arg1;
@end

