//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/_TtP8TAPTweet19TAPTweetPerspective_-Protocol.h>

@class NSDictionary, NSNumber, NSString, _TtC14TFSTwitterCore25TFSTwitterPromotedContent;

@protocol TFNTwitterUserTweetPerspective <_TtP8TAPTweet19TAPTweetPerspective_>
@property(readonly, nonatomic) NSNumber *statusIDNumber;
@property(readonly, nonatomic) long long statusID;
@property(readonly, copy, nonatomic) NSDictionary *scribeItem;
@property(readonly, copy, nonatomic) NSString *scribeComponent;
@property(retain, nonatomic) _TtC14TFSTwitterCore25TFSTwitterPromotedContent *promotedContent;
@end

