//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSString;

@protocol TGFLogger <NSObject>
- (void)tgf_logWithLevel:(long long)arg1 file:(NSString *)arg2 function:(NSString *)arg3 line:(int)arg4 message:(NSString *)arg5;

@optional
- (_Bool)tgf_canLogWithLevel:(long long)arg1;
@end

