//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSNumber, NSString;

@protocol TSCShareable
@property(nonatomic, readonly) _Bool isPrivateOrNonCompliant;
@property(nonatomic, readonly) NSString *scribeElement;
@property(nonatomic, readonly) NSString *scribeComponent;
@property(nonatomic, readonly) NSNumber *scribeParameterID;
@end

