//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIView;
@protocol TUIVoiceDockableContent;

@protocol TUIVoiceDockContainer
@property(retain, nonatomic) UIView<TUIVoiceDockableContent> *contentView;
- (void)voiceDockContentDidInvalidateSize:(UIView<TUIVoiceDockableContent> *)arg1;
@end

