//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtCC23TwitterDirectMessagesUIP33_AC04BCB947934C25D59BC6EF987EB26C43RequestsPromptSheetInfoSheetInfoItemAdapter27RequestsPromptSheetInfoItem : NSObject
{
    MISSING_TYPE *imageName;
    MISSING_TYPE *activeTextItem;
    MISSING_TYPE *image;
}

- (void).cxx_destruct;
- (id)init;

@end

