//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC13DMEditMembers41EditMembersSuggestionsListUserCellBuilder : _TtCs12_SwiftObject
{
    MISSING_TYPE *avatarViewModelBuilder;
    MISSING_TYPE *editMembersPendingGroupStream;
    MISSING_TYPE *editMembersStateStream;
    MISSING_TYPE *editMembersSuggestionsStream;
    MISSING_TYPE *userBadgesImageBuilder;
}

@end

