//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE, TFNLongPressGestureRecognizer, TFNTapGestureRecognizer, TFNTouchDownGestureRecognizer;

@interface _TtC14TwitterUISwift25GroupCountAvatarImageView : UIView
{
    MISSING_TYPE *$__lazy_storage_$_tappableHelper;
    MISSING_TYPE *groupCountView;
    MISSING_TYPE *groupCountState;
    MISSING_TYPE *avatarView;
    MISSING_TYPE *touchInsets;
    MISSING_TYPE *isPressed;
}

- (void).cxx_destruct;
- (void)layoutMetricsDidChange:(id)arg1 to:(id)arg2;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool pressed; // @synthesize pressed=isPressed;
- (_Bool)isPressed;
@property(nonatomic) struct UIEdgeInsets touchInsets; // @synthesize touchInsets;
@property(nonatomic) _Bool isAccessibilityElement;
@property(nonatomic, readonly) TFNTouchDownGestureRecognizer *touchDownGestureRecognizer;
@property(nonatomic, readonly) TFNLongPressGestureRecognizer *longPressGestureRecognizer;
@property(nonatomic, readonly) TFNTapGestureRecognizer *doubleTapGestureRecognizer;
@property(nonatomic, readonly) TFNTapGestureRecognizer *tapGestureRecognizer;
- (void)setPressedStateDidChangeTarget:(id)arg1 action:(SEL)arg2;
- (void)performLongPressAction;
- (void)setLongPressTarget:(id)arg1 action:(SEL)arg2;
- (void)performDoubleTapAction;
- (void)setDoubleTapTarget:(id)arg1 action:(SEL)arg2;
- (void)performTapAction;
- (void)setTapTarget:(id)arg1 action:(SEL)arg2;
@property(nonatomic, copy) CDUnknownBlockType tapActionBlock;

@end

