//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC14TwitterUISwift27StandardStatusEducationView : UIView
{
    MISSING_TYPE *cornerRadius;
    MISSING_TYPE *educationTextView;
    MISSING_TYPE *tapLinkHandler;
    MISSING_TYPE *tapEducationViewHandler;
    MISSING_TYPE *$__lazy_storage_$_tapGestureRecognizer;
    MISSING_TYPE *badgeImageView;
    MISSING_TYPE *badgeFrame;
}

+ (struct CGSize)sizeThatFits:(double)arg1 badgeFrame:(struct CGRect)arg2 attributedText:(id)arg3;
- (void).cxx_destruct;
- (void)attributedTextView:(id)arg1 didTapRange:(id)arg2 rect:(struct CGRect)arg3;
- (void)didTapEducationView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1 textColor:(id)arg2;
@property(nonatomic) struct CGRect badgeFrame; // @synthesize badgeFrame;

@end

