//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNItemsDataViewAdapter.h>

@class MISSING_TYPE;

@interface _TtC23TwitterProfileModulesUIP33_3E2FC5B2B870D271EF97A3D3BC3DAAF613ModuleAdapter : TFNItemsDataViewAdapter
{
    MISSING_TYPE *switchHandler;
    MISSING_TYPE *modulesSettingsDataSource;
    MISSING_TYPE *toggleAction;
    MISSING_TYPE *profileModulesContext;
}

- (void).cxx_destruct;
- (id)init;
- (double)dataViewController:(id)arg1 tableViewHeightForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;

@end

