//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC15TwitterShareKit10ActionRank : _TtCs12_SwiftObject
{
    MISSING_TYPE *predefinedBaseRank;
    MISSING_TYPE *account;
    MISSING_TYPE *predefinedRank;
    MISSING_TYPE *type;
    MISSING_TYPE *observer;
    MISSING_TYPE *actionLog;
}

@end

