//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC14DMConversation30TypingIndicatorCellContentView : UIView
{
    MISSING_TYPE *avatarState;
    MISSING_TYPE *bubbleView;
    MISSING_TYPE *leadingView;
    MISSING_TYPE *stackView;
}

- (void).cxx_destruct;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

