//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSNumber, NSString;

@interface _TtC26TwitterHomePinnedTimelines23PinnedTimelineDataModel : NSObject
{
    MISSING_TYPE *identifier;
    MISSING_TYPE *displayName;
    MISSING_TYPE *timeline;
    MISSING_TYPE *bannerUrl;
}

- (void).cxx_destruct;
- (id)init;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic, readonly) NSString *displayName;
@property(nonatomic, copy) NSString *identifier;
- (void)sortByRecency;
- (void)sortByLikes;
- (void)sortByRelevancy;
@property(nonatomic, readonly) _Bool isSortedByRecency;
@property(nonatomic, readonly) _Bool isSortedByLikes;
@property(nonatomic, readonly) _Bool isSortedByRelevancy;
@property(nonatomic, readonly) _Bool isSortableTimeline;
@property(nonatomic, readonly) NSNumber *listID;
@property(nonatomic, readonly) NSString *communityID;

@end

