//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNActiveTextItemTableRowAdapter.h>

@interface _TtC20TwitterSubscriptionsP33_51A86EA325C87D194FEB6794F2D0748841SubscriptionActiveTextItemTableRowAdapter : TFNActiveTextItemTableRowAdapter
{
}

- (id)init;
- (id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;

@end

