//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIPopoverBackgroundView.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC23TwitterDirectMessagesUI43DirectMessageReactionsPopoverBackgroundView : UIPopoverBackgroundView
{
    MISSING_TYPE *_arrowDirection;
    MISSING_TYPE *_arrowOffset;
}

+ (_Bool)wantsDefaultContentAppearance;
+ (double)arrowHeight;
+ (double)arrowBase;
+ (struct UIEdgeInsets)contentViewInsets;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) unsigned long long arrowDirection;
@property(nonatomic) double arrowOffset;

@end

