//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIStackView.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC20TwitterCommunitiesUI17CommunityRuleView : UIStackView
{
    MISSING_TYPE *ruleViewModel;
    MISSING_TYPE *$__lazy_storage_$_detailView;
    MISSING_TYPE *ordinalNumberView;
    MISSING_TYPE *$__lazy_storage_$_nameLabel;
    MISSING_TYPE *$__lazy_storage_$_descriptionLabel;
    MISSING_TYPE *accessoryView;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

