//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE, NSString;

__attribute__((visibility("hidden")))
@interface _TtC14DMConversation11URLCardView : UIView
{
    MISSING_TYPE *viewModel;
    MISSING_TYPE *contentView;
}

- (void).cxx_destruct;
@property(nonatomic, copy) NSString *accessibilityLabel;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

