//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC11ExpandedBio24ExpandedBioFeatureAccess : NSObject
{
    MISSING_TYPE *featureSwitches;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithFeatureSwitches:(id)arg1;

@end

