//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtCO21TwitterUnifiedCardsUI7Posters19FadingContainerView : UIView
{
    MISSING_TYPE *firstView;
    MISSING_TYPE *secondView;
    MISSING_TYPE *animationStarted;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSublayersOfLayer:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

