//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNTableViewCell.h>

@class MISSING_TYPE;

@interface _TtC23TwitterProfileModulesUIP33_5C23CA8827EAFB3E515DB256B2AFBDC739CommunityConfigurationItemTableViewCell : TFNTableViewCell
{
    MISSING_TYPE *$__lazy_storage_$_contentStackView;
    MISSING_TYPE *$__lazy_storage_$_bannerView;
    MISSING_TYPE *$__lazy_storage_$_communityInfoStackView;
    MISSING_TYPE *$__lazy_storage_$_displayNameLabel;
    MISSING_TYPE *$__lazy_storage_$_checkmarkImageView;
    MISSING_TYPE *$__lazy_storage_$_communityDescriptionLabel;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

