//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC4Jobs15DJSRichtextView : UIView
{
    MISSING_TYPE *draftContent;
    MISSING_TYPE *context;
    MISSING_TYPE *containerWidth;
    MISSING_TYPE *delegate;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

