//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC14DMConversation22MessageCellContentView : UIView
{
    MISSING_TYPE *canReply;
    MISSING_TYPE *clusterState;
    MISSING_TYPE *imageService;
    MISSING_TYPE *reactions;
    MISSING_TYPE *timestampPanState;
    MISSING_TYPE *bubbleHasContent;
    MISSING_TYPE *contentContainerView;
    MISSING_TYPE *stackView;
    MISSING_TYPE *attachmentReactionsView;
    MISSING_TYPE *bubbleReactionsView;
    MISSING_TYPE *headerView;
    MISSING_TYPE *$__lazy_storage_$_bodyView;
    MISSING_TYPE *$__lazy_storage_$_footerView;
    MISSING_TYPE *timestampView;
    MISSING_TYPE *replyArrowView;
    MISSING_TYPE *style;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (id)initWithCoder:(id)arg1;

@end

