//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC4DMV2P33_C5E223C5BA11B3ADB549EECA2C28FF3918RootDependencyImpl : _TtCs12_SwiftObject
{
    MISSING_TYPE *accountID;
    MISSING_TYPE *apiHeaderProvider;
    MISSING_TYPE *featureSwitchProvider;
    MISSING_TYPE *imagePipeline;
    MISSING_TYPE *postAttachmentLoader;
    MISSING_TYPE *postAttachmentViewBuilder;
    MISSING_TYPE *rootBadger;
    MISSING_TYPE *userID;
}

@end

