//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNTableViewCell.h>

@class MISSING_TYPE;

@interface _TtC20TwitterCommunitiesUI34TweetAudienceSelectionItemViewCell : TFNTableViewCell
{
    MISSING_TYPE *audienceSelectionItem;
    MISSING_TYPE *$__lazy_storage_$_itemView;
    MISSING_TYPE *$__lazy_storage_$_detailsStackView;
    MISSING_TYPE *$__lazy_storage_$_nameLabel;
    MISSING_TYPE *$__lazy_storage_$_detailLabel;
    MISSING_TYPE *$__lazy_storage_$_thumbnailImageView;
    MISSING_TYPE *selectionMarkerSize;
    MISSING_TYPE *selectionMarkerIconSize;
    MISSING_TYPE *selectionMarkerBorderWidth;
    MISSING_TYPE *$__lazy_storage_$_selectionMarker;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (long long)tui_scaleAspectFillFocusModeForFetchHelper:(id)arg1;
- (id)tui_focusRectanglesForFocusMode:(long long)arg1 inBounds:(struct CGRect)arg2 forFetchHelper:(id)arg3;

@end

