//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterAppSPMMigration/NSObject-Protocol.h>

@class AVCapturePhoto, AVDepthData, AVPortraitEffectsMatte, AVSemanticSegmentationMatte, NSDictionary, NSString;

@protocol AVCapturePhotoFileDataRepresentationCustomizer <NSObject>

@optional
- (NSDictionary *)replacementAppleProRAWCompressionSettingsForPhoto:(AVCapturePhoto *)arg1 defaultSettings:(NSDictionary *)arg2 maximumBitDepth:(long long)arg3;
- (AVSemanticSegmentationMatte *)replacementSemanticSegmentationMatteOfType:(NSString *)arg1 forPhoto:(AVCapturePhoto *)arg2;
- (AVPortraitEffectsMatte *)replacementPortraitEffectsMatteForPhoto:(AVCapturePhoto *)arg1;
- (AVDepthData *)replacementDepthDataForPhoto:(AVCapturePhoto *)arg1;
- (struct __CVBuffer *)replacementEmbeddedThumbnailPixelBufferWithPhotoFormat:(id *)arg1 forPhoto:(AVCapturePhoto *)arg2;
- (NSDictionary *)replacementMetadataForPhoto:(AVCapturePhoto *)arg1;
@end

