//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GADObserverCollection, NSString;

@interface GADAdExposureMonitor : NSObject
{
    GADObserverCollection *_observers;
    _Bool _adExposureBegan;
    NSString *_adUnitID;
}

+ (void)addMonitorToAd:(id)arg1 adConfiguration:(id)arg2 useVisibilityNotification:(_Bool)arg3;
- (void).cxx_destruct;
- (void)dealloc;
- (void)endExposure;
- (void)startExposure;
- (id)initWithAd:(id)arg1 adUnitID:(id)arg2 useVisibilityNotification:(_Bool)arg3;

@end

