//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface GADAdapterSettings : NSObject
{
    struct sqlite3 *_database;
    NSMutableDictionary *_values;
    NSMutableDictionary *_valuesToWrite;
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSObject<OS_dispatch_queue> *_writeQueue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)writeUpdatedValues:(id)arg1;
- (void)writeUpdates;
- (void)updateValuesWithString:(id)arg1 forKey:(id)arg2;
- (id)internalStringForKey:(id)arg1;
- (void)loadDatabaseValues;
- (void)clearDatabaseValues;
- (_Bool)openDatabase;
- (id)dictionaryForKey:(id)arg1 withDefault:(id)arg2;
- (id)arrayForKey:(id)arg1 withDefault:(id)arg2;
- (_Bool)boolForKey:(id)arg1 withDefault:(_Bool)arg2;
- (double)doubleForKey:(id)arg1 withDefault:(double)arg2;
- (long long)integerForKey:(id)arg1 withDefault:(long long)arg2;
- (long long)longLongForKey:(id)arg1 withDefault:(long long)arg2;
- (id)stringForKey:(id)arg1 withDefault:(id)arg2;
- (void)addEntriesFromDictionary:(id)arg1;
- (void)dealloc;
- (id)init;

@end

