//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSSet;
@protocol GADEventContextSource, OS_dispatch_queue;

@interface GADActionURLHandler : NSObject
{
    NSObject<OS_dispatch_queue> *_lockQueue;
    _Bool _bufferActionsPaused;
    NSMutableArray *_bufferedURLRequests;
    id <GADEventContextSource> _messageSource;
    NSSet *_allowlistedURLSchemes;
    NSSet *_notificationsToBuffer;
}

- (void).cxx_destruct;
- (void)resumeBufferedActions;
- (void)pauseBufferedActions;
- (void)handleActionURLRequest:(id)arg1;
- (id)initWithMessageSource:(id)arg1;

@end

