//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GADAnalyticsEventMonitor, GADJSContext;

@interface GADActiveViewContext : NSObject
{
    GADJSContext *_context;
    GADAnalyticsEventMonitor *_analyticsEventMonitor;
}

+ (void)loadWithEventContext:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (void)updateActiveViewWithSignals:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)setJSContext:(id)arg1;

@end

