//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GADAdLoadMonitor, GADAdVideoController, GADEventContext, GADInternalNativeAd, GADNativeAdImage, GADObserverCollection, GADViewVisibilityMonitor, GADWebAdView, NSDictionary, NSMutableArray, NSString, UIView;

@interface GADAdMediaContent : NSObject
{
    NSDictionary *_adConfiguration;
    NSDictionary *_videoConfiguration;
    GADInternalNativeAd *_internalNativeAd;
    GADWebAdView *_adView;
    NSMutableArray *_adViewMonitors;
    GADAdLoadMonitor *_adLoadMonitor;
    GADViewVisibilityMonitor *_viewVisibilityMonitor;
    GADObserverCollection *_observers;
    GADEventContext *_context;
    GADAdVideoController *_videoController;
    NSDictionary *_videoOptions;
    CDUnknownBlockType _completionHandler;
    struct CGSize _intrinsicVideoSize;
    GADNativeAdImage *_mainImage;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) GADAdVideoController *videoController;
@property(readonly, nonatomic) UIView *mediaView;
@property(retain, nonatomic) GADNativeAdImage *mainImage;
@property(readonly, nonatomic) struct CGSize intrinsicContentSize;
@property(readonly, nonatomic) double duration;
@property(readonly, nonatomic) double currentTime;
@property(readonly, nonatomic) double aspectRatio;
@property(readonly, nonatomic) GADEventContext *context;
- (void)addMonitor:(id)arg1;
- (void)registerOverlayViewObservers:(id)arg1;
- (void)performPostLoadActions;
- (void)finishLoadingWithError:(id)arg1;
- (void)renderVideoDictionary;
- (void)attachMonitors;
- (void)addObservers;
- (void)createAndLoadAdView;
- (void)loadVideoWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithInternalNativeAd:(id)arg1 adConfiguration:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

