//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GADAdContent, GADExpandActionMonitorConfiguration, GADFullScreenAdViewController, GADObserverCollection, GADWebAdView;
@protocol GADEventContextSource;

@interface GADExpandActionMonitor : NSObject
{
    GADAdContent *_ad;
    id <GADEventContextSource> _messageSource;
    GADWebAdView *_adView;
    GADObserverCollection *_observers;
    GADFullScreenAdViewController *_expandableViewController;
    GADObserverCollection *_expandableObservers;
    GADExpandActionMonitorConfiguration *_configuration;
}

- (void).cxx_destruct;
- (void)handleTwoPartExpandActionWithNote:(id)arg1;
- (void)handleOnePartExpandAction:(id)arg1;
- (_Bool)createAndPresentExpandable:(id)arg1 context:(id)arg2 notification:(id)arg3;
- (void)expandDidEnd;
- (id)initWithAd:(id)arg1 webAdView:(id)arg2 messageSource:(id)arg3 configuration:(id)arg4;

@end

