//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface GADNetworkUtilizationStatistics : NSObject
{
    NSDictionary *_transmittedByteCounts;
    NSDictionary *_receivedByteCounts;
}

+ (id)currentStatistics;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *receivedByteCounts; // @synthesize receivedByteCounts=_receivedByteCounts;
@property(readonly, nonatomic) NSDictionary *transmittedByteCounts; // @synthesize transmittedByteCounts=_transmittedByteCounts;
- (id)minusStatistics:(id)arg1;
- (id)plusStatistics:(id)arg1;
- (id)updatedStatistics;
- (id)init;
- (id)initWithTransmittedByteCounts:(id)arg1 receivedByteCounts:(id)arg2;

@end

