//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GADObserverCollection;

@interface GADOnePixelImpressionMonitor : NSObject
{
    GADObserverCollection *_observers;
    struct atomic_flag _didPostImpression;
}

- (void).cxx_destruct;
- (void)postImpressionNotificationForAd:(id)arg1;
- (id)initWithAd:(id)arg1;

@end

