//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GADOMIDActivityMonitor, GADOMIDAdSessionRegistry, GADOMIDStateWatcher, GADOMIDTreeWalker, NSString;
@protocol GADOMIDClockProtocol;

@interface GADOMIDSDK : NSObject
{
    _Bool _active;
    GADOMIDAdSessionRegistry *_adSessionRegistry;
    GADOMIDStateWatcher *_stateWatcher;
    GADOMIDTreeWalker *_treeWalker;
    GADOMIDActivityMonitor *_activityMonitor;
    id <GADOMIDClockProtocol> _clock;
}

+ (id)sharedInstance;
+ (id)versionString;
- (void).cxx_destruct;
@property(retain, nonatomic) id <GADOMIDClockProtocol> clock; // @synthesize clock=_clock;
@property(retain, nonatomic) GADOMIDActivityMonitor *activityMonitor; // @synthesize activityMonitor=_activityMonitor;
@property(retain, nonatomic) GADOMIDTreeWalker *treeWalker; // @synthesize treeWalker=_treeWalker;
@property(retain, nonatomic) GADOMIDStateWatcher *stateWatcher; // @synthesize stateWatcher=_stateWatcher;
@property(retain, nonatomic) GADOMIDAdSessionRegistry *adSessionRegistry; // @synthesize adSessionRegistry=_adSessionRegistry;
@property(readonly, getter=isActive) _Bool active; // @synthesize active=_active;
- (void)adSessionDidBecomeActive:(id)arg1;
- (void)adSessionRegistryDidResignActive;
- (void)adSessionRegistryDidBecomeActive;
- (void)appDidResignActive;
- (void)appDidBecomeActive;
- (void)stop;
- (void)start;
- (void)updateLastActivity;
- (_Bool)activate;
- (id)appInfo;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

