//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GADAdReward, GADFullScreenAdContent, GADObserverCollection;

@interface GADRewardedEventMonitor : NSObject
{
    GADFullScreenAdContent *_ad;
    GADObserverCollection *_observers;
    GADAdReward *_reward;
}

+ (void)addMonitorToAd:(id)arg1 adConfiguration:(id)arg2 view:(id)arg3;
- (void).cxx_destruct;
- (void)handleVideoCompleted;
- (void)handleVideoStarted;
- (void)handleRewardGrantedWithBackUpParameters:(id)arg1;
- (void)handleRewardAction:(id)arg1;
- (id)initWithAd:(id)arg1 reward:(id)arg2 view:(id)arg3;

@end

