//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GADEventContext, NSString, UIViewController, UIWindowScene;

@interface GADViewControllerPresenter : NSObject
{
    UIViewController *_viewController;
    GADEventContext *_context;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) __weak UIWindowScene *windowScene;
- (void)relinquishScreenWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)shouldDismissOnApplicationEnteringForeground;
- (void)presentFromViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)canPresentFromViewController:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic) GADEventContext *context;
- (id)initWithViewController:(id)arg1 context:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

