//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface HFHealthSafetyAccount : NSObject
{
    MISSING_TYPE *userID;
    MISSING_TYPE *featureSwitches;
    MISSING_TYPE *isSoftUser;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithUserID:(long long)arg1 featureSwitches:(id)arg2 isSoftUser:(_Bool)arg3;
- (id)initWithAccount:(id)arg1;

@end

