//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNItemsDataViewController.h>

@class MISSING_TYPE, TTMAsset;
@protocol MASMediaAttachmentSettingsViewControllerDelegate;

@interface MASMediaAttachmentSettingsViewController : TFNItemsDataViewController
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *attachmentView;
    MISSING_TYPE *warningSet;
    MISSING_TYPE *initWarningSet;
    MISSING_TYPE *account;
    MISSING_TYPE *mediaAsset;
    MISSING_TYPE *$__lazy_storage_$_attachmentContainerView;
    MISSING_TYPE *$__lazy_storage_$_blurInterstitial;
    MISSING_TYPE *$__lazy_storage_$_attachmentContainerItem;
    MISSING_TYPE *$__lazy_storage_$_educationTextItem;
    MISSING_TYPE *$__lazy_storage_$_sensitiveWarningBooleanItems;
    MISSING_TYPE *$__lazy_storage_$_sensitiveWarningItems;
    MISSING_TYPE *$__lazy_storage_$_allowDownloadSwitchItem;
    MISSING_TYPE *allowDownloadDescriptionItem;
    MISSING_TYPE *$__lazy_storage_$_allowDownloadItems;
}

- (void).cxx_destruct;
- (id)initWithCollectionViewLayout:(id)arg1;
- (void)logAction:(id)arg1;
- (void)_hf_didTapDoneWithSender:(id)arg1;
- (void)_hf_didTapCancelWithSender:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithAttachmentView:(id)arg1 asset:(id)arg2 account:(id)arg3;
@property(nonatomic, readonly) TTMAsset *mediaAsset; // @synthesize mediaAsset;
@property(nonatomic) __weak id <MASMediaAttachmentSettingsViewControllerDelegate> delegate; // @synthesize delegate;

@end

