//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, TFSTwitterOnboardingFlowSpec;
@protocol TFSTwitterAPICommandContext, TFSTwitterAPICommandLoader, TFSTwitterAuthTimelineTokenStorageDelegate;

@interface OCFAPITaskService : NSObject
{
    id <TFSTwitterAPICommandContext> _context;
    NSString *_knownDeviceToken;
    NSString *_simCountryCode;
    id <TFSTwitterAPICommandLoader> _commandLoader;
    TFSTwitterOnboardingFlowSpec *_flowSpec;
    id <TFSTwitterAuthTimelineTokenStorageDelegate> _authTokenStorage;
}

- (void).cxx_destruct;
- (id)sendPreviousTask:(id)arg1 withState:(id)arg2 forAccountID:(id)arg3 terminationReason:(long long)arg4 debugParameters:(id)arg5 headerFields:(id)arg6 fetchNextTaskWithResponseBlock:(CDUnknownBlockType)arg7;
- (id)initWithFlowSpec:(id)arg1 commandLoader:(id)arg2 context:(id)arg3 simCountryCode:(id)arg4 knownDeviceToken:(id)arg5 authTokenStorage:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

