//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class OCFButtonAppearance, OCFNavigationLink, OCFRichText;

@interface OCFButtonItemComponentData
{
    OCFRichText *_primaryText;
    OCFRichText *_secondaryText;
    OCFButtonAppearance *_buttonAppearance;
    OCFRichText *_buttonLabel;
    OCFNavigationLink *_navigationLink;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) OCFNavigationLink *navigationLink; // @synthesize navigationLink=_navigationLink;
@property(readonly, nonatomic) OCFRichText *buttonLabel; // @synthesize buttonLabel=_buttonLabel;
@property(readonly, nonatomic) OCFButtonAppearance *buttonAppearance; // @synthesize buttonAppearance=_buttonAppearance;
@property(readonly, nonatomic) OCFRichText *secondaryText; // @synthesize secondaryText=_secondaryText;
@property(readonly, nonatomic) OCFRichText *primaryText; // @synthesize primaryText=_primaryText;
- (id)componentNavigationLink;
- (id)initWithJSONDictionary:(id)arg1 error:(id *)arg2;

@end

