//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSString, OCFComponent, OCFNavigationLink, OCFRichText;

@interface OCFEnterEmailSubtask
{
    OCFRichText *_primaryText;
    OCFRichText *_secondaryText;
    NSString *_hintText;
    OCFNavigationLink *_nextLink;
    OCFNavigationLink *_skipLink;
    NSArray *_settings;
    OCFComponent *_discoverabilitySetting;
}

+ (id)emailSubtaskDataKey;
+ (long long)version;
+ (id)typeNames;
- (void).cxx_destruct;
@property(readonly, nonatomic) OCFComponent *discoverabilitySetting; // @synthesize discoverabilitySetting=_discoverabilitySetting;
@property(readonly, nonatomic) NSArray *settings; // @synthesize settings=_settings;
@property(readonly, nonatomic) OCFNavigationLink *skipLink; // @synthesize skipLink=_skipLink;
@property(readonly, nonatomic) OCFNavigationLink *nextLink; // @synthesize nextLink=_nextLink;
@property(readonly, nonatomic) NSString *hintText; // @synthesize hintText=_hintText;
@property(readonly, nonatomic) OCFRichText *secondaryText; // @synthesize secondaryText=_secondaryText;
@property(readonly, nonatomic) OCFRichText *primaryText; // @synthesize primaryText=_primaryText;
- (id)header;
- (id)initWithJSONDictionary:(id)arg1 subtaskID:(id)arg2 typeName:(id)arg3 backNavigationType:(long long)arg4 backNavigationLink:(id)arg5 error:(id *)arg6;

@end

