//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, OCFPasskeySubtaskState;

@interface OCFEnterTextSubtaskState
{
    NSString *_text;
    NSString *_suggestionID;
    OCFPasskeySubtaskState *_passKeyState;
}

- (void).cxx_destruct;
@property(retain, nonatomic) OCFPasskeySubtaskState *passKeyState; // @synthesize passKeyState=_passKeyState;
@property(copy, nonatomic) NSString *suggestionID; // @synthesize suggestionID=_suggestionID;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void)addStateToJSONDictionary:(id)arg1;

@end

