//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, OCFSubtaskDataReference;

@interface OCFNavigationLinkOptions : NSObject
{
    OCFSubtaskDataReference *_countSubtaskDataReference;
    NSArray *_labelConditionalText;
    NSNumber *_minEnableCount;
    NSNumber *_maxEnableCount;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSNumber *maxEnableCount; // @synthesize maxEnableCount=_maxEnableCount;
@property(readonly, nonatomic) NSNumber *minEnableCount; // @synthesize minEnableCount=_minEnableCount;
@property(readonly, nonatomic) NSArray *labelConditionalText; // @synthesize labelConditionalText=_labelConditionalText;
@property(readonly, nonatomic) OCFSubtaskDataReference *countSubtaskDataReference; // @synthesize countSubtaskDataReference=_countSubtaskDataReference;
- (id)initWithJSONDictionary:(id)arg1 error:(id *)arg2;

@end

