//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, OCFNavigationLink;

@interface OCFOpenLinkSubtask
{
    OCFNavigationLink *_link;
    NSString *_onboardingCallbackPath;
}

+ (id)typeNames;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *onboardingCallbackPath; // @synthesize onboardingCallbackPath=_onboardingCallbackPath;
@property(readonly, nonatomic) OCFNavigationLink *link; // @synthesize link=_link;
- (id)initWithJSONDictionary:(id)arg1 subtaskID:(id)arg2 typeName:(id)arg3 backNavigationType:(long long)arg4 backNavigationLink:(id)arg5 error:(id *)arg6;

@end

