//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDate, NSString;

@interface OCFSignUpSubtaskState
{
    NSString *_name;
    NSString *_countryCode;
    NSString *_phone;
    NSString *_email;
    NSDate *_birthday;
    NSString *_jsInstrumentationResponse;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *jsInstrumentationResponse; // @synthesize jsInstrumentationResponse=_jsInstrumentationResponse;
@property(retain, nonatomic) NSDate *birthday; // @synthesize birthday=_birthday;
@property(copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(copy, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void)addStateToJSONDictionary:(id)arg1;

@end

