//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class OCFRichText, TFSTwitterUser;

@interface OCFUserComponentData
{
    TFSTwitterUser *_user;
    OCFRichText *_caption;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) OCFRichText *caption; // @synthesize caption=_caption;
@property(readonly, nonatomic) TFSTwitterUser *user; // @synthesize user=_user;
- (id)initWithUser:(id)arg1 caption:(id)arg2;
- (id)initWithJSONDictionary:(id)arg1 error:(id *)arg2;

@end

