//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface OCFWaitSpinnerSubtaskState
{
    long long _waitTimeMs;
}

@property(nonatomic) long long waitTimeMs; // @synthesize waitTimeMs=_waitTimeMs;
- (void)addStateToJSONDictionary:(id)arg1;

@end

