//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, UIView;

@interface PTVAnimatedTransitionWithShadeCoordinator : NSObject
{
    _Bool _isBeingPresented;
    UIView *_shadeView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIView *shadeView; // @synthesize shadeView=_shadeView;
@property(nonatomic) _Bool isBeingPresented; // @synthesize isBeingPresented=_isBeingPresented;
- (double)animatableHeightForPresentedViewController:(id)arg1 otherViewController:(id)arg2;
- (unsigned long long)animationOptions;
- (double)transitionDuration;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

