//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@protocol PTVAnchoredModalContainerViewDelegate;

@interface PTVAnchoredModalContainerView : UIView
{
    id <PTVAnchoredModalContainerViewDelegate> _delegate;
    UIView *_contentView;
}

+ (struct CGRect)AnchoredFrame:(struct CGSize)arg1 ContainerSize:(struct CGSize)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void)dismiss;
- (void)tapOccurred:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 contentView:(id)arg2 delegate:(id)arg3;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;

@end

