//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSString, NSTimer, PTVBannerPresentableContentView, UIPanGestureRecognizer;

@interface PTVBannerView : UIView
{
    _Bool _isShowing;
    _Bool _pendingDismiss;
    _Bool _interacting;
    PTVBannerPresentableContentView *_contentView;
    UIView *_addedFill;
    UIPanGestureRecognizer *_dismissPan;
    NSTimer *_dismissTimer;
    CDUnknownBlockType _dismissCompletion;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool interacting; // @synthesize interacting=_interacting;
@property(nonatomic) _Bool pendingDismiss; // @synthesize pendingDismiss=_pendingDismiss;
@property(nonatomic) _Bool isShowing; // @synthesize isShowing=_isShowing;
@property(copy, nonatomic) CDUnknownBlockType dismissCompletion; // @synthesize dismissCompletion=_dismissCompletion;
@property(retain, nonatomic) NSTimer *dismissTimer; // @synthesize dismissTimer=_dismissTimer;
@property(retain, nonatomic) UIPanGestureRecognizer *dismissPan; // @synthesize dismissPan=_dismissPan;
@property(retain, nonatomic) UIView *addedFill; // @synthesize addedFill=_addedFill;
@property(retain, nonatomic) PTVBannerPresentableContentView *contentView; // @synthesize contentView=_contentView;
- (id)accessibilityContents;
- (void)contentViewDidRequestDismiss:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)dismissAnimationDidComplete:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismissContentViewWithDelay:(double)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentationAnimationDidComplete:(_Bool)arg1 presentationDuration:(double)arg2;
- (void)presentContentViewWithDismissCompletion:(CDUnknownBlockType)arg1;
- (void)animateContentViewToOriginalPosition;
- (void)handlePan:(id)arg1;
- (void)containerFrameDidChange:(struct CGRect)arg1;
- (void)safeAreaInsetsDidChange;
- (void)layoutContentView:(float)arg1;
- (void)layoutSubviews;
- (id)initWithContentView:(id)arg1 frame:(struct CGRect)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

