//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterAppSPMMigration/NSObject-Protocol.h>

@class NSString, PTVBroadcastOverflowMenuViewController, PTVOverflowMenuItem;

@protocol PTVBroadcastOverflowMenuViewControllerDelegate <NSObject>
- (_Bool)overflowMenu:(PTVBroadcastOverflowMenuViewController *)arg1 shouldEnableMenuItem:(PTVOverflowMenuItem *)arg2;
- (void)overflowMenu:(PTVBroadcastOverflowMenuViewController *)arg1 didSelectMenuItem:(PTVOverflowMenuItem *)arg2;

@optional
- (void)overflowMenu:(PTVBroadcastOverflowMenuViewController *)arg1 didTapTitleHashtag:(NSString *)arg2;
- (void)overflowMenuDidTapEmptySpace:(PTVBroadcastOverflowMenuViewController *)arg1;
@end

