//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterAppSPMMigration/NSObject-Protocol.h>

@class NSIndexPath, NSString, PTVBroadcastDetailsViewModel;

@protocol PTVBroadcastDetailsViewModelDelegate <NSObject>
- (void)broadcastDetailsViewModelDidReloadData:(PTVBroadcastDetailsViewModel *)arg1;

@optional
- (void)broadcastDetailsViewModel:(PTVBroadcastDetailsViewModel *)arg1 didUpdateReplayViewerWithID:(NSString *)arg2 atIndexPath:(NSIndexPath *)arg3;
- (void)broadcastDetailsViewModel:(PTVBroadcastDetailsViewModel *)arg1 didUpdateLiveViewerWithID:(NSString *)arg2 atIndexPath:(NSIndexPath *)arg3;
- (void)broadcastDetailsViewModelDidUpdateNumberOfCommentsReceived:(PTVBroadcastDetailsViewModel *)arg1;
- (void)broadcastDetailsViewModelDidUpdateOccupancyMetrics:(PTVBroadcastDetailsViewModel *)arg1;
- (void)broadcastDetailsViewModelDidUpdateViewerCounts:(PTVBroadcastDetailsViewModel *)arg1;
@end

