//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class UIButton;
@protocol PTVBroadcastEditSaveChangesViewDelegate;

@interface PTVBroadcastEditSaveChangesView : UIView
{
    UIButton *_saveChangesButton;
    id <PTVBroadcastEditSaveChangesViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) __weak id <PTVBroadcastEditSaveChangesViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIButton *saveChangesButton; // @synthesize saveChangesButton=_saveChangesButton;
- (void)enterSavedState;
- (void)enterSavingState;
- (void)enterSaveChangesState;
- (void)saveChangesButtonPressed;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

