//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterAppSPMMigration/NSObject-Protocol.h>

@class PTVMessage;

@protocol PTVChatActionSheetControllerDelegate <NSObject>
- (void)chatActionSheetDidPressReportOtherReason:(PTVMessage *)arg1;
- (void)chatActionSheetDidPressReportSexualContent:(PTVMessage *)arg1;
- (void)chatActionSheetDidPressReportSpam:(PTVMessage *)arg1;
- (void)chatActionSheetDidPressReportAbuse:(PTVMessage *)arg1;
- (void)chatActionSheetDidPressUnmuteForMessage:(PTVMessage *)arg1;
- (void)chatActionSheetDidPressMuteForMessage:(PTVMessage *)arg1;
- (void)chatActionSheetDidPressBlockUserForMessage:(PTVMessage *)arg1;
- (void)chatActionSheetDidPressViewProfile:(PTVMessage *)arg1;
- (void)chatActionSheetDidPressReplyTo:(PTVMessage *)arg1;
@end

