//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class PTVDividerView, PTVTitleAndIconView, UILabel;

@interface PTVContributorsTableViewHeaderView : UIView
{
    UILabel *_titleLabel;
    PTVTitleAndIconView *_totalStarsLabel;
    PTVTitleAndIconView *_helperStarLabel;
    PTVTitleAndIconView *_helperCoinLabel;
    PTVDividerView *_bottomDivider;
    UILabel *_exchangeDescriptionLabel;
}

- (void).cxx_destruct;
- (void)setStarTotal:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1 loggedInUserIsBroadcaster:(_Bool)arg2;

@end

