//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterAppSPMMigration/NSObject-Protocol.h>

@class PTVChatTableViewCell, PTVMessage;

@protocol PTVChatTableViewCellDelegate <NSObject>

@optional
- (void)chatTableViewCell:(PTVChatTableViewCell *)arg1 didTapMessage:(PTVMessage *)arg2;
@end

