//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface PTVChatReplayData : NSObject
{
    NSArray *_historyArray;
    NSString *_cursor;
}

+ (id)messageFromChatWireMessage:(id)arg1 loggedInUser:(id)arg2 broadcastCreatedAfterOct10:(_Bool)arg3;
+ (id)chatReplayDataFromChatHistory:(id)arg1 historyStartDate:(id)arg2 loggedInUser:(id)arg3;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *cursor; // @synthesize cursor=_cursor;
@property(readonly, nonatomic) NSArray *historyArray; // @synthesize historyArray=_historyArray;
- (id)initWithArray:(id)arg1 cursor:(id)arg2;

@end

