//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class PTVWeakSet, UILayoutGuide;

@interface PTVExternalVideoPlayer : UIViewController
{
    PTVWeakSet *_externalVideoPlayerObservers;
    unsigned long long _playbackState;
    UILayoutGuide *_contentAreaGuide;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILayoutGuide *contentAreaGuide; // @synthesize contentAreaGuide=_contentAreaGuide;
@property(nonatomic) unsigned long long playbackState; // @synthesize playbackState=_playbackState;
- (void)setDisplayedAsGuestView:(_Bool)arg1;
- (id)videoPlayerStatistics;
- (void)captureStillImageOfVideoPlayer:(CDUnknownBlockType)arg1;
- (_Bool)shouldCaptureStillImageOfVideoPlayer;
- (_Bool)isSeekingToNTPTime;
- (unsigned long long)ntpToSeekTo;
- (_Bool)canSeekToTime;
- (void)seekToTime:(double)arg1 completion:(CDUnknownBlockType)arg2;
- (void)didReceiveTimedMedataWithDescription:(id)arg1 value:(id)arg2;
- (double)videoDuration;
- (void)didReceiveVideoDuration;
- (double)currentPlaybackTime;
- (id)dateWhenVideoWasLastPaused;
- (id)programDateTime;
- (id)dateWhenLastReceivedNTPTimestamp;
- (double)lastReceivedNTPTimestamp;
- (_Bool)canProvideTimingDataForSyncingComments;
- (_Bool)hasNTPData;
- (void)didReceiveVideoMetadata;
@property(readonly, nonatomic) struct CGSize currentVideoPlayerSize;
@property(readonly, nonatomic) _Bool isReadyForDisplay;
- (_Bool)shouldAutoPlayVideo;
- (void)didReachEndOfVideo;
- (void)disconnectVideo;
- (void)broadcastEndPending;
- (void)pauseVideo;
- (void)playVideo;
- (void)notifyExternalVideoPlayerObservers:(CDUnknownBlockType)arg1;
- (void)removeExternalVideoPlayerObserver:(id)arg1;
- (void)addExternalVideoPlayerObserver:(id)arg1;
- (void)loadView;

@end

