//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <QuartzCore/CALayer.h>

@class PTVGiftStyle, PTVSpriteAnimationLayer, UIImage;

@interface PTVGiftHeartSpriteLayer : CALayer
{
    CALayer *_colorLayer;
    CALayer *_avatarLayer;
    PTVSpriteAnimationLayer *_avatarMaskLayer;
    PTVSpriteAnimationLayer *_borderLayer;
    PTVSpriteAnimationLayer *_colorMask;
    struct CGSize _animationFrameSize;
    double _duration;
    _Bool _isPaused;
    PTVGiftStyle *_giftStyle;
    long long _participantIndex;
    UIImage *_avatar;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *avatar; // @synthesize avatar=_avatar;
@property(nonatomic) long long participantIndex; // @synthesize participantIndex=_participantIndex;
@property(readonly, nonatomic) PTVGiftStyle *giftStyle; // @synthesize giftStyle=_giftStyle;
@property(readonly, nonatomic) _Bool isPaused; // @synthesize isPaused=_isPaused;
- (void)pauseAtOffset;
- (void)resumeAnimation;
- (void)attachAnimationsIfNeeded;
- (void)attachAnimations;
- (void)initializeAvatar;
- (void)setParticipantIndex:(long long)arg1 avatar:(id)arg2;
- (void)initializeLayersWithFillSprite:(id)arg1 maskSprite:(id)arg2 borderSprite:(id)arg3;
- (void)layoutSublayers;
- (void)applicationWillEnterForeground:(id)arg1;
- (id)initWithGiftStyle:(id)arg1;
- (id)initWithAnimationFrameSize:(struct CGSize)arg1 duration:(double)arg2;

@end

