//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSError, NSString;

@interface PTVJanusResponse : NSObject
{
    unsigned long long _result;
    unsigned long long _sessionId;
    NSString *_transactionId;
    NSError *_responseError;
}

+ (id)responseErrorFromJSON:(id)arg1;
+ (unsigned long long)resultTypeFromJSON:(id)arg1;
+ (id)responseFromJSONDictionary:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSError *responseError; // @synthesize responseError=_responseError;
@property(retain, nonatomic) NSString *transactionId; // @synthesize transactionId=_transactionId;
@property(nonatomic) unsigned long long sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) unsigned long long result; // @synthesize result=_result;

@end

