//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PTVJanusAttachResponse
{
    unsigned long long _pluginId;
}

+ (id)responseFromJSONDictionary:(id)arg1;
@property(nonatomic) unsigned long long pluginId; // @synthesize pluginId=_pluginId;

@end

