//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary, NSNumber, NSString, NSTimer, PTVAudioMonitor, PTVGuestRoomConfiguration, PTVJanusVideoRoomPluginHandler, PTVWeakSet, RTCIceServer, RTCPeerConnectionFactory;
@protocol PTVJanusClientHandlerFactoryProtocol, PTVJanusPluginHandlerProtocol, PTVLoggedInUserProtocol, PTVWebRTCClientDelegate, PTVWebRTCClientNetworkHelperProtocol;

@interface PTVJanusClient : NSObject
{
    PTVJanusClient *_weakSelf;
    PTVWeakSet *_observers;
    _Bool _isWebRTCActive;
    _Bool _isWaitingForLongPollResponse;
    _Bool _disconnectedWithError;
    _Bool _shouldIceRestart;
    int _receivingStatus;
    id <PTVWebRTCClientDelegate> _delegate;
    unsigned long long _publisherRole;
    NSString *_roomId;
    long long _state;
    PTVGuestRoomConfiguration *_configuration;
    NSTimer *_pingJanusSessionTimer;
    unsigned long long _janusSessionId;
    NSObject<PTVLoggedInUserProtocol> *_loggedInUser;
    NSString *_adminUserId;
    RTCIceServer *_iceServer;
    RTCPeerConnectionFactory *_peerConnectionFactory;
    id <PTVJanusPluginHandlerProtocol> _storedLoggedInUserHandlerForDestroy;
    NSMutableDictionary *_videoRoomPluginHandlers;
    NSMutableDictionary *_handlersPendingAttach;
    double _lastReceivingStatusChange;
    long long _reachabilityStatus;
    id <PTVWebRTCClientNetworkHelperProtocol> _networkHelper;
    id <PTVJanusClientHandlerFactoryProtocol> _handlerFactory;
    PTVAudioMonitor *_localAudioMonitor;
    CDStruct_08766ad0 _features;
}

+ (id)janusResponseUnhandledError;
+ (id)janusResponseParseError;
- (void).cxx_destruct;
@property(retain, nonatomic) PTVAudioMonitor *localAudioMonitor; // @synthesize localAudioMonitor=_localAudioMonitor;
@property(readonly, nonatomic) CDStruct_08766ad0 features; // @synthesize features=_features;
@property(retain, nonatomic) id <PTVJanusClientHandlerFactoryProtocol> handlerFactory; // @synthesize handlerFactory=_handlerFactory;
@property(retain, nonatomic) id <PTVWebRTCClientNetworkHelperProtocol> networkHelper; // @synthesize networkHelper=_networkHelper;
@property(nonatomic) long long reachabilityStatus; // @synthesize reachabilityStatus=_reachabilityStatus;
@property(nonatomic) double lastReceivingStatusChange; // @synthesize lastReceivingStatusChange=_lastReceivingStatusChange;
@property(nonatomic) int receivingStatus; // @synthesize receivingStatus=_receivingStatus;
@property(readonly, nonatomic) NSMutableDictionary *handlersPendingAttach; // @synthesize handlersPendingAttach=_handlersPendingAttach;
@property(readonly, nonatomic) NSMutableDictionary *videoRoomPluginHandlers; // @synthesize videoRoomPluginHandlers=_videoRoomPluginHandlers;
@property(retain, nonatomic) id <PTVJanusPluginHandlerProtocol> storedLoggedInUserHandlerForDestroy; // @synthesize storedLoggedInUserHandlerForDestroy=_storedLoggedInUserHandlerForDestroy;
@property(nonatomic) _Bool shouldIceRestart; // @synthesize shouldIceRestart=_shouldIceRestart;
@property(nonatomic) _Bool disconnectedWithError; // @synthesize disconnectedWithError=_disconnectedWithError;
@property(retain, nonatomic) RTCPeerConnectionFactory *peerConnectionFactory; // @synthesize peerConnectionFactory=_peerConnectionFactory;
@property(retain, nonatomic) RTCIceServer *iceServer; // @synthesize iceServer=_iceServer;
@property(retain, nonatomic) NSString *adminUserId; // @synthesize adminUserId=_adminUserId;
@property(retain, nonatomic) NSObject<PTVLoggedInUserProtocol> *loggedInUser; // @synthesize loggedInUser=_loggedInUser;
@property(nonatomic) unsigned long long janusSessionId; // @synthesize janusSessionId=_janusSessionId;
@property(retain, nonatomic) NSTimer *pingJanusSessionTimer; // @synthesize pingJanusSessionTimer=_pingJanusSessionTimer;
@property(nonatomic) _Bool isWaitingForLongPollResponse; // @synthesize isWaitingForLongPollResponse=_isWaitingForLongPollResponse;
@property(retain, nonatomic) PTVGuestRoomConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) long long state; // @synthesize state=_state;
@property(readonly, nonatomic) NSString *roomId; // @synthesize roomId=_roomId;
@property(readonly, nonatomic) unsigned long long publisherRole; // @synthesize publisherRole=_publisherRole;
@property(readonly, nonatomic) _Bool isWebRTCActive; // @synthesize isWebRTCActive=_isWebRTCActive;
@property(readonly, nonatomic) __weak id <PTVWebRTCClientDelegate> delegate; // @synthesize delegate=_delegate;
- (void)logAction:(id)arg1 element:(id)arg2;
- (void)storeAndOutputError:(id)arg1;
- (void)storeAndOutputLog:(id)arg1;
- (void)displayErrorWithFormat:(id)arg1;
- (void)displayLogWithFormat:(id)arg1;
- (void)reportErrorToDelegateIfNeeded:(id)arg1 shouldDisplayError:(_Bool)arg2 withLogEntryFormat:(id)arg3;
- (void)reportErrorToDelegateIfNeeded:(id)arg1 shouldDisplayError:(_Bool)arg2;
- (void)reconnectHandler:(unsigned long long)arg1;
- (void)onSubscribeTimerFor:(id)arg1;
- (id)subscribeTimerForHandler:(id)arg1;
- (void)tnl_communicationAgent:(id)arg1 didUpdateReachabilityFromPreviousFlags:(unsigned int)arg2 previousStatus:(long long)arg3 toCurrentFlags:(unsigned int)arg4 currentStatus:(long long)arg5;
- (void)tnl_communicationAgent:(id)arg1 didRegisterObserverWithInitialReachabilityFlags:(unsigned int)arg2 status:(long long)arg3 carrierInfo:(id)arg4 WWANRadioAccessTechnology:(id)arg5 captivePortalStatus:(long long)arg6;
- (void)onJoinFailure:(id)arg1;
- (void)onVideoRoomError:(id)arg1;
- (void)onVideoRoomDestroyed:(id)arg1;
- (void)onSlowLink:(id)arg1;
- (void)iceRestartForAllHandlersShouldNotify:(_Bool)arg1 ignoreState:(_Bool)arg2;
- (_Bool)iceRestartForHandler:(id)arg1 ignoreState:(_Bool)arg2;
- (void)checkLastReceivingTimeout;
- (void)onMedia:(id)arg1;
- (void)setIsWebRTCActive:(_Bool)arg1;
- (void)onWebRtcUp:(id)arg1;
- (void)onDetached:(id)arg1;
- (void)onLeft:(id)arg1;
- (void)handleLeavingEventForHandler:(id)arg1 fromPollResponse:(id)arg2;
- (void)onLeaving:(id)arg1;
- (void)onLoggedInUserLeaving:(id)arg1;
- (void)handleUnpublishedEventForHandler:(id)arg1 fromPollResponse:(id)arg2;
- (void)onUnpublished:(id)arg1;
- (void)onLoggedInUserUnpublished:(id)arg1;
- (void)onHangUp:(id)arg1;
- (void)onListenerAttached:(id)arg1;
- (void)onStarted:(id)arg1;
- (void)onConfigured:(id)arg1;
- (void)addListenerHandlerForNewPublisher:(id)arg1;
- (void)onNewPublishers:(id)arg1;
- (void)onJoined:(id)arg1;
- (void)restartJanusVideoRoomKeepAliveTimer;
- (void)pollStatus:(CDUnknownBlockType)arg1;
- (void)startJanusVideoRoomPollerIfNeeded;
- (void)initializePublisherHandler;
- (void)getIceServers;
- (void)resume;
- (void)setState:(long long)arg1;
- (void)detachAndDestroySessionsWithVideoHandlers:(id)arg1 loggedInUserHandler:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)leaveWithError:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)ping;
- (void)reconfigureWithVideoIfNeeded;
- (void)join;
- (void)removeOtherUserVideoHandler:(id)arg1;
- (void)removeVideoHandler:(id)arg1;
- (void)addVideoHandler:(id)arg1;
- (id)videoHandlerForPollerResponse:(id)arg1;
- (id)userIdForMediaStream:(id)arg1;
- (id)videoHandlerForMediaStream:(id)arg1;
- (_Bool)isFullyConnectedToUserID:(id)arg1;
@property(readonly, nonatomic) NSNumber *loggedInUserJanusPublisherId;
@property(readonly, nonatomic) NSNumber *loggedInUserJanusHandlerId;
@property(readonly, nonatomic) PTVJanusVideoRoomPluginHandler *loggedInUserHandler;
- (id)videoHandlerWithHandlerId:(unsigned long long)arg1;
- (id)videoHandlerForPeriscopeUserId:(id)arg1;
- (_Bool)hasVideoHandlerForPeriscopeUserId:(id)arg1;
@property(readonly, nonatomic) unsigned long long numberOfVideoHandlers;
@property(readonly, nonatomic) NSArray *videoHandlers;
- (void)notify:(CDUnknownBlockType)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
@property(readonly, nonatomic) NSString *userId;
- (id)initWithConfiguration:(id)arg1 delegate:(id)arg2 loggedInUser:(id)arg3 adminUserId:(id)arg4 publisherRole:(unsigned long long)arg5 networkHelper:(id)arg6 handlerFactory:(id)arg7 features:(CDStruct_08766ad0)arg8;
- (void)videoRoomPluginHandler:(id)arg1 didAddLog:(id)arg2;
- (void)videoRoomPluginHandlerNeedsRestart:(id)arg1;
- (void)videoRoomPluginHandler:(id)arg1 didChangeState:(unsigned long long)arg2;
- (void)videoRoomPluginHandler:(id)arg1 didError:(id)arg2;
- (void)videoRoomPluginHandler:(id)arg1 didReceiveLocalAudioLevel:(id)arg2;
- (void)videoRoomPluginHandler:(id)arg1 didReceiveRemoteAudioLevel:(id)arg2;
- (void)videoRoomPluginHandler:(id)arg1 didRemoveRemoteMediaStream:(id)arg2;
- (void)videoRoomPluginHandler:(id)arg1 didUpdateRemoteMediaStream:(id)arg2;
- (void)videoRoomPluginHandler:(id)arg1 didReceiveLocalAudioTrack:(id)arg2;
- (void)videoRoomPluginHandler:(id)arg1 didReceiveLocalVideoTrack:(id)arg2;
- (void)videoRoomPluginHandler:(id)arg1 didCreateLocalVideoSource:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

