//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class UILabel;
@protocol PTVNavigationBarTitleSubtitleViewDelegate;

@interface PTVNavigationBarTitleSubtitleView : UIView
{
    id <PTVNavigationBarTitleSubtitleViewDelegate> _titleTapDelegate;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
}

+ (id)SubtitleFont;
+ (id)TitleFont;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 titleTapDelegate:(id)arg3;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;

@end

