//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@class NSArray;

@interface PTVParticipantsBarFlowLayout : UICollectionViewFlowLayout
{
    NSArray *_updateItems;
}

+ (Class)layoutAttributesClass;
- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *updateItems; // @synthesize updateItems=_updateItems;
- (id)indexPathsToInsertForSupplementaryViewOfKind:(id)arg1;
- (id)indexPathsToDeleteForSupplementaryViewOfKind:(id)arg1;
- (void)applyOffscreenItemAttributes:(id)arg1;
- (id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1;
- (id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)arg1;
- (_Bool)isItemBeingDeletedAtIndexPath:(id)arg1;
- (_Bool)isItemBeingInsertedAtIndexPath:(id)arg1;
- (void)finalizeCollectionViewUpdates;
- (void)prepareForCollectionViewUpdates:(id)arg1;

@end

