//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSString, UILabel, UITapGestureRecognizer, UITextView;
@protocol UITextViewDelegate;

@interface PTVPreBroadcastTitleView : UIView
{
    UITextView *_statusTextView;
    UILabel *_placeholderLabel;
    UITapGestureRecognizer *_tapToCloseGestureRecognizer;
    unsigned long long _remainingCharacterLimit;
    UIView *_topAccessoryView;
    UIView *_bottomFloatingAccessoryView;
    id <UITextViewDelegate> _textViewDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <UITextViewDelegate> textViewDelegate; // @synthesize textViewDelegate=_textViewDelegate;
@property(retain, nonatomic) UIView *bottomFloatingAccessoryView; // @synthesize bottomFloatingAccessoryView=_bottomFloatingAccessoryView;
@property(retain, nonatomic) UIView *topAccessoryView; // @synthesize topAccessoryView=_topAccessoryView;
@property(nonatomic) unsigned long long remainingCharacterLimit; // @synthesize remainingCharacterLimit=_remainingCharacterLimit;
- (void)layoutBottomFloatingAccessoryView;
@property(retain, nonatomic) UIView *keyboardTitleAccessoryView;
- (_Bool)hasTitle;
- (void)layoutPlaceholder;
@property(readonly, nonatomic) UILabel *placeholderLabel;
@property(retain, nonatomic) NSString *title;
- (void)layoutStatusTextView;
@property(readonly, nonatomic) UITextView *statusTextView;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)canTapToClose;
- (void)handleTapToClose;
- (void)setupTapToCloseGesture;
- (void)updateTitleViewState;
- (void)setupPTVPreBroadcastTitleView;
- (id)initWithTitle:(id)arg1;
- (void)textStorage:(id)arg1 didProcessEditing:(unsigned long long)arg2 range:(struct _NSRange)arg3 changeInLength:(long long)arg4;
- (void)textViewDidChangeSelection:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (struct CGSize)textSizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

