//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class PTVPublishParams;

@interface PTVPublishLadderEntry : NSObject
{
    int _bandwidthLimit;
    PTVPublishParams *_publishParams;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) PTVPublishParams *publishParams; // @synthesize publishParams=_publishParams;
@property(readonly, nonatomic) int bandwidthLimit; // @synthesize bandwidthLimit=_bandwidthLimit;
- (id)initWithParams:(id)arg1 andBandwidthLimit:(int)arg2;

@end

