//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSData, NSString;
@protocol PTVRTMPHandlerDelegate;

@interface PTVRTMPVideoSender : NSObject
{
    NSObject<PTVRTMPHandlerDelegate> *_delegate;
    NSData *_config;
    int _width;
    int _height;
    NSString *_paramSets;
    NSString *_profile_level_id;
    int _lengthSize;
    _Bool _seenIDR;
}

- (void).cxx_destruct;
@property(readonly) int height; // @synthesize height=_height;
@property(readonly) int width; // @synthesize width=_width;
- (void)sendData:(id)arg1 pts:(double)arg2 decodeAt:(double)arg3;
- (void)onDiscont;
- (void)sendHeader;
- (id)getTrackInfo;
@property(readonly) NSString *codecID;
- (void)setDelegate:(id)arg1;
- (id)initWithConfigData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

