//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface PTVReplayControlsViewLayout : NSObject
{
    struct CGSize _containerSize;
    struct CGSize _playButtonSize;
    struct CGSize _activityIndicatorSize;
}

+ (id)ErrorSubtitleFont;
+ (id)ErrorTitleFont;
+ (double)ErrorTitleLineSpacing;
+ (id)AttributedStringWithErrorTitle:(id)arg1 Subtitle:(id)arg2;
@property(readonly, nonatomic) struct CGSize activityIndicatorSize; // @synthesize activityIndicatorSize=_activityIndicatorSize;
@property(readonly, nonatomic) struct CGSize playButtonSize; // @synthesize playButtonSize=_playButtonSize;
@property(readonly, nonatomic) struct CGSize containerSize; // @synthesize containerSize=_containerSize;
@property(readonly, nonatomic) struct CGRect activityIndicatorFrame;
- (double)errorLabelHeight;
@property(readonly, nonatomic) struct CGRect errorLabelFrame;
@property(readonly, nonatomic) struct UIEdgeInsets playButtonHitTestEdgeInsets;
@property(readonly, nonatomic) struct CGRect playButtonFrame;
@property(readonly, nonatomic) struct CGSize fittingSize;
- (id)initWithContainerSize:(struct CGSize)arg1 playButtonSize:(struct CGSize)arg2 activityIndicatorSize:(struct CGSize)arg3;

@end

