//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSString, UILabel, UITextView;
@protocol UITextViewDelegate;

@interface PTVTextView : UIView
{
    UIView *_debugHitFrameView;
    _Bool _forceHidePlaceholder;
    _Bool _useHashTagVariantKeyboard;
    UITextView *_textView;
    UILabel *_placeholder;
    id <UITextViewDelegate> _delegate;
    struct UIEdgeInsets _hitTestEdgeInsets;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <UITextViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool useHashTagVariantKeyboard; // @synthesize useHashTagVariantKeyboard=_useHashTagVariantKeyboard;
@property(nonatomic) _Bool forceHidePlaceholder; // @synthesize forceHidePlaceholder=_forceHidePlaceholder;
@property(retain, nonatomic) UILabel *placeholder; // @synthesize placeholder=_placeholder;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(nonatomic) struct UIEdgeInsets hitTestEdgeInsets; // @synthesize hitTestEdgeInsets=_hitTestEdgeInsets;
- (void)setAccessibilityLabel:(id)arg1;
- (id)accessibilityLabel;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)setFont:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)selectAll;
- (void)setKeyboardAppearance:(long long)arg1;
- (void)setTextViewText:(id)arg1;
- (void)setTextAlignment:(long long)arg1;
- (id)textOrPlaceholder;
- (id)initWithFont:(id)arg1 textColor:(id)arg2 placeholderString:(id)arg3 placeholderOpacity:(double)arg4 textViewDelegate:(id)arg5;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (_Bool)becomeFirstResponder;
- (_Bool)resignFirstResponder;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

