//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITextView.h>

@class NSTimer, UIView;

@interface PTVTouchProxyTextView : UITextView
{
    PTVTouchProxyTextView *_weakSelf;
    CDUnknownBlockType _linkSelectionCallback;
    UIView *_highlightView;
    NSTimer *_hideHighlightViewTimer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSTimer *hideHighlightViewTimer; // @synthesize hideHighlightViewTimer=_hideHighlightViewTimer;
@property(retain, nonatomic) UIView *highlightView; // @synthesize highlightView=_highlightView;
@property(copy, nonatomic) CDUnknownBlockType linkSelectionCallback; // @synthesize linkSelectionCallback=_linkSelectionCallback;
- (void)showHighlightViewWithFrame:(struct CGRect)arg1;
- (void)showHighlightViewAtPoint:(struct CGPoint)arg1;
- (void)hideHighlightView;
- (void)startTimerToHideHighlightView;
- (id)stringForLinkAtTouchPoint:(struct CGPoint)arg1;
- (struct CGRect)frameForLinkAtTouchPoint:(struct CGPoint)arg1 constrainedByLinkValues:(id)arg2;
- (struct CGRect)frameForLinkAtTouchPoint:(struct CGPoint)arg1;
- (_Bool)didTouchLink:(struct CGPoint)arg1;
- (void)handleTap:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 textContainer:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)dealloc;

@end

