//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterAppSPMMigration/NSObject-Protocol.h>

@class PTVTableView;

@protocol PTVUserProfilePagingDelegate <NSObject>
- (void)didTransitionPageToViewControllerAtIndex:(unsigned long long)arg1;

@optional
- (void)tableView:(PTVTableView *)arg1 didScrollToYContentOffset:(double)arg2 scrollDirectionUp:(_Bool)arg3;
- (void)willTransitionPageToViewControllerAtIndex:(unsigned long long)arg1;
@end

