//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSLayoutConstraint, PTVGradientView, UILayoutGuide;

@interface PTVVideoOverlayBackgroundShadeView : UIView
{
    PTVGradientView *_gradientView;
    UIView *_shadeView;
    UIView *_keyboardBackgroundView;
    NSLayoutConstraint *_keyboardHeightConstraint;
    UILayoutGuide *_shadeLayoutGuide;
    UILayoutGuide *_contentLayoutGuide;
    double _keyboardHeight;
}

- (void).cxx_destruct;
@property(nonatomic) double keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
@property(readonly, nonatomic) UILayoutGuide *contentLayoutGuide; // @synthesize contentLayoutGuide=_contentLayoutGuide;
@property(readonly, nonatomic) UILayoutGuide *shadeLayoutGuide; // @synthesize shadeLayoutGuide=_shadeLayoutGuide;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end

