//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterAppSPMMigration/NSObject-Protocol.h>

@class NSNumber, NSString, PTVWebRTCMediaStream, RTCAudioTrack, RTCVideoSource, RTCVideoTrack;

@protocol PTVWebRTCClientDelegate <NSObject>
- (void)didUpdateActiveSpeaker:(NSString *)arg1;
- (void)didTriggerICERestartAndShouldNotify:(_Bool)arg1;
- (void)didReceiveVideoRoomIsFull;
- (void)didDestroyVideoRoom;
- (void)didChangePublishingLocalVideoAndAudioState;
- (void)didChangeWebRTCActiveState;
- (void)didUpdateIsFullyConnectedForUserId:(NSString *)arg1;
- (void)didUpdateLocalAudioLevel:(NSNumber *)arg1;
- (void)didUpdateRemoteAudioLevel:(NSNumber *)arg1 forUserId:(NSString *)arg2;
- (void)didRemoveRemoteMediaStream:(PTVWebRTCMediaStream *)arg1 userId:(NSString *)arg2;
- (void)didUpdateRemoteMediaStream:(PTVWebRTCMediaStream *)arg1 userId:(NSString *)arg2;
- (void)didReceiveLocalAudioTrack:(RTCAudioTrack *)arg1;
- (void)didReceiveLocalVideoTrack:(RTCVideoTrack *)arg1;
- (void)didCreateLocalVideoSource:(RTCVideoSource *)arg1;

@optional
- (void)didLeave;
- (void)didStoreAndOutputLogEntry:(NSString *)arg1;
- (void)didChangeWebRTCClientState:(long long)arg1;
@end

