//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class PTVGuestRoomConfiguration;
@protocol PTVLoggedInUserCookieProtocol;

@interface PTVWebRTCClientNetworkHelper : NSObject
{
    id <PTVLoggedInUserCookieProtocol> _loggedInUser;
    PTVGuestRoomConfiguration *_configuration;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) PTVGuestRoomConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) id <PTVLoggedInUserCookieProtocol> loggedInUser; // @synthesize loggedInUser=_loggedInUser;
- (void)removeReachabilityStatusObserver:(id)arg1;
- (void)addReachabilityStatusObserver:(id)arg1;
@property(readonly, nonatomic) long long currentReachabilityStatus;
- (void)getTURNServersForGuestBroadcastingWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)get:(id)arg1 responseClass:(Class)arg2 queryParameters:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)sendPostRequest:(id)arg1 parameters:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)initWithLoggedInUser:(id)arg1 configuration:(id)arg2;

@end

