//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString, T1URTTimelineStatusItemViewModel, _TtC10TwitterURT23FeedbackActionViewModel, _TtC14TFSTwitterCore18URTFeedbackContext;

@interface T1URTDismissedStatusFeedbackViewModel : NSObject
{
    MISSING_TYPE *feedbackActionViewModel;
    MISSING_TYPE *statusViewModel;
}

- (void).cxx_destruct;
- (id)init;
- (_Bool)hasChildren;
@property(nonatomic, readonly) _TtC14TFSTwitterCore18URTFeedbackContext *feedbackContext;
@property(nonatomic, readonly) NSString *entryID;
@property(nonatomic, readonly) T1URTTimelineStatusItemViewModel *statusViewModel; // @synthesize statusViewModel;
@property(nonatomic, readonly) _TtC10TwitterURT23FeedbackActionViewModel *feedbackActionViewModel; // @synthesize feedbackActionViewModel;

@end

