//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface TAFBottomOverlayViewController : UIViewController
{
    MISSING_TYPE *overlay;
    MISSING_TYPE *overlayWindow;
    MISSING_TYPE *overlayContentViewProvider;
    MISSING_TYPE *overlayContentView;
    MISSING_TYPE *containerYWhenPanBegan;
    MISSING_TYPE *isDismissing;
    MISSING_TYPE *$__lazy_storage_$_overlayContainerView;
    MISSING_TYPE *$__lazy_storage_$_panRecognizer;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)panAction:(id)arg1;
- (void)reset;
- (void)dismissOverlay;
- (void)presentOverlayWith:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)loadView;
@property(nonatomic, readonly) unsigned long long tfn_supportedInterfaceOrientations;
@property(nonatomic, readonly) long long preferredStatusBarStyle;
- (id)initWithCoder:(id)arg1;
- (id)initWithOverlay:(id)arg1 overlayWindow:(id)arg2;

@end

