//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface TAFSKAdImpressionManager : NSObject
{
    MISSING_TYPE *scribe;
    MISSING_TYPE *minimumImpressionDuration;
    MISSING_TYPE *endImpressionTimingExperimentBucket;
    MISSING_TYPE *vtaRefactoringExperimentBucket;
    MISSING_TYPE *skAdNetwork4Enabled;
    MISSING_TYPE *skAdNetworkInterface;
    MISSING_TYPE *crashlyticsInterface;
    MISSING_TYPE *serialQueue;
    MISSING_TYPE *numberOfStartImpressionCalls;
    MISSING_TYPE *numberOfEndImpressionCalls;
    MISSING_TYPE *startImpressionStartDate;
    MISSING_TYPE *endImpressionStartDate;
    MISSING_TYPE *candidateImpression;
    MISSING_TYPE *currentImpression;
}

+ (id)sharedSerialQueue;
- (void).cxx_destruct;
- (id)init;
- (id)initWithScribe:(id)arg1 minimumImpressionDuration:(double)arg2 skAdNetworkInterface:(id)arg3 crashlyticsInterface:(id)arg4 serialQueue:(id)arg5 endImpressionTimingExperimentBucket:(unsigned long long)arg6 vtaRefactoringExperimentBucket:(unsigned long long)arg7 skAdNetwork4Enabled:(_Bool)arg8;
- (void)endImpressionWithPromotedContent:(id)arg1 scribeContext:(id)arg2;
- (void)startImpressionWithPromotedContent:(id)arg1 scribeContext:(id)arg2;

@end

