//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNItemsDataViewController.h>

@class MISSING_TYPE, TASSettings;
@protocol TASItemsDataViewControllerDelegate, TASSpaceModel;

@interface TASItemsDataViewController : TFNItemsDataViewController
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *spaceModel;
}

- (void).cxx_destruct;
- (id)initWithCollectionViewLayout:(id)arg1;
- (id)scribePageForToaster:(id)arg1;
- (void)logClickOnElement:(id)arg1 inComponent:(id)arg2;
- (id)scribeImpressionParameters;
- (id)scribeParameters;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (void)handleTapOnLeave:(id)arg1;
@property(nonatomic, retain) TASSettings *settings;
- (void)spaceModel:(id)arg1 didUpdateUsersModels:(id)arg2;
- (void)viewDidLoad;
- (id)initWithSpaceModel:(id)arg1;
@property(nonatomic, readonly) id <TASSpaceModel> spaceModel; // @synthesize spaceModel;
@property(nonatomic) __weak id <TASItemsDataViewControllerDelegate> delegate; // @synthesize delegate;

@end

