//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface TASTitleValue : NSObject
{
    MISSING_TYPE *value;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *titleEditViewText;
@property(nonatomic, readonly) _Bool isTitleEditViewEditable;
@property(nonatomic, readonly) _Bool isTitleEditViewHidden;
@property(nonatomic, readonly) NSString *navigationBarTitle;
@property(nonatomic, readonly) NSString *localizedDescriptiveTitle;
@property(nonatomic, readonly) NSString *title;
- (_Bool)isEqual:(id)arg1;
- (id)initWithSettingsTitle:(id)arg1 connectionState:(long long)arg2 isLoggedInUserCreator:(_Bool)arg3 isLoggedInUserAdmin:(_Bool)arg4 creatorUserDisplayFullName:(id)arg5;

@end

