//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSString, UIImageView, UILabel;

@interface TCRPlaceLabelView : UIView
{
    UILabel *_placeLabel;
    UIImageView *_iconView;
    unsigned long long _style;
}

+ (id)_fontForStyle:(unsigned long long)arg1;
+ (double)widthForText:(id)arg1 style:(unsigned long long)arg2 constrainedtoWidth:(double)arg3;
+ (double)heightForText:(id)arg1 style:(unsigned long long)arg2;
+ (struct CGSize)pinImageSize;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UILabel *placeLabel; // @synthesize placeLabel=_placeLabel;
- (void)layoutSubviews;
- (void)tfn_fontSizeChanged;
@property(copy, nonatomic) NSString *placeText;
- (id)initWithStyle:(unsigned long long)arg1;

@end

