//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, TFNGeoDataAccountAccessController, TFSTwitterLocation;
@protocol TFSTwitterGeoDataProvider;

@interface TFNAccessControlledGeoDataProvider : NSObject
{
    id <TFSTwitterGeoDataProvider> _globalGeoDataProvider;
    TFNGeoDataAccountAccessController *_accessController;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) TFNGeoDataAccountAccessController *accessController; // @synthesize accessController=_accessController;
@property(readonly, nonatomic) id <TFSTwitterGeoDataProvider> globalGeoDataProvider; // @synthesize globalGeoDataProvider=_globalGeoDataProvider;
- (void)getRealtimeLocationWithCallback:(CDUnknownBlockType)arg1;
- (void)getLocationServicesAvailableWithCallback:(CDUnknownBlockType)arg1;
- (void)stopUpdates;
- (void)startUpdates;
@property(readonly, getter=isUsingRetainedGeoDataAllowed) _Bool usingRetainedGeoDataAllowed;
@property double locationUpdateDuration;
@property double locationUpdateInterval;
@property(readonly, getter=isEnabled) _Bool enabled;
@property(readonly, copy) NSString *timezoneName;
@property(readonly) _Bool locationServicesAvailable;
@property(readonly) TFSTwitterLocation *currentLocation;
@property(readonly, getter=isCachedLocationAvailable) _Bool cachedLocationAvailable;
- (id)initWithGlobalGeoDataProvider:(id)arg1 accessController:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

