//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSString, TFNDirectMessageConversation, TFNDirectMessageDraftEntry;
@protocol TFNDirectMessagePostMessageOperationDelegate, TFNDirectMessageUserCache;

@interface TFNDirectMessagePostMessageOperation
{
    NSString *_accountID;
    TFNDirectMessageConversation *_conversation;
    NSString *_conversationKey;
    NSString *_conversationKeySignature;
    TFNDirectMessageDraftEntry *_message;
    NSArray *_encryptedConversationKeys;
    id <TFNDirectMessageUserCache> _userCache;
    id <TFNDirectMessagePostMessageOperationDelegate> _delegate;
}

- (void).cxx_destruct;
@property __weak id <TFNDirectMessagePostMessageOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) id <TFNDirectMessageUserCache> userCache; // @synthesize userCache=_userCache;
@property(retain, nonatomic) NSArray *encryptedConversationKeys; // @synthesize encryptedConversationKeys=_encryptedConversationKeys;
@property(readonly, nonatomic) TFNDirectMessageDraftEntry *message; // @synthesize message=_message;
@property(copy, nonatomic) NSString *conversationKeySignature; // @synthesize conversationKeySignature=_conversationKeySignature;
@property(copy, nonatomic) NSString *conversationKey; // @synthesize conversationKey=_conversationKey;
@property(readonly, nonatomic) TFNDirectMessageConversation *conversation; // @synthesize conversation=_conversation;
@property(readonly, copy, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
- (void)failedWithError:(id)arg1;
- (void)succeededWithObject:(id)arg1;
- (id)makeCommandWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithAccountID:(id)arg1 conversation:(id)arg2 conversationKey:(id)arg3 message:(id)arg4 userCache:(id)arg5 commandLoader:(id)arg6 context:(id)arg7;

@end

