//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface TFNDirectMessageCustomProfile : NSObject
{
    NSString *_customProfileID;
    NSString *_name;
    long long _profileImageShape;
    NSString *_avatarImageURLString;
    struct CGSize _avatarOriginalDimensions;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) struct CGSize avatarOriginalDimensions; // @synthesize avatarOriginalDimensions=_avatarOriginalDimensions;
@property(readonly, copy, nonatomic) NSString *avatarImageURLString; // @synthesize avatarImageURLString=_avatarImageURLString;
@property(readonly, nonatomic) long long profileImageShape; // @synthesize profileImageShape=_profileImageShape;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, copy, nonatomic) NSString *customProfileID; // @synthesize customProfileID=_customProfileID;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithCustomProfileID:(id)arg1 name:(id)arg2 profileImageShape:(long long)arg3 avatarImageURLString:(id)arg4 originalDimensions:(struct CGSize)arg5;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

