//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterAppSPMMigration/TFNDirectMessageAttachment-Protocol.h>
#import <TwitterAppSPMMigration/TFNTwitterDirectMessageCardDataSource-Protocol.h>
#import <TwitterAppSPMMigration/_TtP14TFSTwitterCore23TFSTwitterScribableItem_-Protocol.h>

@class TFCCardData;

@protocol TFNDirectMessageCardAttachment <TFNDirectMessageAttachment, TFNTwitterDirectMessageCardDataSource, _TtP14TFSTwitterCore23TFSTwitterScribableItem_>
@property(readonly, nonatomic) TFCCardData *cardData;
@end

