//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;
@protocol TFNDirectMessageExtractPublicKeysOperationDelegate;

@interface TFNDirectMessageExtractPublicKeysOperation
{
    NSString *_accountID;
    long long _userID;
    id <TFNDirectMessageExtractPublicKeysOperationDelegate> _delegate;
}

- (void).cxx_destruct;
@property __weak id <TFNDirectMessageExtractPublicKeysOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) long long userID; // @synthesize userID=_userID;
@property(readonly, copy, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
- (void)failedWithError:(id)arg1;
- (void)succeededWithObject:(id)arg1;
- (id)makeCommandWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithAccountID:(id)arg1 userID:(long long)arg2 commandLoader:(id)arg3 commandContext:(id)arg4;

@end

