//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSString, TFNDirectMessageConversation, TFNDirectMessageUser;

@interface TFNDirectMessageConversationParticipant : NSObject
{
    _Bool _isAdmin;
    TFNDirectMessageUser *_participatingUser;
    NSDate *_joinDate;
    long long _joinConversationEventID;
    long long _lastReadMessageEventID;
    NSString *_deviceID;
    NSString *_identityKey;
    TFNDirectMessageConversation *_conversation;
}

- (void).cxx_destruct;
@property(nonatomic) __weak TFNDirectMessageConversation *conversation; // @synthesize conversation=_conversation;
@property(copy, nonatomic) NSString *identityKey; // @synthesize identityKey=_identityKey;
@property(copy, nonatomic) NSString *deviceID; // @synthesize deviceID=_deviceID;
@property(readonly, nonatomic) _Bool isAdmin; // @synthesize isAdmin=_isAdmin;
@property(readonly, nonatomic) long long lastReadMessageEventID; // @synthesize lastReadMessageEventID=_lastReadMessageEventID;
@property(readonly, nonatomic) long long joinConversationEventID; // @synthesize joinConversationEventID=_joinConversationEventID;
@property(readonly, nonatomic) NSDate *joinDate; // @synthesize joinDate=_joinDate;
@property(readonly, nonatomic) TFNDirectMessageUser *participatingUser; // @synthesize participatingUser=_participatingUser;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (long long)compare:(id)arg1;
- (id)initWithUser:(id)arg1 joinDate:(id)arg2 joinConversationEventID:(long long)arg3 lastReadMessageEventID:(long long)arg4 isAdmin:(_Bool)arg5;
- (id)initWithUser:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

