//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface TFNTwitterAPIPlaceFetcher : NSObject
{
    NSString *_accountID;
    NSString *_osVersion;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *osVersion; // @synthesize osVersion=_osVersion;
@property(copy, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
- (id)searchPlacesWithLocation:(id)arg1 query:(id)arg2 queryType:(long long)arg3 response:(CDUnknownBlockType)arg4;
- (id)fetchPlacesWithLocation:(id)arg1 queryType:(long long)arg2 includeLatLonParams:(_Bool)arg3 response:(CDUnknownBlockType)arg4;
- (id)initWithAccountID:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

