//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TFNTwitterInactiveAccountRefreshUserRecurringTask
{
}

- (void)tfs_private_triggerRefreshOfAccounts:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)triggerFromService:(id)arg1 account:(id)arg2 event:(id)arg3 completion:(CDUnknownBlockType)arg4;

@end

