//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableArray, NSString;

@interface TFNTwitterCompositionPollingCard : NSObject
{
    _Bool _choicesAreValid;
    _Bool _isAudienceSelectionEnabled;
    NSString *_URI;
    double _pollDuration;
    long long _audienceType;
    NSMutableArray *_labels;
    NSMutableArray *_validatedLabels;
}

+ (id)_whitespaceNewlineAndControlCharacterSet;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *validatedLabels; // @synthesize validatedLabels=_validatedLabels;
@property(retain, nonatomic) NSMutableArray *labels; // @synthesize labels=_labels;
@property(readonly, nonatomic) _Bool isAudienceSelectionEnabled; // @synthesize isAudienceSelectionEnabled=_isAudienceSelectionEnabled;
@property(nonatomic) long long audienceType; // @synthesize audienceType=_audienceType;
@property(nonatomic) double pollDuration; // @synthesize pollDuration=_pollDuration;
@property(copy, nonatomic) NSString *URI; // @synthesize URI=_URI;
@property(nonatomic) _Bool choicesAreValid; // @synthesize choicesAreValid=_choicesAreValid;
@property(readonly, copy, nonatomic) NSDictionary *scribeItem;
@property(readonly, copy, nonatomic) NSString *scribeItemImpressionID;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (unsigned long long)_numberOfNonEmptyStringsInArray:(id)arg1;
- (_Bool)_array:(id)arg1 containsMinimumNonEmptyStrings:(unsigned long long)arg2;
- (void)_updateState;
- (_Bool)_hasTextFieldInput;
- (void)setChoice:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)choiceForIndex:(unsigned long long)arg1;
@property(readonly, copy, nonatomic) NSString *name;
@property(readonly, nonatomic) NSDictionary *choiceLabels;
@property(readonly, nonatomic) unsigned long long numberOfVisibleChoices;
@property(readonly, nonatomic) _Bool hasUserInput;
- (id)init;
- (id)initWithDuration:(double)arg1 isAudienceSelectionEnabled:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) unsigned long long isCurrentlyFirstImpression;
// Preceding property had unknown attributes: ?
// Original attribute string: TQ,?,N

@property(nonatomic) unsigned long long isDuplicateContentIDInstance;
// Preceding property had unknown attributes: ?
// Original attribute string: TQ,?,N

@property(readonly, copy, nonatomic) NSString *scribeComponent;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C,N

@property(readonly, copy, nonatomic) NSString *scribeElement;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C,N

@property(readonly, copy, nonatomic) NSString *scribeItemContentID;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C,N

@property(readonly, copy, nonatomic) NSString *scribeItemFirstImpressionID;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C,N

@property(readonly) Class superclass;

@end

