//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFSDependentConcurrentOperation.h>

@class NSError, NSString, TFNTwitterCompositionUploadContext, TFSTwitterStatusCompositionPendingState;

@interface TFNTwitterCompositionAssimilateReplyCompleteOperation : TFSDependentConcurrentOperation
{
    unsigned long long _updateStatusState;
    NSError *_updateStatusError;
    TFNTwitterCompositionUploadContext *_context;
    TFSTwitterStatusCompositionPendingState *_pendingState;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) TFSTwitterStatusCompositionPendingState *pendingState; // @synthesize pendingState=_pendingState;
@property(readonly, nonatomic) TFNTwitterCompositionUploadContext *context; // @synthesize context=_context;
@property(retain) NSError *updateStatusError; // @synthesize updateStatusError=_updateStatusError;
@property unsigned long long updateStatusState; // @synthesize updateStatusState=_updateStatusState;
- (void)run;
- (id)initWithContext:(id)arg1 pendingState:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

