//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFSAccountUserDefaults.h>

@interface TFSAccountUserDefaults (HealthUI)
+ (void)hui_setGraduatedAccessGraduatedPromptWithValue:(_Bool)arg1 for:(id)arg2;
+ (void)hui_setGraduatedAccessNewUserPromptWithValue:(_Bool)arg1 for:(id)arg2;
+ (void)hui_setGraduatedAccessNUXPromptWithValue:(_Bool)arg1 for:(id)arg2;
+ (_Bool)hui_didDisplayGraduatedAccessGraduatedPromptFor:(id)arg1;
+ (_Bool)hui_didDisplayGraduatedAccessNewUserPromptFor:(id)arg1;
@end

