//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface TFSTwitterPublicKeyBundleEntry : NSObject
{
    _Bool _isCurrentDevice;
    NSString *_identityKey;
    NSString *_registrationToken;
    NSDate *_registrationDate;
    long long _deviceType;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isCurrentDevice; // @synthesize isCurrentDevice=_isCurrentDevice;
@property(readonly, nonatomic) long long deviceType; // @synthesize deviceType=_deviceType;
@property(readonly, nonatomic) NSDate *registrationDate; // @synthesize registrationDate=_registrationDate;
@property(readonly, nonatomic) NSString *registrationToken; // @synthesize registrationToken=_registrationToken;
@property(readonly, nonatomic) NSString *identityKey; // @synthesize identityKey=_identityKey;
- (id)description;
- (id)init;
- (id)initWithIdentityKey:(id)arg1 registrationToken:(id)arg2 registrationDate:(id)arg3 deviceType:(long long)arg4 isCurrentDevice:(_Bool)arg5;

@end

