//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface TGFCoreImageFilterBase : NSObject
{
    NSArray *_filterNames;
    float _minAdjustmentValue;
    float _maxAdjustmentValue;
    float _defaultAdjustmentValue;
    float _inertAdjustmentValue;
    NSString *_identifier;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) float inertAdjustmentValue; // @synthesize inertAdjustmentValue=_inertAdjustmentValue;
@property(readonly, nonatomic) float defaultAdjustmentValue; // @synthesize defaultAdjustmentValue=_defaultAdjustmentValue;
@property(readonly, nonatomic) float maxAdjustmentValue; // @synthesize maxAdjustmentValue=_maxAdjustmentValue;
@property(readonly, nonatomic) float minAdjustmentValue; // @synthesize minAdjustmentValue=_minAdjustmentValue;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)configureFilter:(id)arg1 atIndex:(unsigned long long)arg2 adjustmentValue:(float)arg3 renderContext:(id)arg4;
- (void)apply:(id)arg1;
- (id)initWithIdentifier:(id)arg1 minAdjustmentValue:(float)arg2 maxAdjustmentValue:(float)arg3 defaultAdjustmentValue:(float)arg4 intertAdjustmentValue:(float)arg5 CIImageFilterNames:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

