//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class TLabsAudioPitchTransformer, TLabsAudioReverb;
@protocol TLabsAudioProcessorDelegate;

@interface TLabsAudioProcessor : NSObject
{
    _Bool _processingEnabled;
    id <TLabsAudioProcessorDelegate> _delegate;
    long long _currentSettingPreference;
    CDStruct_c2f466a4 _voiceTransformerParameters;
    TLabsAudioPitchTransformer *_previewTransformer;
    TLabsAudioPitchTransformer *_broadcastTransformer;
    TLabsAudioReverb *_previewReverb;
    TLabsAudioReverb *_broadcastReverb;
    CDStruct_79059171 _reverbParameters;
}

+ (id)sharedAudioProcessor;
- (void).cxx_destruct;
@property(retain) TLabsAudioReverb *broadcastReverb; // @synthesize broadcastReverb=_broadcastReverb;
@property(retain) TLabsAudioReverb *previewReverb; // @synthesize previewReverb=_previewReverb;
@property CDStruct_79059171 reverbParameters; // @synthesize reverbParameters=_reverbParameters;
@property(retain) TLabsAudioPitchTransformer *broadcastTransformer; // @synthesize broadcastTransformer=_broadcastTransformer;
@property(retain) TLabsAudioPitchTransformer *previewTransformer; // @synthesize previewTransformer=_previewTransformer;
@property CDStruct_c2f466a4 voiceTransformerParameters; // @synthesize voiceTransformerParameters=_voiceTransformerParameters;
@property(nonatomic, getter=isProcessingEnabled) _Bool processingEnabled; // @synthesize processingEnabled=_processingEnabled;
@property(nonatomic) long long currentSettingPreference; // @synthesize currentSettingPreference=_currentSettingPreference;
@property(nonatomic) __weak id <TLabsAudioProcessorDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_tlabs_analyzBufferListForPeakSample:(struct AudioBufferList *)arg1;
- (void)broadcastTransformerAudioBufferList:(struct AudioBufferList *)arg1 asbd:(struct AudioStreamBasicDescription)arg2;
- (void)broadcastStreamNumberOfFrames:(unsigned int)arg1 audioBufferList:(struct AudioBufferList *)arg2 asbd:(struct AudioStreamBasicDescription)arg3;
- (void)generateTestSinewaveStreamNumberOfFrames:(unsigned int)arg1 audioBufferList:(struct AudioBufferList *)arg2 asbd:(struct AudioStreamBasicDescription)arg3;
- (void)previewVoiceTransformerAudioBufferList:(struct AudioBufferList *)arg1 asbd:(struct AudioStreamBasicDescription)arg2;
- (void)setReverbWetMix:(float)arg1 dryMix:(float)arg2 damp:(float)arg3 roomSize:(float)arg4 width:(float)arg5;
@property(nonatomic, getter=isReverbEnabled) _Bool reverbEnabled;
@property(nonatomic) float voiceTransformerPitch;
@property(nonatomic, getter=isSoundboardEnabled) _Bool soundboardEnabled;
- (id)init;

@end

