//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TSKSandboxSupport : NSObject
{
}

+ (id)unpinFromLaunchActionFor:(id)arg1;
+ (id)pinToLaunchActionFor:(id)arg1;
+ (id)shareDeeplinkActionFor:(id)arg1 hostIdentifier:(id)arg2 playgroundDeeplinkId:(id)arg3 sender:(id)arg4;
+ (id)playgroundDeeplinkInvocations;
+ (void)configureParametersButtonFor:(id)arg1 customActionItems:(CDUnknownBlockType)arg2;
+ (void)configureToolbarFor:(id)arg1;
+ (void)configureShowcaseAdaptersFor:(id)arg1 showcaseGalleryReusesCells:(_Bool)arg2;
+ (void)configurePlaygroundDefaultsFor:(id)arg1 customParameterButtonActions:(CDUnknownBlockType)arg2 showcaseGalleryReusesCells:(_Bool)arg3;
+ (_Bool)isSandboxApp;
+ (void)applicationDidFinishLaunching:(id)arg1 configuration:(id)arg2;
+ (void)applicationDidFinishLaunching:(id)arg1;
- (void).cxx_destruct;
- (id)init;

@end

