//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterAppSPMMigration/NSObject-Protocol.h>

@class _TtC14TFSTwitterCore25TFSTwitterPromotedContent;

@protocol TTACoreStatusViewModelPromotedContentAdditions <NSObject>
@property(nonatomic) _Bool hasRecordedDwellImpression;
@property(nonatomic) _Bool hasRecordedImpression;
@property(nonatomic, readonly) _Bool allowDynamicAd;
@property(nonatomic, readonly) _Bool displayAsCompactPromotedTweet;
@property(nonatomic, readonly) _TtC14TFSTwitterCore25TFSTwitterPromotedContent *promotedContent;
@end

