//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@protocol TTAHashflagAnimationTypeProvider;

@interface TTAStatusInlineFavoriteButton
{
    long long _showDisabledEducationForReason;
    id <TTAHashflagAnimationTypeProvider> _animationTypeProvider;
}

+ (id)buttonImageNameForUIControlState:(unsigned long long)arg1 viewModel:(id)arg2 options:(unsigned long long)arg3 account:(id)arg4;
+ (id)buttonHoverImageNameForUIControlState:(unsigned long long)arg1 viewModel:(id)arg2 options:(unsigned long long)arg3 account:(id)arg4;
- (void).cxx_destruct;
@property(retain, nonatomic) id <TTAHashflagAnimationTypeProvider> animationTypeProvider; // @synthesize animationTypeProvider=_animationTypeProvider;
@property(nonatomic) long long showDisabledEducationForReason; // @synthesize showDisabledEducationForReason=_showDisabledEducationForReason;
- (_Bool)isEligibleForBrandedLike;
- (id)_t1_firstLikeAnimation;
- (id)_t1_generateBrandedLikeHashFlagAnimation;
- (id)tintColorForUIControlState:(unsigned long long)arg1;
- (id)createImageView;
- (id)animationTypeForTransitionToSelectedState;
- (void)statusDidUpdate:(id)arg1 options:(unsigned long long)arg2 displayTextOptions:(unsigned long long)arg3 animated:(_Bool)arg4 featureSwitches:(id)arg5;
- (id)actionSheetTitle;
- (id)initWithOptions:(unsigned long long)arg1 overrideSize:(id)arg2 account:(id)arg3 style:(long long)arg4;
- (id)initWithPillStyleAndOptions:(unsigned long long)arg1 overrideSize:(id)arg2 account:(id)arg3;
- (id)initWithOptions:(unsigned long long)arg1 overrideSize:(id)arg2 account:(id)arg3;

@end

