//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSNumber, TTMAssetSubtitles, TTMAssetVoiceEditParameters;

@interface TTMAssetVoiceRecording
{
    NSNumber *_clipIndex;
    NSNumber *_numberOfClips;
    NSNumber *_totalDurationMillis;
    NSArray *_audiowaveValues;
    TTMAssetSubtitles *_subtitles;
    double _cachedAssetDuration;
}

- (void).cxx_destruct;
@property(nonatomic) double cachedAssetDuration; // @synthesize cachedAssetDuration=_cachedAssetDuration;
@property(retain, nonatomic) TTMAssetSubtitles *subtitles; // @synthesize subtitles=_subtitles;
@property(retain, nonatomic) NSArray *audiowaveValues; // @synthesize audiowaveValues=_audiowaveValues;
@property(retain, nonatomic) NSNumber *totalDurationMillis; // @synthesize totalDurationMillis=_totalDurationMillis;
@property(retain, nonatomic) NSNumber *numberOfClips; // @synthesize numberOfClips=_numberOfClips;
@property(retain, nonatomic) NSNumber *clipIndex; // @synthesize clipIndex=_clipIndex;
- (void)_ttm_generateAVAssetWithOptions:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (double)duration;
- (struct CGSize)assetDimensions;
@property(retain, nonatomic) TTMAssetVoiceEditParameters *voiceEditParameters;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithTemporaryFile:(id)arg1 audiowaveValues:(id)arg2;
- (id)initWithPermanentFile:(id)arg1;
- (id)initWithTemporaryFile:(id)arg1;
- (id)initWithTemporaryFile:(id)arg1 assetDimensions:(struct CGSize)arg2;

@end

