//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSLocale;

@interface TTMAssetSubtitles
{
    NSArray *_entries;
    NSLocale *_locale;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSLocale *locale; // @synthesize locale=_locale;
@property(retain, nonatomic) NSArray *entries; // @synthesize entries=_entries;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)renderWithFormat:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)renderFinalDataWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)renderPreviewWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (unsigned long long)attachmentType;
- (struct CGSize)assetDimensions;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithEntries:(id)arg1 locale:(id)arg2;
- (id)init;

@end

