//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFSDependentConcurrentOperation.h>

@class AVAssetExportSession, NSURL, TFSCameraVideoCompositorComposition, TFSTimer;

@interface TTMAssetVideoCompositionExportOperation : TFSDependentConcurrentOperation
{
    TFSCameraVideoCompositorComposition *_videoCompositorComposition;
    NSURL *_exportURL;
    CDUnknownBlockType _progressHandler;
    CDUnknownBlockType _completion;
    TFSTimer *_progressTimer;
    AVAssetExportSession *_exportSession;
}

- (void).cxx_destruct;
@property(retain, nonatomic) AVAssetExportSession *exportSession; // @synthesize exportSession=_exportSession;
@property(retain, nonatomic) TFSTimer *progressTimer; // @synthesize progressTimer=_progressTimer;
@property(readonly, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(readonly, nonatomic) CDUnknownBlockType progressHandler; // @synthesize progressHandler=_progressHandler;
@property(readonly, nonatomic) NSURL *exportURL; // @synthesize exportURL=_exportURL;
@property(readonly, nonatomic) TFSCameraVideoCompositorComposition *videoCompositorComposition; // @synthesize videoCompositorComposition=_videoCompositorComposition;
- (void)_ftn_main_callbackProgressHandler;
- (void)_ttm_timer_progressTimerDidFire:(id)arg1;
- (void)run;
- (void)dealloc;
- (id)initWithVideoCompositorComposition:(id)arg1 exportURL:(id)arg2 progressHandler:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;

@end

