//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNItemsDataViewController.h>

@class NSArray, NSString, TTSRecentSearchCollectionItemAdapter, UICollectionViewFlowLayout;
@protocol TTSRecentSearchTypeaheadViewControllerDelegate;

@interface TTSRecentSearchTypeaheadViewController : TFNItemsDataViewController
{
    _Bool _viewDidLoadFired;
    NSArray *_results;
    id <TTSRecentSearchTypeaheadViewControllerDelegate> _delegate;
    TTSRecentSearchCollectionItemAdapter *_recentSearchAdapter;
    UICollectionViewFlowLayout *_flowLayout;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool viewDidLoadFired; // @synthesize viewDidLoadFired=_viewDidLoadFired;
@property(retain, nonatomic) UICollectionViewFlowLayout *flowLayout; // @synthesize flowLayout=_flowLayout;
@property(retain, nonatomic) TTSRecentSearchCollectionItemAdapter *recentSearchAdapter; // @synthesize recentSearchAdapter=_recentSearchAdapter;
@property(nonatomic) __weak id <TTSRecentSearchTypeaheadViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSArray *results; // @synthesize results=_results;
- (void)recentSearchCollectionItemAdapter:(id)arg1 didSelectItem:(id)arg2;
- (void)tfn_fontSizeChanged;
- (void)layoutMetricsDidChange:(id)arg1 to:(id)arg2;
- (id)initWithCollectionViewLayout:(id)arg1;
- (id)init;
- (id)initWithImagePipeline:(id)arg1 cellContext:(id)arg2 externalViewContext:(id)arg3 itemAdapterContext:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

