//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNItemsDataViewController.h>

@class NSArray, NSMapTable, NSMutableSet, NSSet, NSString, TFSObjectCache, TFSTwitterScribeContext, TTSTypeaheadUserTableRowAdapter, TTSUserTypeaheadViewControllerResults;
@protocol TTSSearchTypeaheadViewControllerContext, TTSUserTypeaheadViewControllerDelegate;

@interface TTSUserTypeaheadViewController : TFNItemsDataViewController
{
    NSMutableSet *_selectedUsers;
    _Bool _allowsMultipleSelection;
    _Bool _transparent;
    _Bool _localSearchEnabled;
    id <TTSUserTypeaheadViewControllerDelegate> _delegate;
    NSString *_typeaheadString;
    NSArray *_defaultUsers;
    NSArray *_pinnedActionItems;
    id <TTSSearchTypeaheadViewControllerContext> _context;
    TTSTypeaheadUserTableRowAdapter *_userAdapter;
    unsigned long long _typeaheadSource;
    TFSTwitterScribeContext *_scribeContext;
    TFSObjectCache *_resultsCache;
    TTSUserTypeaheadViewControllerResults *_results;
    NSMapTable *_scribeItemIndex;
}

+ (id)_scribeItemForUserReference:(id)arg1 token:(id)arg2;
- (void).cxx_destruct;
@property(copy, nonatomic) NSMapTable *scribeItemIndex; // @synthesize scribeItemIndex=_scribeItemIndex;
@property(retain, nonatomic) TTSUserTypeaheadViewControllerResults *results; // @synthesize results=_results;
@property(retain, nonatomic) TFSObjectCache *resultsCache; // @synthesize resultsCache=_resultsCache;
@property(readonly, nonatomic, getter=isLocalSearchEnabled) _Bool localSearchEnabled; // @synthesize localSearchEnabled=_localSearchEnabled;
@property(readonly, copy, nonatomic) TFSTwitterScribeContext *scribeContext; // @synthesize scribeContext=_scribeContext;
@property(readonly, nonatomic) unsigned long long typeaheadSource; // @synthesize typeaheadSource=_typeaheadSource;
@property(readonly, nonatomic) TTSTypeaheadUserTableRowAdapter *userAdapter; // @synthesize userAdapter=_userAdapter;
@property(readonly, nonatomic) id <TTSSearchTypeaheadViewControllerContext> context; // @synthesize context=_context;
@property(copy, nonatomic) NSArray *pinnedActionItems; // @synthesize pinnedActionItems=_pinnedActionItems;
@property(copy, nonatomic) NSArray *defaultUsers; // @synthesize defaultUsers=_defaultUsers;
@property(nonatomic, getter=isTransparent) _Bool transparent; // @synthesize transparent=_transparent;
@property(copy, nonatomic) NSString *typeaheadString; // @synthesize typeaheadString=_typeaheadString;
@property(nonatomic) _Bool allowsMultipleSelection; // @synthesize allowsMultipleSelection=_allowsMultipleSelection;
@property(nonatomic) __weak id <TTSUserTypeaheadViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_scribeClickForItem:(id)arg1;
- (void)_scribeResultsImpression;
- (void)_updateScribeItemIndexWithResults:(id)arg1 userResults:(id)arg2;
- (void)_applySelectionEnabledStateForUser:(id)arg1 toCell:(id)arg2;
- (void)_applyCheckedStateForUser:(id)arg1 toCell:(id)arg2;
- (void)_updateVisibleCellsState;
- (void)typeaheadUserAdapter:(id)arg1 didSelectUser:(id)arg2 atIndexPath:(id)arg3;
- (id)tableViewCellForItem:(id)arg1 atIndexPath:(id)arg2;
- (void)update:(_Bool)arg1;
@property(copy, nonatomic) NSSet *selectedUsers;
@property(nonatomic, getter=isUserSocialContextEnabled) _Bool userSocialContextEnabled;
- (void)viewDidLoad;
- (id)initWithCollectionViewLayout:(id)arg1;
- (id)init;
- (id)initWithContext:(id)arg1 typeaheadSource:(unsigned long long)arg2 scribeContext:(id)arg3 localSearchEnabled:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

