//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, TFSTwitterEntityMedia, TUCAppStoreData;

@interface TUCAppStoreWithDockedMediaDestinationDataImpl
{
    TFSTwitterEntityMedia *_mediaEntity;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) TFSTwitterEntityMedia *mediaEntity; // @synthesize mediaEntity=_mediaEntity;
- (id)initWithAppStoreData:(id)arg1 mediaEntity:(id)arg2;

// Remaining properties
@property(readonly, nonatomic) TUCAppStoreData *appStoreData;
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

