//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, NSURL, TFSTwitterEntityMedia;

@interface TUCBrowserWithDockedMediaDestinationDataImpl
{
    TFSTwitterEntityMedia *_mediaEntity;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) TFSTwitterEntityMedia *mediaEntity; // @synthesize mediaEntity=_mediaEntity;
- (id)initWithVanityURLString:(id)arg1 url:(id)arg2 mediaEntity:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isBrowserFallbackEnabled;
@property(readonly, nonatomic) _Bool isUniversalLinkAllowed;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSURL *url;
@property(readonly, copy, nonatomic) NSString *vanityURLString;

@end

