//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString, TFSTwitterUser, TUCDestinationModel;

@interface TUCJobDetailsComponentModel : NSObject
{
    TUCDestinationModel *_destination;
    NSString *_title;
    NSString *_location;
    NSNumber *_salaryMin;
    NSNumber *_salaryMax;
    NSNumber *_salaryInterval;
    NSString *_formattedSalary;
    NSString *_employmentType;
    NSString *_shortDescription;
    TFSTwitterUser *_owner;
}

+ (id)conditionallyApplyPromotedContentClickID:(id)arg1 toDestination:(id)arg2;
+ (id)componentWithJSON:(id)arg1 componentCreationContext:(id)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) TFSTwitterUser *owner; // @synthesize owner=_owner;
@property(readonly, nonatomic) NSString *shortDescription; // @synthesize shortDescription=_shortDescription;
@property(readonly, nonatomic) NSString *employmentType; // @synthesize employmentType=_employmentType;
@property(readonly, nonatomic) NSString *formattedSalary; // @synthesize formattedSalary=_formattedSalary;
@property(readonly, nonatomic) NSNumber *salaryInterval; // @synthesize salaryInterval=_salaryInterval;
@property(readonly, nonatomic) NSNumber *salaryMax; // @synthesize salaryMax=_salaryMax;
@property(readonly, nonatomic) NSNumber *salaryMin; // @synthesize salaryMin=_salaryMin;
@property(readonly, nonatomic) NSString *location; // @synthesize location=_location;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) TUCDestinationModel *destination; // @synthesize destination=_destination;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)withDestinationTransform:(CDUnknownBlockType)arg1;
- (id)withPromotedContent:(id)arg1;
@property(readonly, nonatomic) NSArray *axDestinations;
@property(readonly, nonatomic) unsigned long long type;
- (id)initWithDestination:(id)arg1 title:(id)arg2 location:(id)arg3 salaryMin:(id)arg4 salaryMax:(id)arg5 salaryInterval:(id)arg6 formattedSalary:(id)arg7 employmentType:(id)arg8 shortDescription:(id)arg9 owner:(id)arg10;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

