//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, UIView;
@protocol TUCUnifiedCardView;

@interface TUCPlayableTransitionDelegate : NSObject
{
    UIView<TUCUnifiedCardView> *_unifiedCardView;
    UIView *_videoViewSnapshot;
    struct CGRect _videoViewStartingFrame;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGRect videoViewStartingFrame; // @synthesize videoViewStartingFrame=_videoViewStartingFrame;
@property(retain, nonatomic) UIView *videoViewSnapshot; // @synthesize videoViewSnapshot=_videoViewSnapshot;
@property(retain, nonatomic) UIView<TUCUnifiedCardView> *unifiedCardView; // @synthesize unifiedCardView=_unifiedCardView;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)initWithUnifiedCardView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

