//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface TwitterAdvancedSearch : NSObject
{
    MISSING_TYPE *searchString;
    MISSING_TYPE *isFollowingFilterEnabled;
    MISSING_TYPE *isLocationFilterEnabled;
}

- (void).cxx_destruct;
- (id)init;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic, readonly) _Bool isEmpty;
- (id)initWithSearchString:(id)arg1 isFollowingFilterEnabled:(_Bool)arg2 isLocationFilterEnabled:(_Bool)arg3;
@property(nonatomic, readonly) _Bool isLocationFilterEnabled; // @synthesize isLocationFilterEnabled;
@property(nonatomic, readonly) _Bool isFollowingFilterEnabled; // @synthesize isFollowingFilterEnabled;
@property(nonatomic, readonly) NSString *searchString;

@end

