//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UILabel.h>

@interface UILabel (PTVLabelHeight)
+ (struct CGSize)ptv_GetSize:(struct CGSize)arg1 AttributedString:(id)arg2;
+ (struct CGSize)ptv_TextSize:(struct CGSize)arg1 text:(id)arg2 font:(id)arg3;
- (struct CGSize)ptv_textSize:(struct CGSize)arg1;
- (struct CGSize)ptv_textSize;
@end

