//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSSet, NSString, XKotlinBoolean, XKotlinDouble, XKotlinFloat, XKotlinInt, XKotlinLong;

@protocol XKotlinMultiplatform_settingsSettings
- (int)size_;
@property(nonatomic, readonly) NSSet *keys;
- (void)removeKey:(NSString *)arg1;
- (void)putStringKey:(NSString *)arg1 value:(NSString *)arg2;
- (void)putLongKey:(NSString *)arg1 value:(long long)arg2;
- (void)putIntKey:(NSString *)arg1 value:(int)arg2;
- (void)putFloatKey:(NSString *)arg1 value:(float)arg2;
- (void)putDoubleKey:(NSString *)arg1 value:(double)arg2;
- (void)putBooleanKey:(NSString *)arg1 value:(_Bool)arg2;
- (_Bool)hasKeyKey:(NSString *)arg1;
- (NSString *)getStringOrNullKey:(NSString *)arg1;
- (NSString *)getStringKey:(NSString *)arg1 defaultValue:(NSString *)arg2;
- (XKotlinLong *)getLongOrNullKey:(NSString *)arg1;
- (long long)getLongKey:(NSString *)arg1 defaultValue:(long long)arg2;
- (XKotlinInt *)getIntOrNullKey:(NSString *)arg1;
- (int)getIntKey:(NSString *)arg1 defaultValue:(int)arg2;
- (XKotlinFloat *)getFloatOrNullKey:(NSString *)arg1;
- (float)getFloatKey:(NSString *)arg1 defaultValue:(float)arg2;
- (XKotlinDouble *)getDoubleOrNullKey:(NSString *)arg1;
- (double)getDoubleKey:(NSString *)arg1 defaultValue:(double)arg2;
- (XKotlinBoolean *)getBooleanOrNullKey:(NSString *)arg1;
- (_Bool)getBooleanKey:(NSString *)arg1 defaultValue:(_Bool)arg2;
- (void)clear;

// Remaining properties
@property(nonatomic, readonly) int size;
@end

