//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNItemsDataViewController.h>

@class MISSING_TYPE, UIResponder;

__attribute__((visibility("hidden")))
@interface _TtC23T1TwitterDirectMessages36DirectMessageTypeaheadViewController : TFNItemsDataViewController
{
    MISSING_TYPE *account;
    MISSING_TYPE *scribe;
    MISSING_TYPE *scribeContext;
    MISSING_TYPE *selectionManager;
    MISSING_TYPE *delegate;
    MISSING_TYPE *dataSource;
    MISSING_TYPE *groupSelectionModeEnabled;
    MISSING_TYPE *createGroupEnabled;
    MISSING_TYPE *resultsFilter;
    MISSING_TYPE *customNextResponder;
    MISSING_TYPE *dataSourceObserverHandle;
    MISSING_TYPE *query;
    MISSING_TYPE *resultItems;
    MISSING_TYPE *isEncryptionEnabled;
    MISSING_TYPE *scribeItems;
    MISSING_TYPE *typeaheadUserRowAdapter;
}

- (void).cxx_destruct;
- (id)initWithCollectionViewLayout:(id)arg1;
- (void)update:(_Bool)arg1;
@property(nonatomic, readonly) UIResponder *nextResponder;
- (id)tableViewCellForItem:(id)arg1 atIndexPath:(id)arg2;
- (void)viewDidLoad;

@end

