//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNItemsDataViewController.h>

@class MISSING_TYPE, TFNTwitterAccount;

__attribute__((visibility("hidden")))
@interface _TtC23T1TwitterDirectMessages47DirectMessageConversationSettingsViewController : TFNItemsDataViewController
{
    MISSING_TYPE *account;
    MISSING_TYPE *conversation;
    MISSING_TYPE *adminTwitterUser;
    MISSING_TYPE *shouldShowAdminItem;
    MISSING_TYPE *scribeConversationPosition;
    MISSING_TYPE *$__lazy_storage_$_addPeopleBehavior;
    MISSING_TYPE *dmFeatureSwitches;
    MISSING_TYPE *$__lazy_storage_$_encryptedConversationBanner;
}

- (void).cxx_destruct;
- (id)initWithCollectionViewLayout:(id)arg1;
- (id)scribe;
- (id)scribeSection;
- (id)scribePage;
@property(nonatomic, readonly) _Bool tfn_supportsNavigationBarCollapsing;
- (void)dismissAfterReporting:(id)arg1;
- (void)blockMessageStatusUpdated:(id)arg1;
- (void)blockStatusUpdated:(id)arg1;
- (void)editGroupInfoWithSender:(id)arg1;
- (_Bool)shouldSelectItem:(id)arg1 atIndexPath:(id)arg2;
- (void)update:(_Bool)arg1;
- (void)tfn_fontSizeChanged;
- (void)viewDidLayoutSubviews;
- (void)viewWillFullyDisappear:(_Bool)arg1;
- (void)viewWillFullyAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic, readonly) TFNTwitterAccount *account; // @synthesize account;
- (void)directMessageConversationParticipantsListViewController:(id)arg1 didSelect:(id)arg2;
- (void)didTapAvatarImageView:(id)arg1 inCell:(id)arg2;

@end

