//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, T1DirectMessageAbstractConversationEntryViewModel;
@protocol T1DirectMessageAbstractEntryCellDelegate;

__attribute__((visibility("hidden")))
@interface _TtC23T1TwitterDirectMessages34DirectMessageEntryFeedbackCardCell
{
    MISSING_TYPE *feedbackCardDelegate;
    MISSING_TYPE *feedbackCardContainerView;
    MISSING_TYPE *feedbackCardHeightConstraint;
}

- (void).cxx_destruct;
- (void)feedbackCardViewDidResize:(id)arg1;
- (void)updateConstraints;
@property(nonatomic, retain) T1DirectMessageAbstractConversationEntryViewModel *entryViewModel;
@property(nonatomic) __weak id <T1DirectMessageAbstractEntryCellDelegate> delegate;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)cardView:(id)arg1 didFireViewEvent:(id)arg2;
- (id)layoutMetricsForCardView:(id)arg1;

@end

