//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFNViewController.h>

@class MISSING_TYPE, UIResponder;

__attribute__((visibility("hidden")))
@interface _TtC23T1TwitterDirectMessages53DirectMessageConversationCreationHeaderViewController : TFNViewController
{
    MISSING_TYPE *addressingViewController;
    MISSING_TYPE *rightBarButton;
    MISSING_TYPE *customNextResponder;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)layoutMetricsDidChange:(id)arg1 to:(id)arg2;
- (void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1;
@property(nonatomic, readonly) UIResponder *nextResponder;
- (_Bool)becomeFirstResponder;
@property(nonatomic, readonly) _Bool canBecomeFirstResponder;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

