//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC23T1TwitterDirectMessages34PinnedConversationsPromptViewModel : _TtCs12_SwiftObject
{
    MISSING_TYPE *title;
    MISSING_TYPE *titleImageName;
    MISSING_TYPE *buttonTitleName;
    MISSING_TYPE *$__lazy_storage_$_message;
    MISSING_TYPE *accountDefaults;
    MISSING_TYPE *maxPinnedConversationsAllowed;
}

@end

