//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFSConcurrentOperation.h>

@class MISSING_TYPE;

@interface _TtC23T1TwitterDirectMessagesP33_9555E7EAEFF26BB6A271EC9987E8C75920SendMessageOperation : TFSConcurrentOperation
{
    MISSING_TYPE *conversation;
    MISSING_TYPE *entry;
    MISSING_TYPE *result;
    MISSING_TYPE *accountID;
    MISSING_TYPE *sender;
}

- (void).cxx_destruct;
- (id)init;
- (void)run;

@end

