//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, T1DirectMessageAbstractConversationEntryViewModel, UIImage, UIView;
@protocol T1DirectMessageAbstractEntryCellDelegate, TVPPlayerSessionSource;

__attribute__((visibility("hidden")))
@interface _TtC23T1TwitterDirectMessages27DirectMessageEntryTweetCell
{
    MISSING_TYPE *eventHandlerBlock;
    MISSING_TYPE *tweetDelegate;
    MISSING_TYPE *statusView;
    MISSING_TYPE *statusViewDoubleTapGestureRecognizer;
    MISSING_TYPE *touchDownGestureRecognizer;
    MISSING_TYPE *animator;
    MISSING_TYPE *$__lazy_storage_$_statusBubbleView;
    MISSING_TYPE *overlayView;
    MISSING_TYPE *statusHeightConstraint;
}

- (void).cxx_destruct;
- (void)didLongPressStatus:(id)arg1;
- (void)didDoubleTapStatus:(id)arg1;
- (void)didDoubleTapStatusCommon;
- (void)didTapStatus:(id)arg1;
- (void)didTapStatus;
- (void)didTapStatusCommon;
- (void)statusDidUpdate:(id)arg1;
- (void)updateConstraints;
- (void)tintColorDidChange;
- (void)prepareForReuse;
@property(nonatomic, retain) T1DirectMessageAbstractConversationEntryViewModel *entryViewModel;
- (_Bool)accessibilityActivate;
- (void)layoutSubviews;
@property(nonatomic) __weak id <T1DirectMessageAbstractEntryCellDelegate> delegate;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) UIImage *playerPreviewImage;
@property(nonatomic, readonly) UIView *playerContainerView;
@property(nonatomic, readonly) id <TVPPlayerSessionSource> playerSessionSource;
- (id)previewConfigurationForLocation:(struct CGPoint)arg1;
- (id)handleStatusViewEvent:(id)arg1;

@end

