//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "OCFFlow-Protocol.h"

@protocol OCFFlowURLHandler, _TtP24TwitterOnboardingFeature26TwitterOnboardingPresenter_;

@protocol _TtP24TwitterOnboardingFeature31TwitterOnboardingFlowController_ <OCFFlow>
- (void)addFlowURLHandler:(id <OCFFlowURLHandler>)arg1;
- (void)startFlowWithPresenter:(id <_TtP24TwitterOnboardingFeature26TwitterOnboardingPresenter_>)arg1;
@property(nonatomic, readonly) long long flowStatus;
@end

