//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, OCFNavigationLink, UIFont, UIImage;

@interface ONBActionListItem : NSObject
{
    UIImage *_icon;
    NSString *_text;
    NSString *_detailText;
    UIFont *_textFont;
    UIFont *_detailTextFont;
    OCFNavigationLink *_link;
    long long _options;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) long long options; // @synthesize options=_options;
@property(readonly, nonatomic) OCFNavigationLink *link; // @synthesize link=_link;
@property(readonly, nonatomic) UIFont *detailTextFont; // @synthesize detailTextFont=_detailTextFont;
@property(readonly, nonatomic) UIFont *textFont; // @synthesize textFont=_textFont;
@property(readonly, nonatomic) NSString *detailText; // @synthesize detailText=_detailText;
@property(readonly, nonatomic) NSString *text; // @synthesize text=_text;
@property(readonly, nonatomic) UIImage *icon; // @synthesize icon=_icon;
- (id)initWithText:(id)arg1 detailText:(id)arg2 textFont:(id)arg3 detailTextFont:(id)arg4 icon:(id)arg5 link:(id)arg6 options:(long long)arg7;

@end

