//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class ONBAddBannerControl, TFNFlexibleLayoutView, TUIAvatarImageView, UIImage, UIImageView;
@protocol ONBExampleProfileViewDelegate;

@interface ONBExampleProfileView : UIView
{
    id <ONBExampleProfileViewDelegate> _delegate;
    ONBAddBannerControl *_bannerImageControl;
    TFNFlexibleLayoutView *_contentView;
    TUIAvatarImageView *_avatarImageView;
    UIImageView *_bannerImageView;
}

- (void).cxx_destruct;
- (void)private_didTapAddBannerControl:(id)arg1;
- (id)private_contentViewWithAccount:(id)arg1 userDataSource:(id)arg2 forcedAvatarImage:(id)arg3 forcedBannerImage:(id)arg4 showCurrentBanner:(_Bool)arg5;
- (struct CGSize)sizeThatFitsSize:(struct CGSize)arg1 layoutMetrics:(id)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(retain, nonatomic) UIImage *forcedBannerImage;
@property(retain, nonatomic) UIImage *forcedAvatarImage;
- (id)initWithAccount:(id)arg1 userDataSource:(id)arg2 forcedAvatarImage:(id)arg3 forcedBannerImage:(id)arg4 showCurrentBanner:(_Bool)arg5 delegate:(id)arg6;

@end

