//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class TFNItemsDataViewController;

@interface ONBFlexibleSpaceItemRefreshAssistant : NSObject
{
    TFNItemsDataViewController *_viewController;
    _Bool _isSizeTransitioning;
    CDUnknownBlockType _action;
}

- (void).cxx_destruct;
- (void)handleViewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)private_availableHeightDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithItemsDataViewController:(id)arg1 refreshAction:(CDUnknownBlockType)arg2;

@end

