//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary;
@protocol ONBSubtaskDataObservableFactory;

@interface ONBSubtaskDataObservable : NSObject
{
    NSMutableDictionary *_observables;
    NSMutableDictionary *_observers;
    NSMutableDictionary *_values;
    NSMutableDictionary *_subtaskDataObservers;
    id <ONBSubtaskDataObservableFactory> _factory;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <ONBSubtaskDataObservableFactory> factory; // @synthesize factory=_factory;
- (void)_t1_setObject:(id)arg1 forKey:(id)arg2;
@property(readonly, nonatomic) NSDictionary *allKeysAndValues;
- (id)objectForKey:(id)arg1;
- (void)addObserver:(CDUnknownBlockType)arg1 forKey:(id)arg2 initialValue:(id)arg3;
- (id)init;

@end

