//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@protocol ONBShowCodeViewControllerDelegate;

@interface ONBShowCodeViewController
{
    id <ONBShowCodeViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)abandon;
- (void)submit;
- (id)private_itemWithStyle:(long long)arg1 code:(id)arg2;
- (id)calculatedLayoutMetrics;
- (id)initWithAccount:(id)arg1 componentsViewModel:(id)arg2 style:(long long)arg3 code:(id)arg4 delegate:(id)arg5;

@end

