//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableSet, NSString, OCFSignUpSubtask, OCFSignUpSubtaskState, ONBSignUpViewController;
@protocol ONBSubtaskControllerDelegate;

@interface ONBSignUpSubtaskController
{
    OCFSignUpSubtask *_subtask;
    OCFSignUpSubtaskState *_state;
    id <ONBSubtaskControllerDelegate> _delegate;
    ONBSignUpViewController *_signUpViewController;
    NSMutableSet *_didScribeEditForElementSet;
    NSMutableSet *_didScribeValidationErrorForElementSet;
}

+ (id)supportedSubtaskClasses;
- (void).cxx_destruct;
- (id)private_scribeElementForField:(long long)arg1;
- (void)signUpViewController:(id)arg1 didSelectContactType:(long long)arg2;
- (void)signUpViewController:(id)arg1 didShowErrorInField:(long long)arg2;
- (void)signUpViewController:(id)arg1 didChangeTextInField:(long long)arg2;
- (void)signUpViewController:(id)arg1 didReturnInstrumentationResult:(id)arg2;
- (void)signUpViewController:(id)arg1 didTapNextWithName:(id)arg2 countryCode:(id)arg3 phone:(id)arg4 email:(id)arg5 birthday:(id)arg6;
- (id)subtaskData;
- (void)restartWithNavigationContext:(id)arg1 navigationLink:(id)arg2;
- (void)startWithNavigationContext:(id)arg1 navigationLink:(id)arg2;
- (id)initWithSubtask:(id)arg1 flowToken:(id)arg2 delegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

