//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDictionary, NSString, ONBAddAvatarSuggestionView, ONBAddAvatarView, T1PhotoSelection, T1PickAndFilterPhotoFlowController, TFNAvatarHeaderView, TFNTwitterAccount;
@protocol ONBSelectAvatarViewControllerDelegate;

@interface ONBSelectAvatarViewController
{
    id <ONBSelectAvatarViewControllerDelegate> _delegate;
    _Bool _requireAvatar;
    NSString *_avatarSubmitScribeElement;
    NSDictionary *_avatarSubmitScribeParameters;
    ONBAddAvatarSuggestionView *_suggestionView;
    ONBAddAvatarView *_addAvatarView;
    unsigned long long _avatarImageType;
    T1PickAndFilterPhotoFlowController *_photoPicker;
    T1PhotoSelection *_avatarPhoto;
    TFNAvatarHeaderView *_avatarHeaderView;
    TFNTwitterAccount *_account;
}

- (void).cxx_destruct;
- (void)private_userDataSourceDidUpdate;
- (void)private_updateSuggestionView;
- (void)private_updateAddAvatarView;
- (void)private_updateAvatarHeaderView;
- (void)private_setAvatarImageType:(unsigned long long)arg1;
- (void)private_selectAvatarPhoto:(id)arg1 ofType:(unsigned long long)arg2 scribeElement:(id)arg3 scribeParameters:(id)arg4;
- (void)private_clearAvatarImage;
- (void)private_startFilterFlowWithImage:(id)arg1;
- (void)private_startPickAndFilterFlowFromView:(id)arg1;
- (id)private_suggestionItem;
- (id)private_avatarItems;
- (void)private_avatarImageViewTapped:(id)arg1;
- (void)private_addAvatarViewTapped:(id)arg1;
- (_Bool)dropInteraction:(id)arg1 canHandleSession:(id)arg2;
- (id)dropInteraction:(id)arg1 sessionDidUpdate:(id)arg2;
- (void)dropInteraction:(id)arg1 performDrop:(id)arg2;
- (void)pickAndFilterPhotoFlowController:(id)arg1 removePhotoType:(long long)arg2;
- (void)pickAndFilterPhotoFlowController:(id)arg1 userDidCancelPhotoType:(long long)arg2;
- (void)pickAndFilterPhotoFlowController:(id)arg1 userDidSelectPhoto:(id)arg2 type:(long long)arg3;
- (void)suggestionViewDidSelectCamera:(id)arg1;
- (void)suggestionView:(id)arg1 didSelectAvatarImage:(id)arg2 withForegroundIndex:(long long)arg3 backgroundIndex:(long long)arg4;
- (void)viewDidLoad;
- (long long)submittability;
- (void)submit;
- (void)abandon;
- (void)dealloc;
- (id)initWithAccount:(id)arg1 componentsViewModel:(id)arg2 delegate:(id)arg3 requireAvatar:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

