//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface ONBSignUpViewControllerInputState : NSObject
{
    NSString *_emailModeButtonLabel;
    NSString *_emailModeNextButtonLabel;
    NSString *_navigationLabel;
    NSString *_nextButtonLabel;
    NSString *_phoneModeButtonLabel;
    unsigned long long _allowedIdentifiers;
    long long _contactType;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) long long contactType; // @synthesize contactType=_contactType;
@property(readonly, nonatomic) _Bool isEmailAllowed;
@property(readonly, nonatomic) _Bool isPhoneAllowed;
- (long long)defaultVisibleContactField;
- (long long)visibleContactFieldForCurrentField:(long long)arg1 phoneText:(id)arg2 emailText:(id)arg3;
- (id)nextButtonTitleForNavigation:(_Bool)arg1;
- (id)swapButtonTitleForCurrentField:(long long)arg1;
- (void)toggleContactType;
- (_Bool)isSelectableContactField:(long long)arg1;
@property(readonly, nonatomic) long long contactField;
- (id)initWithPhoneModeButtonLabel:(id)arg1 emailModeButtonLabel:(id)arg2 nextButtonLabel:(id)arg3 emailModeNextButtonLabel:(id)arg4 navigationLabel:(id)arg5 allowedIdentifiers:(unsigned long long)arg6;

@end

