//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class ONBSelectBannerViewController, T1PhotoSelection;

@protocol ONBSelectBannerViewControllerDelegate <NSObject>
- (void)selectBannerViewControllerDidTapAddImage:(ONBSelectBannerViewController *)arg1;
- (void)selectBannerViewControllerDidTapSkip:(ONBSelectBannerViewController *)arg1;
- (void)selectBannerViewController:(ONBSelectBannerViewController *)arg1 didTapNextWithPhoto:(T1PhotoSelection *)arg2;
@end

