//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface T1DirectMessageInboxViewModelConversationAvatarUpdatedEntryDisplayTextBuilder : NSObject
{
}

+ (id)inboxDisplayTextForConversationAvatarUpdatedEntry:(id)arg1 account:(id)arg2;

@end

