//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, TFSFlavoredRange;

@interface T1DirectMessageConversationLocalMessageEntryViewModel
{
    _Bool _didParseMessageText;
    NSString *_text;
    TFSFlavoredRange *_showMoreLinkRange;
}

+ (id)showMoreLinkAttributes;
+ (id)showMoreLinkColor;
- (void).cxx_destruct;
- (void)_parseMessageEntryText;
- (id)text;
- (id)showMoreTextRange;

@end

