//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface T1UserRecommendationListFollowAllSectionHeaderView
{
}

+ (Class)checkmarkControlClass;
+ (double)heightWithHeaderText:(id)arg1 detailText:(id)arg2 layoutMetrics:(id)arg3;
- (id)initWithReuseIdentifier:(id)arg1;

@end

