//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSIndexPath, UIView;

@protocol TFNDataSourceScrollPositionAssociation <NSObject>
- (id)scrollPositionIdentifierForElementAtIndexPath:(NSIndexPath *)arg1 inView:(UIView *)arg2;
- (NSIndexPath *)indexPathForElementWithScrollPositionIdentifier:(id)arg1 inView:(UIView *)arg2;
@end

