//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class UIView, UIWindow;

@protocol TFNMediaTransitionDelegate <NSObject>
- (struct CGRect)mediaTransitionPreviewFrameInWindow:(UIWindow *)arg1 forObject:(id)arg2;

@optional
- (_Bool)mediaTransitionShouldDismissPresentingViewControllerForObject:(id)arg1;
- (struct CGRect)mediaTransitionPreviewHostViewFrameInWindow:(UIWindow *)arg1 forObject:(id)arg2;
- (UIView *)mediaTransitionPreviewHostViewForObject:(id)arg1;
- (struct CGRect)mediaTransitionPreviewContentsRectForObject:(id)arg1;
- (long long)mediaTransitionPreviewContentModeForObject:(id)arg1;
- (void)mediaTransitionOfType:(long long)arg1 didEndForObject:(id)arg2;
- (void)mediaTransitionOfType:(long long)arg1 willBeginForObject:(id)arg2;
- (void)mediaTransitionSetPreviewHidden:(_Bool)arg1 forObject:(id)arg2;
@end

