//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSString, UIImage;

@protocol TFNPickableValue <NSObject>
@property(nonatomic, readonly) NSString *valueName;

@optional
@property(nonatomic, readonly) NSString *valueShortName;
@property(nonatomic, readonly) NSString *valueDetail;
@property(nonatomic, readonly) UIImage *valueIcon;
@end

