//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSNumber, NSString, TFNTwitterComposition, TFNTwitterFeedbackAction;
@protocol _TtP14TFSTwitterCore18URTImpressionCache_;

@protocol TFNTwitterHomeTimelineStream <NSObject>
+ (_Bool)isApplicationLaunchLoadInitialRequestCompletedOnceForAccountID:(NSString *)arg1;
- (void)didTapTombstoneViewTweetOnStreamObject:(id)arg1;
- (void)removeAllStreamObjects;
- (void)dismissStreamObject:(id)arg1 viaFeedbackAction:(TFNTwitterFeedbackAction *)arg2;
- (_Bool)removeStreamObject:(id)arg1;
- (_Bool)isEmpty;
- (_Bool)hasRealData;
- (_Bool)hasUnreadItems;
- (void)didViewStreamObjects:(NSArray *)arg1;
@property(nonatomic, readonly) unsigned long long applicationLaunchInitialRequestState;
- (NSDictionary *)getVisibleScrollPositionState;
- (void)setVisibleScrollPositionState:(NSDictionary *)arg1;
- (NSString *)scribePage;
- (void)loadNewerWithSource:(long long)arg1 pushToHomeTweetId:(NSNumber *)arg2 completion:(void (^)(_Bool, _Bool))arg3;
- (void)loadNewerWithSource:(long long)arg1 completion:(void (^)(_Bool, _Bool))arg2;
- (NSString *)topCursor;
- (_Bool)loadNewerFromStatusPosting:(TFNTwitterComposition *)arg1;
@property(nonatomic, readonly) NSArray *itemsToBeSerialized;
@property(nonatomic, readonly) id <_TtP14TFSTwitterCore18URTImpressionCache_> impressionCache;
@end

