//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TwitterSPMMigration/TFSEventDrivenTraceRepository.h>

@interface TFSEventDrivenTraceRepository (ONB)
- (void)private_activateWithTraceType:(id)arg1 rootSpan:(CDUnknownBlockType)arg2;
- (void)activateOnboardingOpenHomeTimelineTrace;
- (void)activateOnboardingLoggedOutWelcomeStartTrace;
- (void)activateOnboardingLoggedOutSignUpStartTrace;
- (void)activateOnboardingLoggedInSignUpStartTrace;
@end

