//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface THFURTHomeTimelineStreamFactory : NSObject
{
    MISSING_TYPE *applicationLink;
    MISSING_TYPE *homeConfiguration;
}

- (void).cxx_destruct;
- (id)init;
- (id)createWithAccount:(id)arg1;
- (id)initWithApplicationLink:(id)arg1 homeConfiguration:(id)arg2;

@end

