//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (ONBComponentCollectionViewProvider)
- (struct CGRect)t1_private_baseBoundsForProvidedView:(id)arg1;
- (struct CGRect)t1_headerViewBoundsForComponentsViewProvider:(id)arg1;
- (struct CGRect)t1_footerViewBoundsForComponentsViewProvider:(id)arg1;
- (void)t1_configureItemsAndActionsForComponentsViewProvider:(id)arg1 nextAction:(SEL)arg2 skipAction:(SEL)arg3;
- (void)tfn_presentDiscoverabilityOptionsFromSource:(id)arg1 scribePage:(id)arg2 account:(id)arg3;
@property(readonly, nonatomic) long long t1_preferredOnboardingPresenterCancelButtonStyle;
@end

